### ISSUE TITLE
Prototype Token Configuration is being lost when exiting the game

### ISSUE THREAD

**Issue by dsorrentino** [foundryvtt/foundryvtt#8155] opened 2022-09-08 20:52 UTC
### What happened?

Changes to the Prototype Token on Actors are lost when you exit/enter a world.

### What ways of accessing Foundry can you encounter this issue in?

- [ ] Native App (Electron)
- [X] Chrome
- [ ] Firefox
- [ ] Safari
- [ ] Other

### Reproduction Steps

- Enter World
- Create/Edit Actor in World
- Click `Prototype Token`
- Change the `Display Name` from `Never Displayed` to `Always for Everyone`
- Click `Update Token`
- Click `Close` on Actor Sheet
- At this point you can go back in and verify it was changed and it will still show `Always for Everyone`
- Click `Return to Setup`
- Click `Launch World` on the world you were just in and examine the Actors Prototype Token and it will be reset to `Never Displayed`.

This appears to be true for ALL settings in the Prototype Token, they all get reset when you exit/enter a world.

### What core version are you reporting this for?

Version 10 (build 280)

### Bug Checklist

- [X] The issue occurs while all Modules are disabled

**Comment by aaclayton** [comment] 2022-09-08 21:26
Duplicate of https://github.com/foundryvtt/foundryvtt/issues/8073

**Closed by aaclayton** 2022-09-08 21:26 UTC
Labels: bug
