### ISSUE TITLE
Add support for previewing Audio in File Picker

### ISSUE THREAD

**Issue by cswendrowski** [foundryvtt/foundryvtt#8861] opened 2023-02-06 23:54 UTC
Combat Themes revealed how nice it is to hear a soundfile - images are easy to visually preview, audio not so much. We should attach a button that plays the sound when clicked.

**Comment by aaclayton** [comment] 2023-08-30 12:17
Closing as duplicate of #5808

**Closed by aaclayton** 2023-08-30 12:17 UTC
Labels: ux
