### ISSUE TITLE
Hover token event still fires even if the tokens are obscured by HUD elements.

### ISSUE THREAD

**Issue by Fyorl** [foundryvtt/foundryvtt#7152] opened 2022-05-26 11:08 UTC
Originally in GitLab by @Fyorl

Originally reported by Mana#4176  https://discord.com/channels/170995199584108546/872553750877835264/964771862401941524

**ALL MODULES DISABLED?** true  
**OS, Hosting, Browser (if applicable):** Win10, Electron  
**Short Description of bug:** Hover token event happens once for every token past recently opened sheet.  
**Simple steps to reproduce the bug:**
1) `CONFIG.debug.hooks` = true
2) Open actor sheet over several tokens.
3) Mouse around over the sheet
4) Note how hover token events fire once for every token as if the sheet wasn't there, as appropriate for mouse position.

Tested with pf1 and dnd5e with all modules disabled.

If a token has been hovered over even once since load, the behaviour does not occur for that token.

Edit: This also happens if you hover tokens under the sidebar, no sheet needed.

**Comment by aaclayton** [comment] 2022-06-14 21:06
I am not able to reproduce this issue in Chrome or Firefox. Maybe @mattexdee can take a stab at it and if its nonrepro we can close it.

**Comment by mattexdee** [comment] 2022-06-14 21:20
@aaclayton, I was able to replicate this in V10 in Chrome. I've attached a recording of it occurring:
https://user-images.githubusercontent.com/5018947/173690729-e28c454e-ea31-4f54-a974-92c61755ecaf.mp4

**Comment by aaclayton** [comment] 2024-05-20 21:17
@dev7355608 we've changed some of the ways that hover and mouse-events function. Is this still an "issue"? Should we care about it?

**Comment by dev7355608** [comment] 2024-05-21 12:29
It looks like this was already fixed in V11. I'm not able to reproduce this issue in V11 or V12.

**Closed** 2024-05-21 13:07 UTC
Labels: bug, tokens
