### ISSUE TITLE
Function descriptions don't include default values

### ISSUE THREAD

**Issue by esb** [foundryvtt/foundryvtt#11814] opened 2024-11-18 21:06 UTC
### Where did you find it, or where does it belong for requests?

V10 API Documentation (https://foundryvtt.com/api/v10/)

### What page or file needs a look at?

https://foundryvtt.com/api/functions/foundry.utils.mergeObject.html

### What core version are you reporting this for?

Version 12 Build 331

### What is wrong, in your opinion?

The API documentation lists function parameters, but fails to describe any defaults that may apply.

For example, the ``mergeObject`` contains a set of optional options, but does not describe the default value (true/false) assigned to each option.

```javascript
options: {
    insertKeys: boolean;
    insertValues: boolean;
    overwrite: boolean;
    recursive: boolean;
    inplace: boolean;
    enforceTypes: boolean;
    performDeletions: boolean;
} = {}
```

**Comment by stwlam** [comment] 2024-11-18 21:34
Duplicate of #11576

**Closed by stwlam** 2024-11-18 21:34 UTC
Labels: documentation, duplicate, todelete
