### ISSUE TITLE
Update All adds package warnings for every existing module

### ISSUE THREAD

**Issue by DJ4ddi** [foundryvtt/foundryvtt#9816] opened 2023-07-21 16:37 UTC
### What happened?

When using the button to update all modules, FoundryVTT now reports package warnings for every outdated module in the repository. And I'm not talking about the installed ones - no, I mean *literally every module*, even if it was never installed.

### What ways of accessing Foundry can you encounter this issue in?

- [X] Native App (Electron)
- [ ] Chrome
- [X] Firefox
- [ ] Safari
- [ ] Other

### Reproduction Steps

- Setup a clean FoundryVTT install.
- Install one module so that the repository is refreshed when updating.
- Click the "Update All" button.
- Open the package warnings dialog. Observe how there are warnings for hundreds of packages that were never installed.

### What core version are you reporting this for?

11.306

### Bug Checklist

- [X] The issue occurs while all Modules are disabled

**Comment by Fyorl** [comment] 2023-07-21 16:42
Duplicate of #9811

**Closed by Fyorl** 2023-07-21 16:42 UTC
Labels: bug
