### ISSUE TITLE
QoL: Allow RollTables to be dropped onto the Macro Bar

### ISSUE THREAD

**Issue by mclemente** [foundryvtt/foundryvtt#7549] opened 2022-07-19 04:59 UTC
Add a localization string for formatting
```json
"locString": "{document}: {name}"
```

Add the following code (for V10):

```js
Hooks.on("hotbarDrop", (hotbar, data, slot) => {
	if (data.type !== "RollTable") return true;
	const table = game.tables.get(data.uuid.split(".")[1]);
	if (!table) return true;
	// Make a new macro for the RollTable
	Macro.create({
		name: game.i18n.format("locString", { document: game.i18n.localize(`DOCUMENT.${data.type}`), name: table.name }),
		type: "script",
		scope: "global",
		command: `game.tables.get("${table.id}").draw();`,
		img: "icons/svg/d20-grey.svg",
	}).then((macro) => {
		game.user.assignHotbarMacro(macro, slot);
	});
	return false;
});
```

### User Experience

This turns rolling from tables into a single button press (as opposed to going into RollTables > Clicking the table > clicking roll) and makes creating a simple macro easier for users that don't know JS.

### Priority/Importance

Low.

**Comment by paulohdsc** [comment] 2022-07-19 17:45
Related issue: https://github.com/foundryvtt/foundryvtt/issues/5756

**Comment by aaclayton** [comment] 2022-07-19 18:42
Closing as duplicate of #5756

**Closed by aaclayton** 2022-07-19 18:42 UTC
Labels: ux, macros, roll-tables
