### ISSUE TITLE
Transparent white overlay over the scene if no background image is set

### ISSUE THREAD

**Issue by dev7355608** [foundryvtt/foundryvtt#8405] opened 2022-10-20 14:09 UTC
### What happened?

`Interface#drawOutline` draws a rectangle over the scene if not background image is set.
```js
    if ( displaySceneOutline ) outline.lineStyle({
      alignment: 1,
      alpha: 0.25,
      color: 0x000000,
      join: PIXI.LINE_JOIN.BEVEL,
      width: 4
    }).beginFill(0xFFFFFF, 0.025).drawShape(dimensions.sceneRect).endFill();
```
The rectangle would need to be drawn in the primary canvas group as a replacement for the background image as in v9 if it's important to keep this behavior.

### What ways of accessing Foundry can you encounter this issue in?

- [ ] Native App (Electron)
- [ ] Chrome
- [ ] Firefox
- [ ] Safari
- [ ] Other

### Reproduction Steps

.

### What core version are you reporting this for?

Version 10 Stable 4 (build 288)

### Bug Checklist

- [X] The issue occurs while all Modules are disabled

**Comment by dev7355608** [comment] 2022-11-10 12:32
The outline shouldn't be in the primary group of course, but surely overlaying the entire scene with a 2.5% transparent white rectangle if no background image is set isn't intended?

**Comment by aaclayton** [comment] 2022-11-10 13:29
> The outline shouldn't be in the primary group of course, but surely overlaying the entire scene with a 2.5% transparent white rectangle if no background image is set isn't intended?

It was intended as a way to illustrate to the user what the "playable area" of the Scene is because otherwise, without a background image, you don't have a visual indication of that. Admittedly there may be better ways to do that.

**Comment by dev7355608** [comment] 2022-11-10 15:15
I noticed this issue because I was irritated by fact that in scenes without background image the fog of war is gray instead of black except in the padding, which wasn't the case in v9. The white overlay makes everything in the playable area slightly brighter. You could just set the texture of `canvas.primary.background` to `PIXI.Texture.WHITE` with 0.025 alpha instead of making it invisible if no background image is set; then you can get rid of the white rectangle in the outline.

**Comment by aaclayton** [comment] 2022-11-11 14:37
@Feu-Secret could you take a look at @dev7355608's suggestion in the above message and see if you think that would be a more sensible approach?

**Comment by Feu-Secret** [comment] 2022-11-11 15:13
> @Feu-Secret could you take a look at @dev7355608's suggestion in the above message and determine if you think that would be a more sensible approach?

Yes. I reopen the issue and assign it to the next milestone.

**Closed** 2022-11-17 20:37 UTC
Labels: scenes, canvas
