### ISSUE TITLE
Explored colour rendering strangely on Macbook Pro

### ISSUE THREAD

**Issue by Fyorl** [foundryvtt/foundryvtt#8086] opened 2022-09-05 11:27 UTC
Originally reported by DemonWolf69#1458 https://discord.com/channels/170995199584108546/956306859491471420/1015314787757994054

**ALL MODULES DISABLED?** True.  
**OS:** macbook pro 13" MacOS Monterey 12.5.1.  
**Bug:** Running from app, GM view background washed out,  Token view looks normal except explored sections outside of current field of view.  From browser, GM view looks normal, Token view has same problem with explored areas.

![image](https://user-images.githubusercontent.com/207433/188438381-fcc2d295-f3cf-4d69-b0bc-84ff832ef06d.png)

![image](https://user-images.githubusercontent.com/207433/188438423-f558b1de-3e36-430b-9e57-e8506c4d5a56.png)

![image](https://user-images.githubusercontent.com/207433/188438459-5944da5f-e046-4201-9afa-562c3160502e.png)

**Comment by Feu-Secret** [comment] 2022-12-01 17:58
Waiting for user feedback. I suspect driver issues linked to the very specific GPU bundled into MacBook Pro.

**Comment by unsoluble** [comment] 2022-12-05 17:15
`@dev7355608` noticed that one of these reports had an outdated Electron client, and the user in question claimed the issue fixed on reinstall. So unless that was a weird coincidence, this may not require further work. `@DemonWolf69` has been pinged as well; we'll see if it works for them too.

**Comment by Feu-Secret** [comment] 2022-12-05 17:43
Update: this issue is caused by old Electron client version. Updating the client is solving the problem.

**Closed by Feu-Secret** 2022-12-05 17:43 UTC
Labels: bug, lighting/fog, canvas, blocked
