### ISSUE TITLE
Add API extension point for configuring how Map Notes are drawn

### ISSUE THREAD

**Issue by cswendrowski** [foundryvtt/foundryvtt#8229] opened 2022-09-19 18:06 UTC
From https://discord.com/channels/170995199584108546/956306859491471420/1020475498213687359

Previously the icons had clear backdrops, now they seem to have grey backdrops.This is messing up my maps. Is there any way to control the way the map notes are displayed?
 
There doesn't seem to be.

It looks like canvas.objects.children[N].controlIcon.bg.alpha sets the alpha quality, which doesn't seem to be exposed?

I hacked this in Foundry itself which worked for me, but I can't believe I have to do this to edit the appearance of the map notes. I would like it if there were a better approach.

```js
/**
* Draw the ControlIcon for the Map Note
* @returns {ControlIcon}
* @protected
*/
_drawControlIcon() {
  let tint = Color.from(this.document.texture.tint || null);
  let icon = new ControlIcon({ texture: this.document.texture.src, size: this.size, tint });
  icon.bg.alpha = 0; // HACK
  icon.x -= (this.size / 2);
  icon.y -= (this.size / 2);
  return icon;
 }
}
```

API Request: Expose this option. It would also be nice to somewhat unify tokens, map tiles, and map notes graphically, so you could use a token or a tile graphic as a map note

**Comment by aaclayton** [comment] 2022-09-19 18:08
Duplicate of https://github.com/foundryvtt/foundryvtt/issues/8220

**Closed by aaclayton** 2022-09-19 18:08 UTC
Labels: api, canvas
