### ISSUE TITLE
Add button to Compendium app header to copy ID

### ISSUE THREAD

**Issue by JPMeehan** [foundryvtt/foundryvtt#10466] opened 2024-02-28 16:06 UTC
### User Experience

As a power user, grabbing the full ID of a Compendium can be obtuse. It would be easier if there were a header button similar to the one for Documents that grabbed the compendium's ID.

Possible extension: This *could* use the alternate left/right click controls that documents get, although I'm unsure what use *just* the `name` field would be useful for.

**Comment by krbz999** [comment] 2024-02-28 17:03
(Related: https://github.com/foundryvtt/foundryvtt/issues/9848)

**Comment by aaclayton** [comment] 2024-03-04 14:10
Closing as duplicate of https://github.com/foundryvtt/foundryvtt/issues/9848

**Closed** 2024-03-04 14:11 UTC
