### ISSUE TITLE
Regression: Unlinked tokens do not correctly inherit the default permission from their base actors

### ISSUE THREAD

**Issue by dev7355608** [foundryvtt/foundryvtt#11034] opened 2024-05-26 14:24 UTC
#9655. Probably caused by #10928.

**Comment by dylanpiera** [comment] 2024-05-27 16:00
Seems to be caused by the fact that `DocumentOwnershipField` extends `ObjectField` which was changed in #10928 to return `undefined` as it's initial value if `required: false`.

This however means that `ActorDelta#toObject` adds: `{ownership: undefined}` which was previously omitted.

This in turn causes the mergeObject call in `BaseActorDelta.applyDelta` to overwrite the DeltaActor's `ownership` field with `undefined`.

Which will then initialize back to `{default: 0}`.

**Comment by aaclayton** [comment] 2024-05-29 17:30
I am not able to reproduce this issue. Here is what I tried:

1. Verify Actor ownership
```js
a = game.actors.get("l2m5KKMq10zxUHBc");
console.log(a.ownership); // {default: 3, Smy99Z2Oa9gQ8IpV: 3, bPcIi1Q7SuXNUS01: 2}
```
2. Create an unlinked token from this actor
3. Verify unlinked Actor ownership
```js
console.log(token.actor.ownership); // {default: 3, Smy99Z2Oa9gQ8IpV: 3, bPcIi1Q7SuXNUS01: 2}
```
This is identical to the base actor.

4. Change ownership for the unlinked token specifically:
```js
token.actor.update({ownership: {default: 1}});
```
5. Verify that the overridden ownership has merged with base ownership:
```js
console.log(token.actor.ownership); // {default: 1, Smy99Z2Oa9gQ8IpV: 3, bPcIi1Q7SuXNUS01: 2}
```
Correct

**Comment by dev7355608** [comment] 2024-05-29 17:43
I checked again: I'm still able to reproduce it with the instructions given in #9655. Checking the unlinked tokens actor ownership always gives me `{default: 0}`.

**Comment by aaclayton** [comment] 2024-05-29 17:53
I have tried again, still no repro on my side

**Comment by dylanpiera** [comment] 2024-05-30 19:22
Just tested it and I can also still reproduce it.

```js
let actor = fromUuidSync('Actor.VTyTMFY6oksXdr4H');
console.log(actor.ownership, actor.prototypeToken.actorLink);

const token = await actor.getTokenDocument({}, {parent: canvas.scene});
console.log(token.actor.ownership, token.actorLink);

const canvasToken = await token.constructor.create(token, {parent: canvas.scene});
console.log(canvasToken.actor.ownership, canvasToken.actorLink);
```

![image](https://github.com/foundryvtt/foundryvtt/assets/2012848/f70e63fe-bfac-4c81-ba05-a46dcf42187b)

**Comment by aaclayton** [comment] 2024-05-30 19:25
@dylanpiera we just released a patch 12.325. Are you testing under that latest update? Or under 12.324?

**Comment by dylanpiera** [comment] 2024-05-30 19:27
Haven't updated yet, let me give that a shot.

**Comment by dylanpiera** [comment] 2024-05-30 19:30
![image](https://github.com/foundryvtt/foundryvtt/assets/2012848/5490fb99-46c4-48ad-98e5-bdb85977269e)

Seems that you managed to fix it during this update. Sneaky bugfix!

**Closed** 2024-05-30 19:32 UTC
Labels: bug, tokens

**Comment by dylanpiera** [comment] 2024-05-30 19:34
> This however means that ActorDelta#toObject adds: {ownership: undefined} which was previously omitted

![image](https://github.com/foundryvtt/foundryvtt/assets/2012848/1a75c014-d0f7-443d-a39f-234710d929f0)
Yup this got removed and thus fixed it.
