### ISSUE TITLE
Option to privately measure distances

### ISSUE THREAD

**Issue by ThiefMaster** [foundryvtt/foundryvtt#10464] opened 2024-02-27 19:48 UTC
### User Experience

This is something Roll20 has and I'm a bit surprised it's not a thing in Foundry:

**As a player I'd like to measure distances without other players or my DM seeing it.**

While generally a good DM will not do this type of metagaming, I think unconsciously there's still a good chance that they may act upon a likely action plan of the next character that's up in combat. For example, I'm measuring whether ✨*big kaboom spell*✨ has enough range to hit *big evil dude*. But I don't want to give him the idea that maybe moving a little bit away will keep him out of reach or require me to spend movement first (this is worse in systems like pf2e where having to take a movement action means I may not be able to use the most powerful 3-action spell). So I'd prefer to do the measurement privately.

**Comment by aaclayton** [comment] 2024-03-01 20:06
Closing as duplicate of #8675, merging your comment into that issue.

**Closed by aaclayton** 2024-03-01 20:06 UTC
