### ISSUE TITLE
Allow execution of Macros which are inside a Compendium pack

### ISSUE THREAD

**Issue by cswendrowski** [foundryvtt/foundryvtt#6823] opened 2022-03-10 22:54 UTC
Currently, Macros that are stored with at least the Limited permission can be executed straight from a Compendium.

We should consider if this is intended, and if so, more explicitly support it, else consider removing this unintended option

**Comment by aaclayton** [comment] 2022-06-12 18:16
Originally in GitLab by @SalieriC

Not sure if it's a bug or a feature.

### Feature Summary

When players have a link to a macro which is inside a compendium, allow them to execute it by clicking the link.

### User Experience

Macros in compendiums can be placed as links in all sorts of text fields (journal entries, descriptions, etc.) using @Compendium[ID]{Title}. This creates a clickable link that executes the macro. This however is not true for all permission levels as some cannot execute macros which are in a compendium. This is somewhat confusing as one would assume that anyone with access to an ID (can view the compendium) can execute a macro using a link.

**Comment by aaclayton** [comment] 2022-07-18 17:07
This is already working as intended. Closing as wontfix.

**Closed by aaclayton** 2022-07-18 17:07 UTC
Labels: ux, macros, compendium
