### ISSUE TITLE
Allow Sharing Data Usage pops every time the application is started

### ISSUE THREAD

**Issue by cswendrowski** [foundryvtt/foundryvtt#9324] opened 2023-05-01 15:00 UTC
https://discord.com/channels/170995199584108546/1065764070680186930/1101918800833679422

Simple steps to reproduce the bug:
- Restart Foundry
- Log into setup
- Allow Data Usage Sharing dialog pops

**Comment by aaclayton** [comment] 2023-05-01 16:15
@cswendrowski do you get this prompt every time? I certainly do not. The reproduction steps provided do not result in me being prompted multiple times. Likely if this was an issue it was fixed by https://github.com/foundryvtt/foundryvtt/issues/9105.

Marking as nonrepro.

**Comment by silvative** [comment] 2023-05-15 19:21
I also was unable to reproduce this behaviour, the popup did not appear for me even when disabling the data usage setting

**Closed by silvative** 2023-05-15 19:21 UTC
Labels: bug, nonrepro, ux
