### ISSUE TITLE
Cannot @Embed more than 6 documents into journal sheet

### ISSUE THREAD

**Issue by Greatshock** [foundryvtt/foundryvtt#11486] opened 2024-07-20 19:45 UTC
### What happened?

In the screenshot below I have 7 roll tables, when I try to embed all of them in 1 journal, only first 6 are getting embedded.

<img width="1666" alt="issue" src="https://github.com/user-attachments/assets/834746af-1fb8-4fe0-aeba-ed42aca36c9a">

I think it's somehow related to https://github.com/foundryvtt/foundryvtt/issues/11417

### What ways of accessing Foundry can you encounter this issue in?

- [X] Native App (Electron)
- [X] Chrome
- [X] Firefox
- [X] Safari
- [X] Other

### Reproduction Steps

1. Create roll table (or 7+ different tables)
2. Create journal
3. `@Embed` roll table in journal 7 or more times

### What core version are you reporting this for?

Version 12 Stable (build 239)

### Relevant log output

```shell
foundry.js:69845 Nested Document embedding is restricted to a maximum depth of 5. @Embed[RollTable.i36pHLwogStR3WAk] cannot be fully enriched.
_embedContent @ foundry.js:69845
_replaceTextContent.replaceParent @ foundry.js:69553
_replaceTextContent @ foundry.js:69717
await in _replaceTextContent (async)
_enrichEmbeds @ foundry.js:69553
enrichHTML @ foundry.js:69495
await in enrichHTML (async)
getData @ foundry.js:77772
_renderPageViews @ foundry.js:78624
_render @ foundry.js:78595
await in _render (async)
render @ foundry.js:5796
render @ foundry.js:10874
_onUpdateDescendantDocuments @ foundry.js:11242
_dispatchDescendantDocumentEvents @ foundry.js:11162
#handleUpdateDocuments @ foundry-esm.js:56568
await in #handleUpdateDocuments (async)
_updateDocuments @ foundry-esm.js:56446
await in _updateDocuments (async)
update @ foundry-esm.js:12328
await in update (async)
updateDocuments @ foundry-esm.js:11473
update @ foundry-esm.js:11583
_updateObject @ foundry.js:7343
_updateObject @ foundry.js:77833
_onSubmit @ foundry.js:6668
saveEditor @ foundry.js:6812
saveEditor @ foundry.js:77840
onSave @ foundry.js:6893
_handleSave @ foundry-esm.js:36912
_onAction @ foundry-esm.js:36881
button.onclick @ foundry-esm.js:36382
enrichers.mjs:412 Embed enrichers are restricted to 5 levels deep. @Embed[RollTable.i36pHLwogStR3WAk] cannot be enriched fully.
enrichEmbed @ enrichers.mjs:412
enrichString @ enrichers.mjs:62
_replaceTextContent.replaceParent.replaceParent @ foundry.js:69597
_replaceTextContent @ foundry.js:69717
_applyCustomEnrichers @ foundry.js:69597
enrichHTML @ foundry.js:69495
await in enrichHTML (async)
getData @ foundry.js:77772
_renderPageViews @ foundry.js:78624
_render @ foundry.js:78595
await in _render (async)
render @ foundry.js:5796
render @ foundry.js:10874
_onUpdateDescendantDocuments @ foundry.js:11242
_dispatchDescendantDocumentEvents @ foundry.js:11162
#handleUpdateDocuments @ foundry-esm.js:56568
await in #handleUpdateDocuments (async)
_updateDocuments @ foundry-esm.js:56446
await in _updateDocuments (async)
update @ foundry-esm.js:12328
await in update (async)
updateDocuments @ foundry-esm.js:11473
update @ foundry-esm.js:11583
_updateObject @ foundry.js:7343
_updateObject @ foundry.js:77833
_onSubmit @ foundry.js:6668
saveEditor @ foundry.js:6812
saveEditor @ foundry.js:77840
onSave @ foundry.js:6893
_handleSave @ foundry-esm.js:36912
_onAction @ foundry-esm.js:36881
button.onclick @ foundry-esm.js:36382
foundry.js:7848 Foundry VTT | Retrieved and compiled template templates/journal/parts/page-header.html
foundry.js:7848 Foundry VTT | Retrieved and compiled template templates/journal/parts/page-footer.html
```

### Bug Checklist

- [X] The issue occurs while all Modules are disabled

**Comment by Norc** [comment] 2024-07-20 23:46
Thanks for the report. I believe this is the same issue as #11479, which has already been addressed and will be included in the next release.  You are correct that this regression was likely caused by the fix for #11417.

Please feel free to re-open if you believe this is actually a separate issue.

**Closed by Norc** 2024-07-20 23:46 UTC
Labels: bug, duplicate, todelete
