### ISSUE TITLE
Ability to join a server from the desktop app.

### ISSUE THREAD

**Issue by Wizard-Level-1** [foundryvtt/foundryvtt#10644] opened 2024-04-14 14:45 UTC
### User Experience

One of the things I like about self hosting is that the app is it's own separate thing rather than being accessed through my browser. Since the app is chromium based, it seems that it could be possible to use it to connect to a server someone else is hosting. This would be a nice feature for those of us that have it installed. On certain hardware set up's it would offer a much better play experience.

**Comment by aaclayton** [comment] 2024-04-14 17:31
Closing as duplicate of #1981

**Closed by aaclayton** 2024-04-14 17:31 UTC
