### ISSUE TITLE
A system that fails validation appears as uninstalled in the install system dialog

### ISSUE THREAD

**Issue by Fyorl** [foundryvtt/foundryvtt#7679] opened 2022-07-29 12:09 UTC
Originally reported by BadIdeasBureau#7024 https://discord.com/channels/170995199584108546/956306859491471420/1002357280085393418

**ALL MODULES DISABLED?** N/A  
**OS, Hosting, Browser (if applicable):** Windows app  
**Short Description of bug:** If a system fails metadata validation, it appears as if it was uninstalled when searching in the "install system" dialog.  Suggest listing the failed systems/modules somewhere in setup screen with an "update" prompt instead.  
**Simple steps to reproduce the bug:** Have a system installed which fails validation in v10, search for that system in "install system".  
**Screenshots and/or console errors:**

![image](https://user-images.githubusercontent.com/207433/181755447-a44e888b-6301-4309-bf5b-cbac485faf83.png)

**Comment by theripper93** [comment] 2022-07-30 12:15
i think this is the same issue i reported here, so i guess this should be closed as wontfix as well https://github.com/foundryvtt/foundryvtt/issues/7690

**Comment by aaclayton** [comment] 2022-07-30 15:07
While this is not great for UX, it is working as intended.

**Closed by aaclayton** 2022-07-30 15:07 UTC
Labels: bug, ui, ux, packages
