### ISSUE TITLE
Token and AmbientLight config erases flags in preview if flags do not exist in the form

### ISSUE THREAD

**Issue by dev7355608** [foundryvtt/foundryvtt#8414] opened 2022-10-24 14:27 UTC
### What happened?

Because the source is now updated with `recursive: false`, passing a diff to `_previewChanges` erases other flags that haven't been changed if at least one flag was. `AmbientLightConfig#_resetPreview` is fine, but `TokenConfig#_resetPreview` is not. 
```diff
  // TokenConfig
  _resetPreview() {
-   const resetData = foundry.utils.diffObject(this.object.toObject(), this.original.toObject());
-   this._previewChanges(resetData);
+   this._previewChanges(this.object.toObject());
  }
```

There's also a similar issue that affects both configs. If at least one flag is injected into the config, all other flags that are not injected into the config are erased after the first `_onChangeInput` and are only restored when the config is saved or closed.

### What ways of accessing Foundry can you encounter this issue in?

- [ ] Native App (Electron)
- [ ] Chrome
- [ ] Firefox
- [ ] Safari
- [ ] Other

### Reproduction Steps

```js
Hooks.on("renderTokenConfig", sheet => {
    sheet.form
        .querySelector(`.tab[data-tab="light"] > .tab[data-tab="advanced"]`)
        .insertAdjacentHTML("beforeend", `\
            <div class="form-group slim">
                <label>Priority</label>
                <div class="form-fields">
                    <input type="number" name="flags.core.priority" value="${sheet.object.getFlag("core", "priority") ?? ""}">
                </div>
            </div>
            <div class="form-group slim">
                <label>Animation Seed</label>
                <div class="form-fields">
                    <input type="number" name="flags.core.animationSeed" value="${sheet.object.getFlag("core", "animationSeed") ?? ""}">
                </div>
            </div>`);
});
```

1. Open token config.
2. Set *Priority* to 1 and *Animation Seed* to 2.
3. Click *Update Token*
4. Reopen config:  *Priority* is 1 and *Animation Seed* is 2 as expected.
5. Change *Animation Seed* to 3.
6. Close config without saving.
7. Reopen config: *Animation Seed* is 2 as expected, but *Priority* is empty.

---
---

```js
Hooks.on("renderTokenConfig", sheet => {
    sheet.form
        .querySelector(`.tab[data-tab="light"] > .tab[data-tab="advanced"]`)
        .insertAdjacentHTML("beforeend", `\
            <div class="form-group slim">
                <label>Priority</label>
                <div class="form-fields">
                    <input type="number" name="flags.core.priority" value="${sheet.object.getFlag("core", "priority") ?? ""}">
                </div>
            </div>`);
});
```

1. `_token.document.setFlag("core", "priority", 1)` and  `_token.document.setFlag("core", "animationSeed", 2)`.
2. Open token config.
3.  `_token.document.getFlag("core", "priority")` is `1` and  `_token.document.getFlag("core", "animationSeed")` is `2`.
4. Change any input.
5.  `_token.document.getFlag("core", "priority")` is `1` and  `_token.document.getFlag("core", "animationSeed")` is `undefined`.

### What core version are you reporting this for?

Version 10 Stable 4 (build 288)

### Bug Checklist

- [X] The issue occurs while all Modules are disabled

**Comment by Fyorl** [comment] 2022-10-24 14:56
Mostly a duplicate of #8407 which should be fixed by the solution for #8393. I'm going to repurpose this issue to track this part:

> There's also a similar issue that affects both configs. If at least one flag is injected into the config, all other flags that are not injected into the config are erased after the first `_onChangeInput` and are only restored when the config is saved or closed.

Since that is not currently tracked.

**Closed** 2022-11-02 16:19 UTC
Labels: bug, lighting/fog, tokens, ui
