### ISSUE TITLE
Improve styling/layout of `HTMLMultiSelectElement` tags

### ISSUE THREAD

**Issue by dev7355608** [foundryvtt/foundryvtt#10733] opened 2024-04-24 13:18 UTC
![image](https://github.com/foundryvtt/foundryvtt/assets/31905376/8e71646e-2dc7-4d14-b90d-0492554b876c)

**Comment by aaclayton** [comment] 2024-04-29 16:46
Closing as duplicate of https://github.com/foundryvtt/foundryvtt/issues/10796

**Closed by aaclayton** 2024-04-29 16:46 UTC
Labels: ui
