### ISSUE TITLE
Browser back action is not suppressed when Foundry is the active tab

### ISSUE THREAD

**Issue by Fyorl** [foundryvtt/foundryvtt#9212] opened 2023-04-17 11:57 UTC
Originally reported by Plentimon#7350 https://discord.com/channels/170995199584108546/956306859491471420/1093742678442786866

**ALL MODULES DISABLED?** true  
**OS, Hosting, Browser (if applicable):** Windows 11, Self-hosted  
**Short Description of bug:** Back button attempts to exit and causes minor jam  
**Simple steps to reproduce the bug:**  
Small, but annoying, quality-of-life issue -- If I accidentally hit the back button on my mouse while editing an actor, I get a prompt that reads "Are you sure you want to exit the Foundry Virtual Tabletop game?" I then select cancel. It pauses my game and makes the character sheet un-editable unless I reboot the program or un-pause the game (just found this quick fix). Checked the hotkeys and did not see the Back Button on Mouse assigned to anything. Prefer to just have this action removed from the mouse.

**Comment by Fyorl** [comment] 2023-04-17 11:58
I wasn't able to reproduce this when I tested with the steps given. It might be specific to a particular system maybe? Either way, I thought we had code that swallowed events from mouse buttons 4 and 5, so that should be investigated.

**Comment by silvative** [comment] 2023-05-16 16:09
Unable to reproduce issue as described on 5e system in v11t3 with Firefox and Windows 10. 

>  Checked the hotkeys and did not see the Back Button on Mouse assigned to anything. Prefer to just have this action removed from the mouse.

Do note that the "back" button is something that you should rebind with your mouse's software (EG Logitech G hub). If it's bound to "back" (which I believe is the default) then it's not Foundry adding this functionality and you will notice it on any website you visit. That's why the popup prompt is not styled by Foundry- it originates from your browser. You can always unbind it at the OS level.

@Fyorl 

> Either way, I thought we had code that swallowed events from mouse buttons 4 and 5, so that should be investigated.

I can confirm that the back button prompt does appear (and not only in 5e, since I've experienced it in my own game too). What I can't confirm is that pressing it "freezes" Foundry- this may be an OS, browser, or system specific bug?

https://github.com/foundryvtt/foundryvtt/assets/66365038/8fcc498c-a697-4140-9c5d-8081ceb76f27

**Comment by aaclayton** [comment] 2023-05-24 12:40
Closed as nonrepro and working as intended.

**Closed by aaclayton** 2023-05-24 12:40 UTC
Labels: bug, ux
