### ISSUE TITLE
Jump To Pin results in a call to a non-existent method.

### ISSUE THREAD

**Issue by SethGallucci** [foundryvtt/foundryvtt#9883] opened 2023-08-03 10:56 UTC
### What happened?

```js
// class NotesLayer ...

panToNote(note, {scale=1.5, duration=250}={}) {
  if ( !note ) return Promise.resolve();
  if ( note.visible && !this.active ) this.activate();
  return canvas.animatePan({x: note.x, y: note.y, scale, duration}).then(() => {

    // _onMouseOut doesn't seem to exist in Note (this.hover); only in DoorControl.
    // I think this was meant to be _onHoverOut (from PlaceableObject).
    if ( this.hover ) this.hover._onMouseOut(new Event("pointerout"));

    note._onHoverIn(new Event("pointerover"), {hoverOutOthers: true});
  });
}
```

### What ways of accessing Foundry can you encounter this issue in?

- [X] Native App (Electron)
- [X] Chrome
- [ ] Firefox
- [ ] Safari
- [ ] Other

### Reproduction Steps

1. Create a Note that links to a JournalEntry or JournalEntryPage.
2. Use the *Jump To Pin* feature via the ContextMenu (right click) of the JournalEntry in the Journal Sidebar or directory item in the directory list of the JournalEntrySheet.
3. Perform step 2 again.

The first time `panToNote` is called, `this.hover` typically has a value of null, resulting in no error, as the if-conditional causes `_onMouseOut` to be bypassed. The second time `panToNote` is called, `this.hover` refers to the Note to which the view was previously panned, resulting in `_onMouseOut` being called.

### What core version are you reporting this for?

11.306

### Relevant log output

```shell
foundry.js:41471 Uncaught (in promise) TypeError: this.hover._onMouseOut is not a function
    at foundry.js:41471:36
(anonymous) @ foundry.js:41471
Promise.then (async)
panToNote @ foundry.js:41470
panToNote @ foundry.js:22594
callback @ foundry.js:86567
#onClickItem @ foundry.js:64765
dispatch @ jquery.min.js:2
y.handle @ jquery.min.js:2
```

### Bug Checklist

- [X] The issue occurs while all Modules are disabled

**Comment by Fyorl** [comment] 2023-08-03 11:08
Duplicate of #9869

**Closed by Fyorl** 2023-08-03 11:08 UTC
Labels: bug
