### ISSUE TITLE
the ability to multiple delete items on any of the menus

### ISSUE THREAD

**Issue by ThingsCouldGetDicey** [foundryvtt/foundryvtt#7428] opened 2022-07-03 18:22 UTC
> the issue i am having is that if i have more than one item that i need to delete i have to right click all the items i want and delete them individually. what id like is a lock button next to the sort button. which would be unlocked and show a column of selection that i could tick for deletion/ duplication or for moving to a folder. 
### User Experience

> the ideal user experience would be if you could have a lock button that you could unlock next to the sort button which you could click which would open up a new column with boxes next to the items within the actor/journal/scenes etc tabs that would enable you the ability to multiple select items for the purposes of deletion/duplications or moving. 

### Priority/Importance

> not high but low it would help with ui and organisation of things active in foundry.

**Comment by aaclayton** [comment] 2022-07-04 12:20
Could you explain what you mean precisely by "on any of the menus", are you talking about items in the sidebar directories?

**Comment by ThingsCouldGetDicey** [comment] 2022-07-04 12:38
![image](https://user-images.githubusercontent.com/62528192/177155858-9eebcc81-1728-4464-b3a0-16e95ce45732.png)
 so what i mean is that if you see the first smaller box you could click an unlock button similar to the tidy 5e sheet module in this image.:
 
![image](https://user-images.githubusercontent.com/62528192/177156314-1c1d3511-0fcb-4319-ad86-73b361edadd9.png)

the longer bars i made in the first image would be for that extra column which would enable the selection of multiple items. to copy/ delete or move to another folder. allowing multiple selection. sometimes by mistake i may import something too much and i have to delete duplicates or alot of folders currently i cant select multiples to speed up that process. i have to right click delete every single one.

**Comment by aaclayton** [comment] 2022-07-04 12:41
Closing as duplicate of #3579 and merging this there.

**Closed by aaclayton** 2022-07-04 12:41 UTC
Labels: ux
