### ISSUE TITLE
ToS page renders in a broken state

### ISSUE THREAD

**Issue by cswendrowski** [foundryvtt/foundryvtt#9081] opened 2023-03-20 15:40 UTC
hitting accept or decline doesn't do anything. The license only appears in text format
Simple steps to reproduce the bug: Fresh install of v10.291, then update to the prototype.
Screenshots and/or console errors: No console errors, hitting cancel bypasses it, however, the main page with the world/game/module select looks in text format only. 

![](https://media.discordapp.net/attachments/1065764070680186930/1086748923969945711/image.png?width=964&height=522)
![](https://media.discordapp.net/attachments/1065764070680186930/1086748924183847062/image.png?width=617&height=458)

**Comment by aaclayton** [comment] 2023-04-07 19:02
This looks like a caching issue, not able to reproduce this issue in any way nor have I seen other reports of it. Closing as nonrepro.

**Closed by aaclayton** 2023-04-07 19:02 UTC
Labels: bug, authentication
