### ISSUE TITLE
FilePicker S3 buckets still have upload failure. 

### ISSUE THREAD

**Issue by AyoOgunsola** [foundryvtt/foundryvtt#11298] opened 2024-06-29 19:41 UTC
### What happened?

Uploading files to s3 buckets still throws file upload failed: The specified bucket does not exist: 0. 
Related issue: https://github.com/foundryvtt/foundryvtt/issues/11218

### What ways of accessing Foundry can you encounter this issue in?

- [ ] Native App (Electron)
- [ ] Chrome
- [X] Firefox
- [ ] Safari
- [X] Other

### Reproduction Steps

1. Open File Picker
2. Select S3 bucket
3. Attempt to upload a file.

### What core version are you reporting this for?

Version 12 Build 328

### Relevant log output

```shell
File upload failed: The specified bucket does not exist: 0 foundry.js:71791:78
    fetch https://cloudfoundry.nickoblack.xyz/scripts/foundry.js:71791
    notify https://cloudfoundry.nickoblack.xyz/scripts/foundry.js:71687
    error https://cloudfoundry.nickoblack.xyz/scripts/foundry.js:71724
    upload https://cloudfoundry.nickoblack.xyz/scripts/foundry.js:70628
    #onUpload https://cloudfoundry.nickoblack.xyz/scripts/foundry.js:71073
    onchange https://cloudfoundry.nickoblack.xyz/scripts/foundry.js:70735
    (Async: EventHandlerNonNull)
    activateListeners https://cloudfoundry.nickoblack.xyz/scripts/foundry.js:70735
    _render https://cloudfoundry.nickoblack.xyz/scripts/foundry.js:5842
    render https://cloudfoundry.nickoblack.xyz/scripts/foundry.js:5768
    render https://cloudfoundry.nickoblack.xyz/scripts/foundry.js:70700
    browse https://cloudfoundry.nickoblack.xyz/scripts/foundry.js:70528
    #onPick https://cloudfoundry.nickoblack.xyz/scripts/foundry.js:70930
    jQuery 8
    activateListeners https://cloudfoundry.nickoblack.xyz/scripts/foundry.js:70738
    _render https://cloudfoundry.nickoblack.xyz/scripts/foundry.js:5842
    render https://cloudfoundry.nickoblack.xyz/scripts/foundry.js:5768
    render https://cloudfoundry.nickoblack.xyz/scripts/foundry.js:70700
    browse https://cloudfoundry.nickoblack.xyz/scripts/foundry.js:70528
    #onPick https://cloudfoundry.nickoblack.xyz/scripts/foundry.js:70930
    jQuery 8
    activateListeners https://cloudfoundry.nickoblack.xyz/scripts/foundry.js:70738
    _render https://cloudfoundry.nickoblack.xyz/scripts/foundry.js:5842
    render https://cloudfoundry.nickoblack.xyz/scripts/foundry.js:5768
    render https://cloudfoundry.nickoblack.xyz/scripts/foundry.js:70700
    browse https://cloudfoundry.nickoblack.xyz/scripts/foundry.js:70528
```

### Bug Checklist

- [X] The issue occurs while all Modules are disabled

**Comment by aaclayton** [comment] 2024-06-30 13:21
Hmm... you are certain you are using the latest 12.328 release? We did address this problem and make a change that should have fixed this error. Perhaps you are experiencing an unrelated issue. S3 uploading was working fine in my own testing though.

**Comment by AyoOgunsola** [comment] 2024-06-30 14:42
Double checked my install and I'm on 328. Using a v11 install I have, the upload works fine there. Someone else on discord mentioned having issues with uploading this current patch as well which is why i posted the issue. I am using a backblaze b2 instead of an Amazon s3 directly though so may be more related to that.

I saw in the patch notes that the issue was only noted to occur with the filepicker. This is true for me as well, since the mounlinette module has been configured to upload to the bucket and has no problems doing so on the latest patch.

**Comment by AyoOgunsola** [comment] 2024-06-30 14:43
I didn't mean to close this issue lol, miss clicked on my phone.

**Comment by TShapinsky** [comment] 2024-06-30 21:14
@aaclayton I'd like to confirm that this is still an issue.

I still have to change the line in `#onUpload` to
```javascript
const options = { bucket: form.bucket ? game.data.files.s3.buckets[form.bucket.value] : null };
```
for S3 upload to work. If that was the fix it looks like it didn't make it into 12.328

**Comment by BigReidy** [comment] 2024-06-30 22:28
I'll throw my hat into the ring.
My docker container had the same issue, and I've applied the fix manually.
![image](https://github.com/foundryvtt/foundryvtt/assets/20508383/62b3fd7f-47c8-4f66-b442-9245db27eb25)

**Comment by strongpauly** [comment] 2024-07-03 20:46
I've just seen an issue with this on my server.  I'm using v12 Build 328 and node version `v22.3.0`.  I saw this error in the logs:
```
Are you using a Stream of unknown length as the Body of a PutObject request? Consider using Upload instead from @aws-sdk/lib-storage.
```

**Comment by LavCorps** [comment] 2024-07-04 17:58
Reproduced on Node `v18.19.0`, Foundry 12 Build 328 on Chromium (Vivaldi). Looking at server logs reveals the cause is still the same as that of #11218 and #11126

**Comment by dprothero** [comment] 2024-07-04 22:03
> @aaclayton I'd like to confirm that this is still an issue.
> 
> I still have to change the line in `#onUpload` to
> 
> ```js
> const options = { bucket: form.bucket ? game.data.files.s3.buckets[form.bucket.value] : null };
> ```
> 
> for S3 upload to work. If that was the fix it looks like it didn't make it into 12.328

Where is the file you make this change?

**Comment by dev7355608** [comment] 2024-07-09 18:45
Originally reported by andysaysgrr: https://discord.com/channels/170995199584108546/1184176415139184731/1256172785689038889

**ALL MODULES DISABLED?** TRUE
**OS, Hosting, Browser (if applicable)**: Mac OS Sonoma 14.5, Foundry App
**Short Description of bug**: Unable to upload files to AWS bucket now, was working previously in V11. Error says "The specified bucket is not valid." I saw this issue on Github and its marked as closed, but this error is still persisting for me following this mornings update to Version 12 Stable - Build 328.
**Simple steps to reproduce the bug**: Select a file to upload to your AWS bucket
**Screenshots and/or console errors**:

**Closed** 2024-07-10 14:10 UTC
Labels: bug, nonrepro

**Comment by dprothero** [comment] 2024-07-10 18:36
Why was this closed? It's still an issue.

**Comment by unsoluble** [comment] 2024-07-10 18:40
![IMG_4199](https://github.com/foundryvtt/foundryvtt/assets/801582/e2704821-49e9-4119-a768-f90d2ce677e0)
