### ISSUE TITLE
Migration of packs to V11 uses wrong name

### ISSUE THREAD

**Issue by farling42** [foundryvtt/foundryvtt#9594] opened 2023-06-11 09:10 UTC
### What happened?

I have a shared compendium module in V10 which contains some packs where the .name of the db file does not match the name of the pack.

During migration to V11 a DB is created using the name of the db file, but then when the world starts another db is created with the name of the pack. This second db is the one that is visible in Foundry, and is (of course) empty.

A manual rename of the actual db directory to the pack's name is required in order to get the pack to appear again.

The migration should use the contents of the named db file to create a new DB using the pack's name (not its filename).

### What ways of accessing Foundry can you encounter this issue in?

- [X] Native App (Electron)
- [X] Chrome
- [ ] Firefox
- [ ] Safari
- [ ] Other

### Reproduction Steps

Create a pack in a V10 module with a filename for the db file which is different to the pack name.
Start V11 and enable the module.
Observe that two DBs are created, one with the db's filename and one with the pack's name.

### What core version are you reporting this for?

11.300

### Bug Checklist

- [X] The issue occurs while all Modules are disabled

**Comment by aaclayton** [comment] 2023-06-11 16:24
Hey @farling42 just so we can reproduce exactly what you're seeing, could you attach the `module.json` manifest for your module to this issue?

**Comment by farling42** [comment] 2023-06-11 21:02
In the following, look for the pack called `actors-cts` - although there are others with mismatches as well.
[module.json.txt](https://github.com/foundryvtt/foundryvtt/files/11715718/module.json.txt)

**Comment by Fyorl** [comment] 2023-06-13 16:24
I wasn't able to reproduce this on 301 or 300, though I did find an (unrelated) bug: #9616 

> The migration should use the contents of the named db file to create a new DB using the pack's name (not its filename).

This is not correct though. The migration should (and does) create a LevelDB folder with the same name as the `path` field, but with the `.db` extension stripped. It does not use the pack's `name`. I can see why that appears to be the solution, given the bug, but I wasn't able to reproduce foundry creating two directories: one with the `path` and one with the `name`, it only (correctly) produced the directory pointed to by `path`.

**Comment by Fyorl** [comment] 2023-06-13 17:38
> When I started the world with the module compendium, it seemed to create a db using the name, possibly on a restart - since the path isn't used after the migration has been performed?

The `path` is still used after the migration has been performed. I guess with what you're observing with your bug, it seems like it's not, but in the normal functioning of the software, the `path` is still used and is important.

> I will need to do another test to see when the "pack"-named db is created.

It might be because I didn't have any actual NeDB packs to migrate, but I did also try to reproduce it with the Cypher system itself which also has some mismatched `path`s and `name`s, and does use NeDB packs, but I wasn't able to reproduce it there either. If you are able to narrow it down more it would be very helpful.

**Comment by farling42** [comment] 2023-06-13 21:18
I just tried with my last V10 backup and using 11.300 and I couldn't repeat the problem.

I know at some point that I went in to remove the .db files, and I also removed all the "path" lines from module.json, since I'd read that that line is no longer required. But removing the "path" line means that a new DB would be created since the folder based on the "pack" name doesn't exist.

**Comment by Fyorl** [comment] 2023-06-15 13:15
Tentatively marking this as closed then for now.

**Closed by Fyorl** 2023-06-15 13:15 UTC
Labels: bug, nonrepro, packages, data architecture
