### ISSUE TITLE
Line of sight not working as expected

### ISSUE THREAD

**Issue by cswendrowski** [foundryvtt/foundryvtt#8182] opened 2022-09-12 16:01 UTC
From https://discord.com/channels/170995199584108546/956306859491471420/1018328869679398912

A wall (highlighted in the image attached) somehow causes line of sight to break in unexpected ways within certain areas of the map (the top-right, in particular). Tokens are unable to see areas for no apparent reason, in spite of being a long way from the wall in question.
Simple steps to reproduce the bug: I have not been able to recreate the bug - even deleting then replacing the wall in the same location resolves the issue.

![image](https://user-images.githubusercontent.com/2468703/189716006-ebc66c66-8445-41cb-8629-6daaf109b246.png)

## Dev Note
Linked Discord message has a scene json export for testing

**Comment by Feu-Secret** [comment] 2022-09-19 18:29
Not able to reproduce this issue with the provided map. Everything is working fine.

**Comment by Feu-Secret** [comment] 2022-09-19 18:33
@aaclayton I think this issue is related to 8097, which was fixed in the v10 stable 2:
- https://github.com/foundryvtt/foundryvtt/issues/8097

**Closed by Feu-Secret** 2022-09-19 18:33 UTC
Labels: bug, nonrepro, walls, vision
