### ISSUE TITLE
Moving token using arrow keys causing jerky movement

### ISSUE THREAD

**Issue by caewok** [foundryvtt/foundryvtt#7321] opened 2022-06-16 20:44 UTC
### Environment Details
* Foundry VTT Version: 10.270
* Operating System: macOS 12.4
* How Are You Using Foundry: Nodejs running locally on the computer; Chrome 102.0.5005.115 (arm64)
* Which Game System: dnd5e 1.6.2
* Modules Enabled?: no

### Issue Description

Holding down the arrow keys to move a token, the token movement is very jerky (as if it were pausing after each grid step) when moving south or east. There is a bit of a pause when moving north or west, but the motion then gets smoother. 

If you drag the token and drop it to cause it to move, it also is not smooth and sometimes looks like the token is skipping a step.

In this video, I push the arrow key once and hold it to cause the token to move in the given direction. Please let me know if other tests would be helpful.

https://user-images.githubusercontent.com/1267134/174160306-c4aef797-b064-4746-87b5-e05bb6c26453.mov

**Comment by aaclayton** [comment] 2024-05-20 21:15
Closing as duplicate of https://github.com/foundryvtt/foundryvtt/issues/10790

**Closed by aaclayton** 2024-05-20 21:15 UTC
Labels: bug
