### ISSUE TITLE
Many modules fail to install due to `active` being `null`

### ISSUE THREAD

**Issue by mattexdee** [foundryvtt/foundryvtt#7308] opened 2022-06-14 18:55 UTC
Originally posted by Clemente: https://discord.com/channels/170995199584108546/956306859491471420/985645134534283314

**ALL MODULES DISABLED?** N/A
**OS, Hosting, Browser (if applicable):** Windows, Electron
**Short Description of bug:** Some modules fail to be installed (and don't show up even when installed manually)
**Simple steps to reproduce the bug:**
1) On Setup, try to install the Health Estimate module (or many other modules).
2) It'll throw TypeError: Cannot destructure property 'active' of 'data' as it is null.
Notes:
- The module does install normally on V9.
- For some reason, its data.pkg is null and is making the module to not be installed (even though its files are being unzipped properly on its folder, healthEstimate)
- Might be another bug altogether, but the module also doesn't show up on the Manage Modules list inside a world (no errors, it just isn't listed on game.modules).
**Screenshots and/or console errors:**
```js
Uncaught (in promise) TypeError: Cannot destructure property 'active' of 'data' as it is null.
    at new Module (foundry.js:2349)
    at done (setup.js:277)
    at progress (setup.js:298)
    at setup.js:451
    at Array.forEach (<anonymous>)
    at i._onProgress (setup.js:451)
    at i.x.emit (index.mjs:136)
    at i.value (socket.js:278)
    at i.value (socket.js:265)
    at i.value (socket.js:235)
```

I was able to replicate the the failed installation issue with a number of modules as well. I believe they're not showing the manage modules list because they're not V10 compatible though.

**Comment by aaclayton** [comment] 2022-06-15 20:48
I believe that the issue with `active` state is fixed, but I did encounter a different issue with the `healthEstimate` module specifically.

It declares one of its `scripts` as `"./lib/color-picker.min.js",` which is a file that does not exist in the module. Our more strict validation throws an error because of this and does not acknowledge the module as being valid as a result.

**Comment by aaclayton** [comment] 2022-06-15 20:51
Closing as nonrepro/todelete.

**Comment by arcanistzed** [comment] 2022-07-16 03:10
I think that this should be made clear on the client with a more descriptive error message. Currently, the only indication of the issue is in the server logs which means that it's a very confusing user experience.

**Comment by aaclayton** [comment] 2022-07-16 15:41
We should be able to tackle this as part of https://github.com/foundryvtt/foundryvtt/issues/6727

**Closed by aaclayton** 2022-07-16 15:41 UTC
Labels: bug, nonrepro, todelete, packages
