### ISSUE TITLE
WEBM Animation alpha/transparency issue :  "overshadowing" effect or black matte on semi transparent areas

### ISSUE THREAD

**Issue by thewaenderer** [foundryvtt/foundryvtt#8848] opened 2023-02-03 18:06 UTC
### What happened?

WEBM animated asset with transparency/alpha (Straight not Premultiplied) looks wrong in Foundry VTT. The semi transparent areas have a black matte behind them (much like if the file's Alpha channel was Premultiplied).
<img width="451" alt="image" src="https://user-images.githubusercontent.com/124388713/216674985-a0a39c32-18ab-4197-bd79-729f1c8b742c.png">

_PS :  The module Sequencer offers a workaround in its settings named "Enable Global PIXI fix". It works but not for every users and not everytime._

### What ways of accessing Foundry can you encounter this issue in?

- [X] Native App (Electron)
- [X] Chrome
- [X] Firefox
- [X] Safari
- [ ] Other

### Reproduction Steps

1. Upload a webm file with Straight Alpha channel as a tile.
2. Place it on your map.
3. See the black matte in semi transparent areas of the animation.

### What core version are you reporting this for?

Version 10 (Building 291)

### Bug Checklist

- [X] The issue occurs while all Modules are disabled

**Comment by aaclayton** [comment] 2023-02-05 01:51
I think Stryxin from Forgotten Adventures has called out this issue in the past as well. It's worth @Feu-Secret looking into this to see if there is something we can improve on our end, or surface as an upstream bug to PIXI.

**Comment by Feu-Secret** [comment] 2023-02-05 13:12
@thewaenderer By taking a look at the screenshot, it seems that the RGB components are premultiplied twice. Could you send us the asset to test it?
@aaclayton This issue is also a duplicate of https://github.com/foundryvtt/foundryvtt/issues/5954

**Comment by thewaenderer** [comment] 2023-02-06 10:31
Hi @Feu-Secret and @aaclayton, thank you for your quick reply.

Here are the files I'm using to make my tests : https://drive.google.com/drive/folders/1k62dnnMZ5IlQb0YZ9mFOYhAPPkOOFQ2D?usp=share_link
You'll find : 
- the 2 source files in .mov, GOPROCINEFORM and ANIMATION using Straight Alpha (to verify the Alpha) 
- 2 .webm files from the converter Shutter Encoder in VP9 and VP8
- 2 .webm files from the converter Adobe Media Encoder in VP9 and VP8

Sorry for the double post, I tried to find a previous report about this issue but failed to do so.

**Comment by Haxxer** [comment] 2023-02-08 18:36
The fix I offer in Sequencer only works for some users, which seems to allude to some form of software and/or hardware difference that causes this. In fact, enabling my fix for users that does not experience the bug causes the webm to overblow its channels.

**Closed** 2023-02-17 23:24 UTC
Labels: bug, canvas, blocked

**Comment by thewaenderer** [comment] 2023-02-18 12:43
Hi @Feu-Secret , I've tested Version 11 Build 292 and the bug remains. Will it be solved on a next build?

**Comment by aaclayton** [comment] 2023-02-18 14:51
> Hi @Feu-Secret , I've tested Version 11 Build 292 and the bug remains. Will it be solved on a next build?

These changes have been completed for our upcoming V11 prototype 2 release that is expected early next week. Please give it a try once that new release is available!
