### ISSUE TITLE
S3 path-style uploads broken

### ISSUE THREAD

**Issue by LavCorps** [foundryvtt/foundryvtt#11126] opened 2024-06-04 07:12 UTC
### What happened?

Hello, this is a follow-up from two messages on the FoundryVTT Discord, [here](https://discord.com/channels/170995199584108546/486930822465716249/1246662449667641376) and [here](https://discord.com/channels/170995199584108546/1184176344276406292/1246955908106293328). For clarity's sake, I will also reiterate noteworthy facts here.

When attempting to upload a file via the Foundry file manager interface, an "Access Denied" error will be returned.

* Issue noted to occur on Foundry 12 Build 325 on Chromium (Vivaldi) and Firefox, under system Pathfinder Second Edition 6.0.0-beta2.
* Issue occurs even when all modules are disabled.
* S3 server used is self-hosted SeaweedFS 3.67.
* Verified to work without issue on Chromium (Vivaldi) and Firefox on Foundry 11 Build 315.
* Credentials confirmed to be correct.
* This issue is noteworthy in that while Foundry will send requests to the appropriate bucket for path-style requests for file listing, put requests for uploading files will not have the bucket name filled in appropriately, instead replaced with `0`.

### What ways of accessing Foundry can you encounter this issue in?

- [ ] Native App (Electron)
- [X] Chrome
- [X] Firefox
- [ ] Safari
- [ ] Other

### Reproduction Steps

1. Setup S3 connection with path-style buckets.
2. Enable credentials used to upload and list files.
3. Upload file using Foundry 12 Build 325

### What core version are you reporting this for?

Version 12 Stable Build 325

### Relevant log output

Web console:
```js
foundry.js:71220 File upload failed: Access Denied.
fetch @ foundry.js:71220
notify @ foundry.js:71116
error @ foundry.js:71153
upload @ foundry.js:70057
await in upload (async)
_onDrop @ foundry.js:70274
callback @ foundry.js:68463
_handleDrop @ foundry.js:68514
```
Apache2 logs:
```
10.0.0.1 - - [04/Jun/2024:11:44:15 -0600] "GET /foundry/?delimiter=%2F&list-type=2&max-keys=1000&prefix= HTTP/1.1" 200 705 "-" "aws-sdk-js/3.577.0 ua/2.0 os/linux#6.6.13+bpo-amd64 lang/js md/nodejs#18.19.0 api/s3#3.577.0"
10.0.0.1 - - [04/Jun/2024:11:44:20 -0600] "PUT /0/test.png?x-id=PutObject HTTP/1.1" 403 826 "-" "aws-sdk-js/3.577.0 ua/2.0 os/linux#6.6.13+bpo-amd64 lang/js md/nodejs#18.19.0 api/s3#3.577.0"
10.0.0.1 - - [04/Jun/2024:11:44:20 -0600] "POST /foundry/upload HTTP/1.1" 200 832 "https://lavcorps.xyz/foundry/game" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/124.0.0.0 Safari/537.36"
10.0.0.1 - - [04/Jun/2024:11:44:21 -0600] "GET /foundry/?delimiter=%2F&list-type=2&max-keys=1000&prefix= HTTP/1.1" 200 1030 "-" "aws-sdk-js/3.577.0 ua/2.0 os/linux#6.6.13+bpo-amd64 lang/js md/nodejs#18.19.0 api/s3#3.577.0"
```

### Bug Checklist

- [X] The issue occurs while all Modules are disabled

**Comment by LavCorps** [comment] 2024-06-08 21:09
Confirmed to still occur on Foundry 12 Build 327 on Chromium (Vivaldi) under system Pathfinder Second Edition 6.0.0-beta3.

**Comment by ctbritt** [comment] 2024-06-09 12:32
confirming same issue in 12.327 in Chromium (Arc) and DnD53 3.2

**Comment by Zloklun** [comment] 2024-06-14 16:35
Same issue on 12.325 and 12.327

Seems like a bug in some frontend HTML templates to me. Foundry always tries to `PUT` to a bucket by its index in dropdown list instead of bucket name: try to create several buckets, upload some files to them, and watch webserver logs

**Comment by aaclayton** [comment] 2024-06-27 13:15
Closing as duplicate of https://github.com/foundryvtt/foundryvtt/issues/11218

**Closed by aaclayton** 2024-06-27 13:15 UTC
Labels: bug
