### ISSUE TITLE
Move the Dynamic Token Ring settings to a new tab

### ISSUE THREAD

**Issue by ddbrown30** [foundryvtt/foundryvtt#11636] opened 2024-08-31 22:48 UTC
### User Experience

With the addition of the Dynamic Token Ring settings on the Appearance tab, there is now too much on that tab. The dialog fills the whole screen and still requires a scroll bar. It would be great if we could get the settings split out into a new tab so we can return to a smaller dialog again.

**Comment by stwlam** [comment] 2024-09-01 00:45
Closing as duplicate of #11434

**Closed by stwlam** 2024-09-01 00:45 UTC
Labels: duplicate, todelete
