### ISSUE TITLE
Add a "user" scope to game settings

### ISSUE THREAD

**Issue by theripper93** [foundryvtt/foundryvtt#7737] opened 2022-08-03 12:30 UTC
### User Experience

Currently we have world and client settings. While client settings are great for things like performance options, most module seettings would be best stored on a per user basis, so that clearing the cookies or switching IP will not purge those settings.

The current workaround is to setFlag() on the user document but it would be more convinient and consistent to have a dedicated user scope.

**Comment by aaclayton** [comment] 2022-08-03 13:10
Duplicate of #4804

**Closed by aaclayton** 2022-08-03 13:10 UTC
