### ISSUE TITLE
Signal handling for SIGTERM no longer works with NodeJS 20

### ISSUE THREAD

**Issue by jacobsteffler** [foundryvtt/foundryvtt#9473] opened 2023-05-25 17:00 UTC
### What happened?

When running Foundry with NodeJS v20, the server can no longer be safely stopped by sending SIGTERM.
The following error is emitted:

```
FoundryVTT | 2023-05-25 11:33:26 | [error] The "code" argument must be of type number. Received type string ('SIGTERM')
TypeError [ERR_INVALID_ARG_TYPE]: The "code" argument must be of type number. Received type string ('SIGTERM')
    at process.set [as exitCode] (node:internal/bootstrap/node:124:9)
    at exit (node:internal/process/per_thread:188:24)
    at Object.onceWrapper (node:events:626:26)
    at process.emit (node:events:523:35)
```

In NodeJS v19, this deprecation warning was shown:
`[DEP0164] DeprecationWarning: Implicit coercion to integer for exit code is deprecated.`

This can be solved by using an earlier version of Node as recommended on the website. (LTS Hydrogen, which is v18, works.)
Still, this will need to be resolved before Foundry can support newer versions of Node.

### What ways of accessing Foundry can you encounter this issue in?

- [ ] Native App (Electron)
- [ ] Chrome
- [ ] Firefox
- [ ] Safari
- [x] Other

### Reproduction Steps

Run the standalone version of Foundry with NodeJS 20. Attempt to kill the server by sending SIGTERM.
SIGTERM is how systemd (and probably other init systems) attempt to stop services by default.

I can provide more information about my system if needed, but this issue seems pretty straightforward.

### What core version are you reporting this for?

10.291

### Bug Checklist

- [X] The issue occurs while all Modules are disabled

**Comment by Fyorl** [comment] 2023-05-25 17:03
Duplicate of #9373, already fixed in v11.

**Closed by Fyorl** 2023-05-25 17:03 UTC
Labels: bug

**Comment by jacobsteffler** [comment] 2023-05-25 17:13
Oops sorry, I checked for a duplicate but only searched the word "SIGTERM". Thanks!
