### ISSUE TITLE
Prompt for backup when installing new version of Foundry

### ISSUE THREAD

**Issue by bithir** [foundryvtt/foundryvtt#8072] opened 2022-09-03 12:07 UTC
### User Experience

In order to save sanity on people (module, system and foundry support staff) - I would like to suggest when installing a new version of Foundry, that if there exist data in the default data-path, to either automatically take a backup (preferred), or prompt the user to make a manual backup (people will not read such a prompt).

**Comment by aaclayton** [comment] 2022-09-03 14:02
Closing as duplicate of #2912

**Closed by aaclayton** 2022-09-03 14:02 UTC
