### ISSUE TITLE
Add option/ button to apply the "Configure Ownership" setting for all items within a folder to what they are for the folder

### ISSUE THREAD

**Issue by itteerde** [foundryvtt/foundryvtt#8457] opened 2022-11-01 12:59 UTC
### User Experience

When making a folder for a user (or worse group of users) and adding items to the folder it seems one has to edit the access for every item. There should be a right-click option on the folder like "Apply Ownership to Contents".

**Comment by aaclayton** [comment] 2022-11-01 13:42
Duplicate of #3807, moving this over there.

**Closed by aaclayton** 2022-11-01 13:42 UTC
