### ISSUE TITLE
Using the "Transition To Daylight/Darkness" button logs a deprecation warning

### ISSUE THREAD

**Issue by dev7355608** [foundryvtt/foundryvtt#10701] opened 2024-04-22 12:44 UTC
Originally reported by huepfklotz: https://discord.com/channels/170995199584108546/1184176415139184731/1231218588375973909

**ALL MODULES DISABLED?** (true/false)
**OS, Hosting, Browser (if applicable)**: -
**Short Description of bug**: Darkness animation throws deprecation warning
**Simple steps to reproduce the bug**: Use day cycle buttons in toolbar on the left, observe console
**Screenshots and/or console errors**:

```
foundry-esm.js:4565 Error: You are accessing Scene#darkness which has been migrated to Scene#environment.darknessLevel
Deprecated since Version 12
Backwards-compatible support will be removed in Version 14
    at logCompatibilityWarning (foundry-esm.js:4553:19)
    at Scene._logDataFieldMigration (foundry-esm.js:11931:14)
    at Object.get (foundry-esm.js:11892:21)
    at Scene._onUpdate (foundry.js:21459:55)
    at foundry-esm.js:56200:15
    at foundry-esm.js:56206:43
    at Array.map (<anonymous>)
    at #handleUpdateDocuments (foundry-esm.js:56206:33)
```

**Comment by aaclayton** [comment] 2024-05-13 17:18
Assigning to @Feu-Secret

**Comment by Feu-Secret** [comment] 2024-05-16 19:01
Already fixed. Duplicate of https://github.com/foundryvtt/foundryvtt/issues/10807

**Closed by Feu-Secret** 2024-05-16 19:01 UTC
Labels: bug, duplicate, todelete, scenes
