### ISSUE TITLE
Get the error `Error: Cannot find module '@node-rs/crc32-darwin-arm64'` when launching from the command line.

### ISSUE THREAD

**Issue by Feu-Secret** [foundryvtt/foundryvtt#10289] opened 2023-12-18 11:01 UTC
### What happened?

Reported here: https://discord.com/channels/170995199584108546/1184176415139184731/1184273085491322980

Get the error `Error: Cannot find module '@node-rs/crc32-darwin-arm64'` when launching from the command line.

### What ways of accessing Foundry can you encounter this issue in?

- [ ] Native App (Electron)
- [ ] Chrome
- [X] Firefox
- [ ] Safari
- [ ] Other

### Reproduction Steps

Install node module, run using command `node /path/to/foundry/resources/app/main.js --dataPath=/path/to/foundrydata`

![image](https://github.com/foundryvtt/foundryvtt/assets/66535080/be0cc45f-9955-4f90-863d-1af81f1eea07)

### What core version are you reporting this for?

Version 12 P1 316

### Bug Checklist

- [X] The issue occurs while all Modules are disabled

**Comment by ChunkLightTuna** [comment] 2024-02-05 00:30
on a x64 mac, running `npm i` from <FOUNDRY_DIR>/resources/app fixes this. Foundry's build script should also target x86_64-apple-darwin.

**Comment by aaclayton** [comment] 2024-02-05 18:31
Closing as duplicate of https://github.com/foundryvtt/foundryvtt/issues/10288

**Closed by aaclayton** 2024-02-05 18:31 UTC
Labels: bug, electron
