### ISSUE TITLE
Cannot create new Compendium with Core translation enabled

### ISSUE THREAD

**Issue by phenomen** [foundryvtt/foundryvtt#8117] opened 2022-09-06 19:08 UTC
### What happened?

When any Core translation is enabled, it's impossible to create a new Compendium of any type.

![Foundry_Virtual_Tabletop_GHqm1St6Jo](https://user-images.githubusercontent.com/138311/188718465-b880d40e-c56b-4ea0-8c8e-c8339f8dfd06.png)

![image](https://user-images.githubusercontent.com/138311/188718404-23c4de04-c4ed-42b3-931d-8929473ae338.png)

### What ways of accessing Foundry can you encounter this issue in?

- [X] Native App (Electron)
- [X] Chrome
- [ ] Firefox
- [ ] Safari
- [ ] Other

### Reproduction Steps

1. Enable any Core localization
2. Create a new Compendium of any type

### What core version are you reporting this for?

Version 10 (build 284)

### Bug Checklist

- [ ] The issue occurs while all Modules are disabled

**Comment by Fyorl** [comment] 2022-09-06 19:10
Duplicate of #8036

**Closed by Fyorl** 2022-09-06 19:10 UTC
Labels: bug
