### ISSUE TITLE
Linux, Server: Add logrotate for /foundrydata/Logs

### ISSUE THREAD

**Issue by ChaoticEvilDM** [foundryvtt/foundryvtt#10578] opened 2024-03-18 23:37 UTC
### Where did you find it, or where does it belong for requests?

Knowledge Base (https://foundryvtt.com/kb/)

### What page or file needs a look at?

https://foundryvtt.com/article/installation/

### What core version are you reporting this for?

Version 10 Testing 1 (build 274)

### What is wrong, in your opinion?

Issue: Currently, logs are not being emptied or deleted automatically which can cause congestion on file system and lead to a multitude of issues on the disk foundryvtt is installed on. I was unable to identify any such measure within the logging system. Since a logstash package is pulled upon installation, I operate under the assumption that a form of time series database is used to store logs for searching and application access purposes in addition to those on the file system.

Solution for file system logs:
Offer a logrotate config for all logs placed in the Log directory. I am currently unable to provide proper context as logging behavior between applications can differ, based on the type of file lock. Apache2 requires running a pre- and postrotation script will other application don't need a precaution like this.

**Comment by aaclayton** [comment] 2024-03-19 01:36
Closing as duplicate of #9972 and merging this comment over there.

**Closed** 2024-03-19 01:36 UTC
Labels: documentation
