### ISSUE TITLE
Correct HTML markup issue with FilePicker S3 buckets whic h prevented file upload

### ISSUE THREAD

**Issue by MrZeyami** [foundryvtt/foundryvtt#11218] opened 2024-06-15 16:40 UTC
### What happened?

The client gives me an error "File upload failed: The specified bucket is not valid."
I've confirmed this is not an issue with the bucket configuration; have set up new access keys and still the issue persists.
Using the same configuration settings, I was able to upload files on V11.
I should note that browsing and downloading from the bucket still work.

This is using the js node on windows 11.

### What ways of accessing Foundry can you encounter this issue in?

- [ ] Native App (Electron)
- [X] Chrome
- [X] Firefox
- [ ] Safari
- [ ] Other

### Reproduction Steps

1) Open File Picker
2) Switch to S3 storage
3) Choose a location
4) Attempt to upload a file

### What core version are you reporting this for?

V12.327

### Relevant log output

```shell
Foundry VTT | Rendering FilePicker foundry.js:5802:15
Foundry VTT | Retrieved and compiled template templates/apps/filepicker.html foundry.js:7768:11
File upload failed: The specified bucket is not valid.
```

### Bug Checklist

- [x] The issue occurs while all Modules are disabled

**Comment by Havoclivekiller** [comment] 2024-06-16 15:27
I have the same problem. Worked on V11. I can give the configuration files, if needed.

**Comment by Norc** [comment] 2024-06-17 13:36
Possibly related to (or duplicate of) #11126.

**Comment by ChunkLightTuna** [comment] 2024-06-19 20:52
![image](https://github.com/foundryvtt/foundryvtt/assets/1526907/eaf1222f-7926-47dd-9166-d194d5d38a6c)

![image](https://github.com/foundryvtt/foundryvtt/assets/1526907/c9e59ff2-8be3-453c-822e-029f20f2290c)

**Comment by cgoins0125** [comment] 2024-06-22 05:09
Also having this issue. Have a work around of uploading files directly to s3, but it is not ideal.

**Comment by Havoclivekiller** [comment] 2024-06-22 05:55
> ![image](https://private-user-images.githubusercontent.com/1526907/341201945-eaf1222f-7926-47dd-9166-d194d5d38a6c.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTkwMzYwNDIsIm5iZiI6MTcxOTAzNTc0MiwicGF0aCI6Ii8xNTI2OTA3LzM0MTIwMTk0NS1lYWYxMjIyZi03OTI2LTQ3ZGQtOTE2Ni1kMTk0ZDVkMzhhNmMucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDYyMiUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA2MjJUMDU1NTQyWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9NDE1NDkxMTcwYjI4OGQ2NjM5ODdmNTM1NDMzZDE2NTdiOTYwZDYwODYxYTFmMjc2NDkwMDBhNTQ2NjE2YTM2NSZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.8rU7FW4hg50SfbGUk_cwMqf16g19uMWkiKrrmbEeTJ4)
> 
> ![image](https://private-user-images.githubusercontent.com/1526907/341201764-c9e59ff2-8be3-453c-822e-029f20f2290c.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTkwMzYwNDIsIm5iZiI6MTcxOTAzNTc0MiwicGF0aCI6Ii8xNTI2OTA3LzM0MTIwMTc2NC1jOWU1OWZmMi04YmUzLTQ1M2MtODIyZS0wMjlmMjBmMjI5MGMucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDYyMiUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA2MjJUMDU1NTQyWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9YjNiZWE5YjUwOGE2Y2M1ZDJlZDQ4YmJkMDFkZjE4ZGZkMmQ0YzIzNjJiZmFkNDllNTMzNDRlNzg4M2VlOWMzNiZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.TAdNCp0dr2_YiTDawDVXrPxXCwzn0Sur88NmmsVNfPA)
> 
> changing `options` in `#onUpload()` from
> 
> ```js
> const options = { bucket: form.bucket ? form.bucket.value : null };
> ```
> 
> to
> 
> ```js
> const options = { bucket: form.bucket ? this.sources.s3.buckets[form.bucket.value] : null };
> ```
> 
> fixed my upload issues.

This worked for me, thanks!

**Comment by MrZeyami** [comment] 2024-06-22 18:16
> ![image](https://private-user-images.githubusercontent.com/1526907/341201945-eaf1222f-7926-47dd-9166-d194d5d38a6c.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTkwODA0MzIsIm5iZiI6MTcxOTA4MDEzMiwicGF0aCI6Ii8xNTI2OTA3LzM0MTIwMTk0NS1lYWYxMjIyZi03OTI2LTQ3ZGQtOTE2Ni1kMTk0ZDVkMzhhNmMucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDYyMiUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA2MjJUMTgxNTMyWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9YjFiZDc5MDY0ZDEyZmZiMGFlODJiMTI1MzcxZmU1NDQ3ZGZiODRlYzg2NTFlNWRiZTk1YmMzYTY1ZmU2NTg2YSZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.tmCG58a_uiERshT-pnNV4RVKA_8gpg3IcXcHkLztKok)
> 
> ![image](https://private-user-images.githubusercontent.com/1526907/341201764-c9e59ff2-8be3-453c-822e-029f20f2290c.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTkwODA0MzIsIm5iZiI6MTcxOTA4MDEzMiwicGF0aCI6Ii8xNTI2OTA3LzM0MTIwMTc2NC1jOWU1OWZmMi04YmUzLTQ1M2MtODIyZS0wMjlmMjBmMjI5MGMucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDYyMiUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA2MjJUMTgxNTMyWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9MDJiMGRiNTliOWExOTFkYzk5ZTk3M2E3M2EwOGM5NmMzMjQ4ZTMzMzJjNWI5OTNhYTA3ZTkwODE0MDI2ZWQzMSZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.0pEB6eJ7DnILtOd3AEb14ijmA5K4HI1HRBu1fwY-91U)
> 
> changing `options` in `#onUpload()` from
> 
> ```js
> const options = { bucket: form.bucket ? form.bucket.value : null };
> ```
> 
> to
> 
> ```js
> const options = { bucket: form.bucket ? this.sources.s3.buckets[form.bucket.value] : null };
> ```
> 
> fixed my upload issues.

This fixed a long-time issue I have had with the bucket not listing or opening correctly, however my initial upload error persists.

**Comment by jilesley** [comment] 2024-06-25 22:37
> ![image](https://private-user-images.githubusercontent.com/1526907/341201945-eaf1222f-7926-47dd-9166-d194d5d38a6c.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTkzNTUxNDEsIm5iZiI6MTcxOTM1NDg0MSwicGF0aCI6Ii8xNTI2OTA3LzM0MTIwMTk0NS1lYWYxMjIyZi03OTI2LTQ3ZGQtOTE2Ni1kMTk0ZDVkMzhhNmMucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDYyNSUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA2MjVUMjIzNDAxWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9MmQ3NzA0ZWU0ZGMxNjRlMjNkMDk4ZjY0MTc0Y2U3MDhmYjNjOTdmYWU0YjA0OGY4Y2Q1ZDMyYWNhNDg2OWUyZCZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.PRjHSZQE-_8oYzTs-khyNioVZcunQCulwMq6ah-nI1E)
> 
> ![image](https://private-user-images.githubusercontent.com/1526907/341201764-c9e59ff2-8be3-453c-822e-029f20f2290c.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTkzNTUxNDEsIm5iZiI6MTcxOTM1NDg0MSwicGF0aCI6Ii8xNTI2OTA3LzM0MTIwMTc2NC1jOWU1OWZmMi04YmUzLTQ1M2MtODIyZS0wMjlmMjBmMjI5MGMucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDYyNSUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA2MjVUMjIzNDAxWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9ZDBjNWZlZDg4OTU3MzhjZWRhN2MwM2U0ZDEzMGZhMjYxOWRlOGUzOTQxZTMxM2JiYTU3YzBiNjkwNWEwZGM1NyZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.GQk8ye4wtlYtnaSK7nfiu8N9MiivYa_130vubCXWbWA)
> 
> changing `options` in `#onUpload()` from
> 
> ```js
> const options = { bucket: form.bucket ? form.bucket.value : null };
> ```
> 
> to
> 
> ```js
> const options = { bucket: form.bucket ? this.sources.s3.buckets[form.bucket.value] : null };
> ```
> 
> fixed my upload issues.

Was also having this issue and this solved it! Nice find!

**Closed** 2024-06-27 13:21 UTC
Labels: bug, ux

**Comment by carolinex** [comment] 2024-07-14 00:24
I'm having this issue after upgrading Foundry to version 12.328. Folders can be created and file access works, I just can't upload any new files.
