### ISSUE TITLE
Roll#toJSON should call toJSON on its terms for cases where it is not immediately serialised with JSON.stringify

### ISSUE THREAD

**Issue by ironmonk88** [foundryvtt/foundryvtt#8260] opened 2022-09-23 03:53 UTC
### What happened?

Using the toJSON function on a Roll is just dumping the term values instead of converting it to JSON.  So if you save this value to the database, the class information is missing, and retrieving the information can't restore the Terms but instead leaves them as objects.

### What ways of accessing Foundry can you encounter this issue in?

- [ ] Native App (Electron)
- [ ] Chrome
- [ ] Firefox
- [ ] Safari
- [ ] Other

### Reproduction Steps

let roll = new Roll("1d20")
let rolljson = roll.toJSON()
game.user.setFlag("core", "testroll", rolljson)
let savedroll = game.user.getFlag("core", "testroll")
let newroll = Roll.fromData(savedroll)

![image](https://user-images.githubusercontent.com/75920956/191889256-e4934648-7653-465e-9486-ed0eb50278af.png)

### What core version are you reporting this for?

Version 10 Testing 3 (build 277)

### Bug Checklist

- [ ] The issue occurs while all Modules are disabled

**Comment by mkahvi** [comment] 2022-09-23 13:58
It appears `.class` is stripped from the data in serialization somewhere deeper in, making me unable to even apply a hacky fix for this.

**Comment by ironmonk88** [comment] 2022-09-23 14:22
Would this not work?
```
toJSON() {
    return {
      class: this.constructor.name,
      options: this.options,
      dice: this._dice,
      formula: this._formula,
      terms: this.terms.map((t) => t.toJSON()),
      total: this._total,
      evaluated: this._evaluated
    };
  }
```
I'm using something similar to correct it in my code.  But I just don't know if there are other ramifications to altering it in that way.
Or is the issue in the part that saves it to the database?

**Comment by mkahvi** [comment] 2022-09-23 19:18
That actually does seem to work perfectly. My tests were only for overriding the RollTerm.toJSON() and the like, which clearly was too deep.

**Comment by Fyorl** [comment] 2022-09-27 15:56
I'm not sure this is actually a bug. `toJSON` is called automatically by `JSON.stringify`, so the `terms` array does get serialised correctly when using `JSON.stringify`.
```js
const r = new Roll('1d20');
console.log(JSON.stringify(r));
// {"class":"Roll","options":{},"dice":[],"formula":"1d20","terms":[{"class":"Die","options":{},"evaluated":false,"number":1,"faces":20,"modifiers":[],"results":[]}],"evaluated":false}
console.log(JSON.stringify(r.toJSON())); // This also works but is redundant.
```
This is how `ChatMessage`s store their `rolls`, for example, and they should probably be stored in flags the same way:
```js
const r = new Roll('1d20');
game.user.setFlag('scope', 'roll', JSON.stringify(r));
console.log(Roll.fromJSON(game.user.getFlag('scope', 'roll')));
```

That's not to say that there would be any *harm* necessarily in having `Roll#toJSON` also do this itself rather than relying on `JSON.stringify` to do it, but I think we'd have to re-evaluate. Are there some use-cases, such as embedding rolls in some other larger structure where it's difficult/undesirable to use `JSON.stringify`?

**Comment by Fyorl** [comment] 2022-09-27 16:00
@mkahvi Not if you use `JSON.stringify`. You can clearly see in my comment that the serialised terms contain a `class` field.

**Comment by mkahvi** [comment] 2022-09-27 16:01
Then chat messages aren't using it. Do a `/roll 3d6` and inspect the `.rolls` part of the message.

**Comment by Fyorl** [comment] 2022-09-27 16:05
The `rolls` field of `BaseChatMessage` is defined as a `JSONField` so it should be automatically serialised with `JSON.stringify`.

**Comment by mkahvi** [comment] 2022-09-27 16:15
Looking at the code that is causing the problem, it seems to be using `roll: roll.toJSON()` like in v9 instead of `rolls` in the chat message creation data. So is the shim for that broken?

**Comment by mkahvi** [comment] 2022-09-28 17:07
Okay, PF1 case I think was definitely system error.

However I'm curious why did this become a problem with 10.286 but is fine with 10.285?

**Comment by Fyorl** [comment] 2022-09-28 17:25
Does `Roll#toJSON` call `toJSON` on terms in 285? I can't see anything like that in the commit history. Or do you mean there's some PF1e code that worked correctly in 285 but not anymore? Hard to say why that might be. If we had some reports from other systems or other code that stopped working, it might help narrow things down.

I'm going to repurpose this issue since, from what I can tell, having `Roll#toJSON` do this itself should not have any adverse effects or break anything, so we can improve the ergonomics of the API here.

**Comment by Plushtoast** [comment] 2022-09-28 18:28
I can confirm that it was working for The Dark Eye System too in early v10 version but now it isn't anymore.
I came to the same conclusion as ironmonk that terms.map(x => x.toJSON) would help, but I also compared this to v9 where this is also not there but it still works.
Working fine in v9, working fine early v10 --> now broken.

**Comment by Fyorl** [comment] 2022-09-28 19:11
Well `Roll#toJSON` has not changed since v9 as you noted. And it hasn't regressed in the core software either as chat message rolls are being serialised/deserialised correctly as far as I can tell. So the change must be somewhere else, but it's hard to locate given core rolls are working without issue.

Do you have an example of code that stopped working in DSA that I can maybe cross-reference against the PF1e code that Mana linked?

**Comment by mkahvi** [comment] 2022-09-28 21:59
The code that worked in PF1 for 10.285 is in the commit I linked in my previous message. Apparently mergeObject() was trashing the roll.toJSON() structure since the terms weren't turned into JSON.

**Comment by mkahvi** [comment] 2022-09-28 22:11
It's probably the expandObject/mergeObject changes for dealing with contents of arrays in updates.

**Closed** 2022-10-05 18:34 UTC
Labels: dice, api
