### ISSUE TITLE
Module sidegrade stripping the verified key from the compatibility field

### ISSUE THREAD

**Issue by Fyorl** [foundryvtt/foundryvtt#8099] opened 2022-09-05 12:23 UTC
Originally reported by Skimble#8601 https://discord.com/channels/170995199584108546/956306859491471420/1016069902962016487

This is a core module migration/versioning bug in 10.284 (I think)

This is the manifest for one of my modules:

```
{
  "title": "zSync",
  "description": "A module that synchronises the z-index of tokens across clients.",
  "authors": [
    {
      "name": "Richard Bellingham (Skimble)"
    }
  ],
  "version": "0.0.6",
  "scripts": [
    "zsync.js"
  ],
  "socket": true,
  "manifest": "https://raw.githubusercontent.com/Sk1mble/zsync/master/module.json",
  "download": "https://github.com/Sk1mble/zsync/archive/v0.0.6.zip",
  "id": "zsync",
  "name":"zsync",
  "compatibility": {
    "minimum": "10.275",
    "verified": "10.275"
  },
  "minimumCoreVersion":"10.275"
}
```

I've also updated it to be compatible with 10.284 in the package manager, but it should obviously be showing as compatible with 10.275 at minimum. But for some reason, when I check for updates on installed modules, Foundry is migrating the module.json file, stripping out the 'verified' key of the compatibility object, leading to it being shown as not having compatibility data specified.

![image](https://user-images.githubusercontent.com/207433/188448275-ed21e04d-b5bc-4b8e-a743-cdb434b88d3e.png)

**Comment by aaclayton** [comment] 2022-09-05 13:17
Duplicate of https://github.com/foundryvtt/foundryvtt/issues/8081

**Closed by aaclayton** 2022-09-05 13:17 UTC
Labels: bug, packages
