### ISSUE TITLE
Restore touch control functionality flawed by changes in PixiJS

### ISSUE THREAD

**Issue by Chris76J** [foundryvtt/foundryvtt#10236] opened 2023-11-30 19:20 UTC
### What happened?

Touch control in FoundryVTT worked with 3rd party module add ons like Touchcontrol or Material Plane.
Since updates made in v11 it is broken and no longer works.
Above module developers won´t (be able to) fix it.
For details what might have caused this in PixiJS, see module (currently somewhat working): 
https://foundryvtt.com/packages/gaming-table/
-> section "Well what did you contribute?" -> Custom Mouse Interaction Manager

As told: Touch controls are broken in the later v11 builds, but worked before with modules.

Since Patreon voting for v11 had "improve touch controls" in second place (of course my vote included) and is used in my group as essential "Wow!" factor in exploration and battle maps on my PC controlled touchscreen monitor setup, I hope there is a fix for this,

Best option would be a fully integrated touch control in FoundryVTT without extra modules.

### What ways of accessing Foundry can you encounter this issue in?

- [X] Native App (Electron)
- [X] Chrome
- [X] Firefox
- [ ] Safari
- [ ] Other

### Reproduction Steps

Use touch controls to move tokens on maps.
Without change it just opens character sheet -> Workaround was modification of Foundry.JS at #handleMouseDown method
But even with this modification you could just lift and move the token on the map, but no longer drop it again.
Now the only workaround is to use module Gaming Table. It´s developer states already that his work will soon after further updates of FoundryVTT no longer work.

Please fix this. Thank you.

### What core version are you reporting this for?

Version 11 Stable - Build 315

### Bug Checklist

- [ ] The issue occurs while all Modules are disabled

**Comment by aaclayton** [comment] 2023-12-01 13:25
Hi @Chris76J thanks for the report. Unfortunately it's a bit unclear what the technical details of the problem are. Can you go into more specifics?

@Feu-Secret this might be something worth looking into due to the changes in the interaction manager we made in v11. If it caused a regression for touch support it's probably something we want to address in v12.

**Comment by Chris76J** [comment] 2023-12-01 22:42
And this issue perfectly describes and shows in a video the issue with dropping the token:
https://github.com/dan-cave/gaming-table/issues/1

**Comment by Bryan-Legend** [comment] 2024-01-19 17:18
Maybe it's not clear, but this bug breaks all support for mobile use of Foundry, so it's very important.

**Comment by OmegaRogue** [comment] 2024-01-31 17:49
My current assemption is that this was caused by PixiJs deprecating its old interaction system with 7.0, and the new one barely supporting touch from what ive found

**Comment by Chris76J** [comment] 2024-01-31 18:29
> My current assemption is that this was caused by PixiJs deprecating its old interaction system with 7.0, and the new one barely supporting touch from what ive found

This seemed to have happened in my experience and according to developer Dan Cave with [module Gaming-Table](https://github.com/dan-cave/gaming-table), which he only himself declares as a temporary workaround. Touch functionality in FoundryVTT always worked better with the other old modules [Touch-VTT](https://github.com/Oromis/touch-vtt) or the [touchscreen controls in Material Plane](https://github.com/MaterialFoundry/MaterialPlane/wiki/Touch-Screen-Guide) which were are no longer maintained after it broke with these deep changes in FoundryVTT.

**Comment by OmegaRogue** [comment] 2024-01-31 18:30
> > My current assemption is that this was caused by PixiJs deprecating its old interaction system with 7.0, and the new one barely supporting touch from what ive found
> 
> This seemed to have happened in my experience and according to developer Dan Cave with [module Gaming-Table](https://github.com/dan-cave/gaming-table), which he only himself declares as a temporary workaround. Touch functionality in FoundryVTT always worked better with the other old modules [Touch-VTT](https://github.com/Oromis/touch-vtt) or the [touchscreen controls in Material Plane](https://github.com/MaterialFoundry/MaterialPlane/wiki/Touch-Screen-Guide) which were are no longer maintained after it broke with these deep changes in FoundryVTT.

for me things are mostly working with touch-vtt and this small tweak to the foundry code https://github.com/Oromis/touch-vtt/issues/61#issuecomment-1723727061

**Comment by Chris76J** [comment] 2024-01-31 18:44
> > > My current assemption is that this was caused by PixiJs deprecating its old interaction system with 7.0, and the new one barely supporting touch from what ive found
> > 
> > 
> > This seemed to have happened in my experience and according to developer Dan Cave with [module Gaming-Table](https://github.com/dan-cave/gaming-table), which he only himself declares as a temporary workaround. Touch functionality in FoundryVTT always worked better with the other old modules [Touch-VTT](https://github.com/Oromis/touch-vtt) or the [touchscreen controls in Material Plane](https://github.com/MaterialFoundry/MaterialPlane/wiki/Touch-Screen-Guide) which were are no longer maintained after it broke with these deep changes in FoundryVTT.
> 
> for me things are mostly working with touch-vtt and this small tweak to the foundry code [Oromis/touch-vtt#61 (comment)](https://github.com/Oromis/touch-vtt/issues/61#issuecomment-1723727061)

This just worked for me to avoid the accidental opening of the character sheet instead by the DoubleClick delay. [And in your linked comment is PixiJS event handling suspected](https://github.com/Oromis/touch-vtt/issues/61#issuecomment-1723727061). But even with this patch I could not "[drop the token anymore](https://github.com/dan-cave/gaming-table/issues/1)".

**Comment by OmegaRogue** [comment] 2024-01-31 18:46
> > > > My current assemption is that this was caused by PixiJs deprecating its old interaction system with 7.0, and the new one barely supporting touch from what ive found
> > > 
> > > 
> > > This seemed to have happened in my experience and according to developer Dan Cave with [module Gaming-Table](https://github.com/dan-cave/gaming-table), which he only himself declares as a temporary workaround. Touch functionality in FoundryVTT always worked better with the other old modules [Touch-VTT](https://github.com/Oromis/touch-vtt) or the [touchscreen controls in Material Plane](https://github.com/MaterialFoundry/MaterialPlane/wiki/Touch-Screen-Guide) which were are no longer maintained after it broke with these deep changes in FoundryVTT.
> > 
> > 
> > for me things are mostly working with touch-vtt and this small tweak to the foundry code [Oromis/touch-vtt#61 (comment)](https://github.com/Oromis/touch-vtt/issues/61#issuecomment-1723727061)
> 
> This just worked for me to avoid the accidental opening of the character sheet instead by the DoubleClick delay. [And in your linked comment is PixiJS event handling suspected](https://github.com/Oromis/touch-vtt/issues/61#issuecomment-1723727061). But even with this patch I could not "[drop the token anymore](https://github.com/dan-cave/gaming-table/issues/1)".

for me the dropping works as long as i have touchvtt enabled

**Comment by OmegaRogue** [comment] 2024-02-03 00:19
foundry is still using MouseInteractionManager, which its carrying around itself as that was removed in pixijs 7 in favor of a new event system, I'm trying to make touch functionality based on the new pixijs system

**Comment by OmegaRogue** [comment] 2024-02-04 15:26
The biggest problem with the entire new event system of pixiJS seems to be that you can't get a proper `TouchEvent` any more, there is no way to get the `touches` property or to even associate movement events from different fingers easily. The best way i currently see to get around this is to manually register event handler for the javascript touch events

**Comment by Chris76J** [comment] 2024-02-04 15:32
> The biggest problem with the entire new event system of pixiJS seems to be that you can't get a proper `TouchEvent` any more, there is no way to get the `touches` property or to even associate movement events from different fingers easily. The best way i currently see to get around this is to manually register event handler for the javascript touch events

-> Since I am not a developer myself, I could just point out to the developers with affected modules in my statement above.
They could point out to their used methods or maybe even suggest, how to get this done in the best way possible.
I hope for the best. Thanx for your efforts.

**Comment by aaclayton** [comment] 2024-02-04 15:34
I would be shocked if the new PIXI 7 event system did not include built-in support for touch events. I hope there's a misunderstanding here that can be easily resolved.

**Comment by OmegaRogue** [comment] 2024-02-04 15:50
this PR here removed the `TouchEvent`: https://github.com/pixijs/pixijs/pull/9474

**Comment by OmegaRogue** [comment] 2024-02-04 16:17
After more investigation, it seems like the events that can be listened to are the elements from the `touches` array, but somehow the original value of the property `identifier` gets lost by the time the event gets to the registered event handlers. If it didnt get lost, it would be possible to reconstruct the `TouchEvent` from the multiple events it gets split into

**Comment by OmegaRogue** [comment] 2024-02-05 13:14
I don't know what was going on yesterday that I was only receiving one identifier value regardless of touch point, but today I'm getting the correct identifiers. With the correct identifiers, it should be pretty easy to get touch working again properly, as the touches array can be put together again by keeping track of events

**Comment by OmegaRogue** [comment] 2024-02-05 15:44
for the time being, I've managed to get `touches` back using this libWrapper snippet:
```js
// get the path to the function, this is a bit weird because pixijs is minified
const PixiNormalizePointer = `PIXI.extensions._queue["renderer-canvas-system"].["${PIXI.extensions._queue["renderer-canvas-system"].findIndex((b) => b.name === "events")}"].ref.prototype.normalizeToPointerData`;
libWrapper.register(MODULE_ID, PixiNormalizePointer, (wrapped, event) => {
	if (event instanceof TouchEvent) {
		const normalizedEvents = wrapped(event);
		const newNormalizedEvents = [];
		for (const normalizedEvent of normalizedEvents) {
			normalizedEvent.touches = event.touches;
			normalizedEvent.targetTouches = event.targetTouches;
			normalizedEvent.changedTouches = event.changedTouches;
			newNormalizedEvents.push(normalizedEvent);
		}
		return newNormalizedEvents;
	}
	return wrapped(event);
});
```
with that, `touches` is available in `event.nativeEvent.touches` in touch event handlers

**Comment by kuenzign** [comment] 2024-02-07 01:02
@OmegaRogue Where are you suggesting to put this workaround code at?

**Comment by OmegaRogue** [comment] 2024-02-07 02:16
> @OmegaRogue Where are you suggesting to put this workaround code at?

You put it into a module

**Comment by ksignorini** [comment] 2024-02-19 20:12
> > @OmegaRogue Where are you suggesting to put this workaround code at?
> 
> You put it into a module, one of which I'm working on

How's this coming...?

**Comment by OmegaRogue** [comment] 2024-02-20 00:30
> > > @OmegaRogue Where are you suggesting to put this workaround code at?
> > 
> > You put it into a module, one of which I'm working on
> 
> How's this coming...?

My original method is causing some very weird bugs with drag and drop of templates breaking everything else, so its looking like for now the best way will be to actually make a MouseInteractionManager for this. Using the proper, up to date pixijs event handling would be better, but as the rest of foundry relies on MouseInteractionManagers, it's better to work with foundry than to fight it

**Comment by OmegaRogue** [comment] 2024-02-20 00:43
I have however found another place where touch support is broken currently (haven't yet tested whether that also was a regression), and that is drag and drop from the sidebar, it seems like on mobile the dragstart and drop events aren't very reliable or supported well, Sortablejs (which does work on mobile, pf2e uses it for its lists) uses touchstart, touchend and touchcancel for mobile drag and drop

**Comment by aaclayton** [comment] 2024-02-20 01:36
> My original method is causing some very weird bugs with drag and drop of templates breaking everything else, so its looking like for now the best way will be to actually make a MouseInteractionManager for this. Using the proper, up to date pixijs event handling would be better, but as the rest of foundry relies on MouseInteractionManagers, it's better to work with foundry than to fight it

You are aware that the `MouseInteractionManager` class uses "proper up-to-date pixijs event handling" right? If you feel that is not the case can you elaborate why?

**Comment by OmegaRogue** [comment] 2024-02-20 02:42
> > My original method is causing some very weird bugs with drag and drop of templates breaking everything else, so its looking like for now the best way will be to actually make a MouseInteractionManager for this. Using the proper, up to date pixijs event handling would be better, but as the rest of foundry relies on MouseInteractionManagers, it's better to work with foundry than to fight it
> 
> You are aware that the `MouseInteractionManager` class uses "proper up-to-date pixijs event handling" right? If you feel that is not the case can you elaborate why?

Ah, i somehow didn't realize that. It looks a bit weird to have it set up like that compared to how the pixijs examples go about input handling, but having it centralized does make it easier to properly keep track of interaction state

**Comment by aaclayton** [comment] 2024-03-07 21:51
We have this issue assigned to be worked on, but we have not reached a conclusion yet.

**Comment by nuck1234** [comment] 2024-03-08 10:03
Good news, can you let me know where the issue is being tracked? 

I wanted to invest in a screen but want to make sure it will work efficiently.

**Comment by aaclayton** [comment] 2024-03-08 16:25
> Good news, can you let me know where the issue is being tracked?
> 
> I wanted to invest in a screen but want to make sure it will work efficiently.

Youre already in the exact issue where this issue is being tracked.

**Comment by Chris76J** [comment] 2024-03-21 21:03
Biweekly bump... ;-)
I hope you have had your next sprint and approached a conclusion.

**Comment by mmacgibbon** [comment] 2024-04-12 00:55
just commenting here so i know the status.  is only going to be in v12?  not v11?

**Closed** 2024-04-29 14:30 UTC
Labels: bug, ux

**Comment by Feu-Secret** [comment] 2024-04-29 14:36
So. In our code, we were processing both `pointer` and `mouse` events. `pointer` are working for both mouse and touch events. `mouse` are working only for... mouse events. The culprits were several occurrences of `mouseupoutside`, which have been changed to `pointerupoutside`. I have done some tests with Chrome and Firefox touch emulation, and it seems to work fine.
Pinging @Norc for additional tests in real conditions.

**Comment by Chris76J** [comment] 2024-04-29 17:58
These are great news! Thank you.
Can you please describe, what effect this will have on the existing modules enabling touch control in FoundryVTT?
Do developers now have to adopt the touch controls in their modules to "pointer" events to trigger the according actions?
Or does FoundryVTT now just allows touch control without any additional modul?

**Comment by Feu-Secret** [comment] 2024-04-30 09:20
> These are great news! Thank you. Can you please describe, what effect this will have on the existing modules enabling touch control in FoundryVTT? Do developers now have to adopt the touch controls in their modules to "pointer" events to trigger the according actions? Or does FoundryVTT now just allows touch control without any additional modul?

Modules using our API should benefit from the patch. Those handling events separately should simply ensure they handle `pointer` events instead of `mouse` events if they intend to capture mouse **_and_** touch events.
