### ISSUE TITLE
When resizing a rotated image tile, the resize preview shows the tile in its original rotation

### ISSUE THREAD

**Issue by Fyorl** [foundryvtt/foundryvtt#8278] opened 2022-09-26 11:35 UTC
Originally reported by Scythen#8777 https://discord.com/channels/170995199584108546/956306859491471420/1022934905346338866

**ALL MODULES DISABLED?**  Yes  
**OS, Hosting, Browser (if applicable):** Win11, Self-Hosting, Electron  
**Short Description of bug:** Wonky behavior when resizing image tiles:

1) Rotate image (say 90 degrees).
2) Resizing the tile causes image to be rotated back to original orientation during the resize...making it awkward/impossible to use.

Also:
3)  When you drag the resizing handle PAST the opposite corner... the image doesn't flip orientation AND actually appears outside the image boundry.

https://user-images.githubusercontent.com/207433/192266546-ab197fd7-5618-4a07-a7b8-565d940de107.mp4

**Comment by aaclayton** [comment] 2022-09-26 13:43
Duplicate of #6373

**Closed by aaclayton** 2022-09-26 13:43 UTC
Labels: bug, ui, tiles
