### ISSUE TITLE
Overhead tiles now appear correctly for GM users, according to tile foreground menu status.

### ISSUE THREAD

**Issue by Fyorl** [foundryvtt/foundryvtt#7919] opened 2022-08-25 11:27 UTC
Originally reported by alaustin#0963 https://discord.com/channels/170995199584108546/956306859491471420/1012129693559947415

**ALL MODULES DISABLED?** TRUE  
**OS, Hosting, Browser (if applicable):** Win10, Electron App  
**Short Description of bug:** Overhead Tiles are always visible as a GM.  
**Simple steps to reproduce the bug:** Place an Overhead Tile. It will always be visible rather than being translucent for GMs as they behave in V9.  
**Screenshots and/or console errors:**

![image](https://user-images.githubusercontent.com/207433/186652528-2f8289e3-c969-4d89-911f-b7ecaaaf76c9.png)

**Comment by Fyorl** [comment] 2022-09-16 11:32
Additional user report claiming this issue as regressed:

Originally reported by HarryFurAlle#5062 https://discord.com/channels/170995199584108546/956306859491471420/1019970755322204181

**ALL MODULES DISABLED?** true  
**OS, Hosting, Browser (if applicable):** Windows, Chrome  
**Short Description of bug:**  https://github.com/foundryvtt/foundryvtt/issues/7919 The bug in this closed issue has been reintroduced at some point. Overhead tiles are always visible and never semi-transparent for the GM.  
**Simple steps to reproduce the bug:**
1) Create a new world without modules.
2) Place a tile and set it to Overhead.
3) Watch with sadness as the GM.

**Screenshots and/or console errors:**

![image](https://user-images.githubusercontent.com/207433/190629713-90215bdf-b24c-46e0-aae9-31332a3b049c.png)

**Comment by corpocracy** [comment] 2022-10-04 03:42
I'm having same issues as Fyorl above and can also reproduce. Some additional notes:
1. If marked as Overhead, not semi-transparent. If marked as Overhead AND Roof, will be semi-transparent.
2. Tiles marked as Overhead are always selectable and can be interacted with even when the Foreground Layer is not toggled.
3. The only thing the Foreground Layer toggle seems to do currently is make Roof tiles opaque.
4. Makes it impossible to work with normal tiles "underneath" an overhead tile which seems to be a regression from v9

**Comment by unsoluble** [comment] 2022-10-26 02:26
Another note: It's expected behaviour (from v9) that when you're on one of the two layers, the other layer is _not interactable_. That is, if you've got an Overhead tile on top of a background tile, when you've toggled to the Background layer all clicks should go right through the (transparent, if the other bits here are fixed) foreground tile and interact with the BG tile underneath. This does not currently work in 288.

**Closed** 2022-11-09 16:05 UTC
Labels: bug, tiles

**Comment by unsoluble** [comment] 2022-11-13 00:29
Note that the changes released for 10.290 did not include a fix for the interactivity issue noted in my comment above.

**Comment by aaclayton** [comment] 2022-11-13 03:10
> Note that the changes released for 10.290 did not include a fix for the interactivity issue noted in my comment above.

Sorry, that definitely slipped through the cracks. We need to get a separate issue created for it if you don't mind.
