### ISSUE TITLE
DocumentCollection.getSearchableFields not finding textSearch fields

### ISSUE THREAD

**Issue by farling42** [foundryvtt/foundryvtt#11073] opened 2024-05-29 14:12 UTC
### What happened?

In Foundry 12.324, foundry.js:12191  (DocumentCollection#getSearchableFields)

I have a StringField defined with "textSearch: true", but the field is never set up properly for searching. A search always find every single document in that particular collection.

The following line is removing the first element from the path, thus the path is never valid, and so the function uses "system" as the searchPath. This actually results in ALL the documents matching the pattern (an error is reported at a lower level, presumably because "system" isn't a string).
```
const [, ...path] = this.fieldPath.split(".");
```

Not stripping the first element from fieldPath works properly (since fieldPath doesn't include "system").
```
const path = this.fieldPath.split(".");
```

### What ways of accessing Foundry can you encounter this issue in?

- [ ] Native App (Electron)
- [X] Chrome
- [ ] Firefox
- [ ] Safari
- [ ] Other

### Reproduction Steps

Set an HTMLField to have "textSearch: true".
Use "Full Text Search" to search for a document with specific text in that field.
Observe that ALL the documents are marked as matching

### What core version are you reporting this for?

12.324

### Bug Checklist

- [X] The issue occurs while all Modules are disabled

**Comment by farling42** [comment] 2024-06-01 19:54
This is working correctly in Foundry 11.325.

In Foundry 11.325 it seems that `fieldPath` is now returning the path including the leading "system." which wasn't occurring in 11.324.

**Comment by dev7355608** [comment] 2024-06-10 14:06
Closing as duplicate of #10948.

**Closed by dev7355608** 2024-06-10 14:06 UTC
Labels: bug, data-models
