### ISSUE TITLE
Prototype token properties no longer retain their updates when closing FVTT

### ISSUE THREAD

**Issue by ThatOneBaguette** [foundryvtt/foundryvtt#8073] opened 2022-09-03 13:07 UTC
### What happened?

After the latest stable update I updated a former world of mine and modified some token prototypes. The tokens in question were scale 2 and had vision disabled. I decided to bring them back to scale 1 and to enable vision. I also added some other tokens. I placed them in my scene and all was well. Then I shut down Foundry VTT. 

Later I came back to Foundry and found that progress had been saved on everything EXCEPT the new properties of prototypes tokens. They were back at being vision disabled and scale 2 when I placed them. The new actors were fine somehow.

### What ways of accessing Foundry can you encounter this issue in?

- [X] Native App (Electron)
- [ ] Chrome
- [ ] Firefox
- [ ] Safari
- [ ] Other

### Reproduction Steps

I'm unsure exactly what happened to cause this but I assume this could work : 

1. Create a scene
2. Create an actor token with vision disabled and scale 2
3. Place it on the scene
4. Modify the prototype token so that it now has scale 1 and vision enabled. 
5. Close Foundry VTT 
6. Start it again 
7. Find the scene
8. Try placing the prototype token you updated : It should still have the same properties as the first prototype. 

### What core version are you reporting this for?

Version 10 Testing 3 (build 277)

### Bug Checklist

- [X] The issue occurs while all Modules are disabled

**Comment by unsoluble** [comment] 2022-09-03 17:22
For what it's worth, I can repro this reliably.

**Comment by patengelbert** [comment] 2022-09-04 13:55
I am having this issue as well. The token only saves if it is on a canvas, otherwise it is reset to default.

**Comment by DrTravisProthro** [comment] 2022-09-05 20:51
I've had this exact same bug, but I noticed a work around that seems to fix the issue. 

1. You modify the token on the canvas to all the settings you desire such as size, model, vision, etc...
2. Open the prototype token from the actor sheet and select the token on the canvas
3. Assign the token to the prototype token to update the settings 
 
When I did these steps, it seems to have made the settings persist when I swapped scenes or closed down the vtt and reopened the game.

**Comment by ThatOneBaguette** [comment] 2022-09-06 09:33
Neat, my foundry addiction is free to start up again. Thank you !

**Comment by Hoff851** [comment] 2022-09-06 13:49
+1 the issue.
It seems that using the 'update token' button does not save anything related to a prototype token whatsoever - vision, token art, linked actor, etc.
It happens on every system I've tested with no modules enabled, even on fresh worlds.

I can confirm that using the 'assign token' workaround posted above does seem to save and persist, so at least there is a workaround for now.

**Comment by Rawkul** [comment] 2022-09-06 13:58
+1 to the problem, it happens to me too.

And the workaround suggested by DrTravis works for me. Thanks for that! Also I've come up with another workaround:

1. Modify anything you need as you do usually, inside the actor's sheet.
2. Duplicate the actor and delete the original.

The duplicated actor will retain any changes, you can rename it as the original or whatever you want.

Hope this helps!

**Comment by Razeick** [comment] 2022-09-06 15:21
+1 the issue 
Also tried with no modules on fresh world. After changing the core default token settings for all tokens, such as always display name or enable token vision, I tried creating new actors but their token properties keep getting reverted back to the default token properties after reloading

**Comment by aaclayton** [comment] 2022-09-06 15:51
No need for all the +1s folks, we're aware and have fixed the issue for our next update (sometime this week)!

**Closed by aaclayton** 2022-09-06 15:51 UTC
Labels: bug, nonrepro, tokens
