### ISSUE TITLE
helpers.randomID chars string is off

### ISSUE THREAD

**Issue by Tommycore** [foundryvtt/foundryvtt#7890] opened 2022-08-22 09:49 UTC
### What happened?

common/utils/helpers.mjs `randomID()` function, first line of the function body, where you define viable characters for the id:
You have 9 two times in there.

### What ways of accessing Foundry can you encounter this issue in?

- [ ] Native App (Electron)
- [ ] Chrome
- [ ] Firefox
- [ ] Safari
- [ ] Other

### Reproduction Steps

n/a

### What core version are you reporting this for?

Version 10 Testing 4 (build 278)

### Bug Checklist

- [X] The issue occurs while all Modules are disabled

**Comment by aaclayton** [comment] 2022-08-22 14:14
Duplicate of https://github.com/foundryvtt/foundryvtt/issues/7877

**Closed by aaclayton** 2022-08-22 14:14 UTC
Labels: bug, api
