### ISSUE TITLE
Timeout error while trying to get list of avaiable modules for installation

### ISSUE THREAD

**Issue by grz0** [foundryvtt/foundryvtt#9150] opened 2023-04-02 18:27 UTC
### What happened?

Timeout error while trying to get list of avaiable modules for installation. I don't have this issue on v10 running on the same computer.

![image](https://user-images.githubusercontent.com/3605541/229371625-27fe4750-37a5-4e6d-ac86-c2ecb989040a.png)

### What ways of accessing Foundry can you encounter this issue in?

- [ ] Native App (Electron)
- [ ] Chrome
- [X] Firefox
- [ ] Safari
- [ ] Other

### Reproduction Steps

1. Install v11d1 in Linux and start nodejs server (node v18.15.0)
2. Enter Setup and try to get list of available modules 

### What core version are you reporting this for?

v11d1

### Relevant log output

```shell
TypeError: Cannot read properties of undefined (reading '0')
    at Tokenizer.stateBeforeEntity (/home/user/foundry/foundryvtt/resources/app/node_modules/htmlparser2/lib/Tokenizer.js:582:47)
    at Tokenizer.parse (/home/user/foundry/foundryvtt/resources/app/node_modules/htmlparser2/lib/Tokenizer.js:818:22)
    at Tokenizer.write (/home/user/foundry/foundryvtt/resources/app/node_modules/htmlparser2/lib/Tokenizer.js:158:14)
    at Parser.write (/home/user/foundry/foundryvtt/resources/app/node_modules/htmlparser2/lib/Parser.js:459:28)
    at sanitizeHtml (/home/user/foundry/foundryvtt/resources/app/node_modules/sanitize-html/index.js:588:10)
    at cleanHTML (file:///home/user/foundry/foundryvtt/resources/app/dist/database/validators.mjs:1:204)
    at System.cleanData (file:///home/user/foundry/foundryvtt/resources/app/dist/packages/package.mjs:1:3454)
    at System._initializeSource (file:///home/user/foundry/foundryvtt/resources/app/common/abstract/data.mjs:165:29)
    at System._initializeSource (file:///home/user/foundry/foundryvtt/resources/app/common/packages/base-package.mjs:248:11)
    at new DataModel (file:///home/user/foundry/foundryvtt/resources/app/common/abstract/data.mjs:47:19)
FoundryVTT | 2023-04-02 19:45:40 | [error] Cannot read properties of undefined (reading '0')
TypeError: Cannot read properties of undefined (reading '0')
    at Tokenizer.stateBeforeEntity (/home/user/foundry/foundryvtt/resources/app/node_modules/htmlparser2/lib/Tokenizer.js:582:47)
    at Tokenizer.parse (/home/user/foundry/foundryvtt/resources/app/node_modules/htmlparser2/lib/Tokenizer.js:818:22)
    at Tokenizer.write (/home/user/foundry/foundryvtt/resources/app/node_modules/htmlparser2/lib/Tokenizer.js:158:14)
    at Parser.write (/home/user/foundry/foundryvtt/resources/app/node_modules/htmlparser2/lib/Parser.js:459:28)
    at sanitizeHtml (/home/user/foundry/foundryvtt/resources/app/node_modules/sanitize-html/index.js:588:10)
    at cleanHTML (file:///home/user/foundry/foundryvtt/resources/app/dist/database/validators.mjs:1:204)
    at Module.cleanData (file:///home/user/foundry/foundryvtt/resources/app/dist/packages/package.mjs:1:3454)
    at Module._initializeSource (file:///home/user/foundry/foundryvtt/resources/app/common/abstract/data.mjs:165:29)
    at Module._initializeSource (file:///home/user/foundry/foundryvtt/resources/app/common/packages/base-package.mjs:248:11)
    at new DataModel (file:///home/user/foundry/foundryvtt/resources/app/common/abstract/data.mjs:47:19)
```

### Bug Checklist

- [X] The issue occurs while all Modules are disabled

**Comment by ViridiumRP** [comment] 2023-05-12 02:14
I have this exact same problem. Also running Linux on a nodejs server.  It seems this problem only occurs when updating from v10 to v11 via the application itself. If you do a clean install of v11, it seems to function normally, at least for myself. Hopefully this helps figure out whatever is causing it!

**Comment by silvative** [comment] 2023-05-16 16:17
Closing this one as a dupe of https://github.com/foundryvtt/foundryvtt/issues/9321

**Closed by silvative** 2023-05-16 16:17 UTC
Labels: bug, nonrepro, packages
