### ISSUE TITLE
Module dependencies should check against the module list state, instead of loaded modules

### ISSUE THREAD

**Issue by alexbrault** [foundryvtt/foundryvtt#10381] opened 2024-02-01 19:40 UTC
### User Experience

When enabling a module with dependencies, if those dependencies are not loaded, the module list pops up a dialog with the list of dependencies to ask if they should be enabled as well.

If you then enable more modules with the same dependencies, the pop up shows up each time, even though the dependencies are marked to be loaded when the list is saved.

If the dependencies check used the list check state instead of the module loaded state, enabling multiple modules at once would be a smoother experience

**Comment by aaclayton** [comment] 2024-02-03 02:27
I believe your report is a duplicate of https://github.com/foundryvtt/foundryvtt/issues/9762 which we implemented in V12 prototype 1 for release with V12 stable.

**Closed by aaclayton** 2024-02-03 02:27 UTC
