### ISSUE TITLE
New effects cannot be added to Active Effects

### ISSUE THREAD

**Issue by cswendrowski** [foundryvtt/foundryvtt#7978] opened 2022-08-29 15:28 UTC
From https://discord.com/channels/170995199584108546/956306859491471420/1013206815183482982

Create an Active Effect on an Item document.
Open the Configure Active Effect window. 
Click the Add New Effect button.
Input any data into the Attribute Key, Change Mode, and Effect Value fields.
Click Submit Changes.
Re-open Configure Active Effect window.
Observe no effects registered.

![](https://media.discordapp.net/attachments/956306859491471420/1013206814495612928/unknown.png)

**Comment by aaclayton** [comment] 2022-08-29 16:16
Might be a duplicate of something already fixed, but I'll take it to confirm.

**Comment by aaclayton** [comment] 2022-08-29 17:12
This has been fixed by a related change.

**Closed by aaclayton** 2022-08-29 17:12 UTC
Labels: bug, active-effects
