### ISSUE TITLE
keybindings for right sidebar tabs

### ISSUE THREAD

**Issue by rsek** [foundryvtt/foundryvtt#7256] opened 2022-06-11 12:38 UTC
### User Experience

in less tactically-oriented game systems, i spend much more time shuttling between the various sidebar tabs than handling macros, doing map manipulations, and so on. some keybindings for those tabs would be handy, and would also improve their accessibility (and maybe give them `role=tab`, `role=tabpanel`, and `role=tablist` to round them out!).

robust keyboard navigation of tab *content* would be a welcome enhancement to that functionality.

### Priority/Importance
robust keyboard accessibility is an important component of most a11y standards, and this would take foundry a step closer towards that. it'd also make use more comfortable for anyone who prefers keybindings to pointer-based tab navigation.

**Comment by plutoneld** [comment] 2022-06-12 01:42
Possibly a duplicate of #5643 (says menu in title but description mentions sidebar tabs)?

**Comment by rsek** [comment] 2022-06-12 03:32
> Possibly a duplicate of #5643 (says menu in title but description mentions sidebar tabs)?

damn, i think you're right 🤦 since foundry itself labels them "keybindings", it didn't even occur to me to search for "hotkeys"... might be worth updating the title of the other one to include both terms, since they're both quite common

**Closed** 2022-06-12 14:00 UTC
Labels: duplicate, todelete, folders, ux
