### ISSUE TITLE
Dynamic links to Scenes by UUID will open a journal entry if the scene has a journal entry configured in the ambience tab

### ISSUE THREAD

**Issue by anathemamask** [foundryvtt/foundryvtt#10422] opened 2024-02-18 20:06 UTC
This was actually discovered by users of the Kingmaker premium content module (https://github.com/foundryvtt/foundryvtt-premium-content/issues/496)

If a given Scene has a journal entry configured, clicking a dynamic link to that scene will open the journal entry instead.

Steps to reproduce:
- Create a journal entry
- Create a scene
- On the ambience tab of scene  configuration set the journal entry to the one you just created
- Save changes
- Create a new journal entry and text page
- Drag the scene from the sidebar into a text journal entry page, or directly link to it via UUID
- Save
- Click the link in your journal entry

**Comment by aaclayton** [comment] 2024-03-26 20:50
This was - at one time - an intentional feature. It may be a dumb one though and is probably a behavior we should remove for the sake of consistency.

**Comment by aaclayton** [comment] 2024-05-20 13:20
Closing as wontfix, it's an intentional feature not a bug. We can raise a separate discussion to evaluate whether it should work differently.

**Closed by aaclayton** 2024-05-20 13:20 UTC
Labels: bug, journal, scenes
