### ISSUE TITLE
10.284 Compendium creation fails for documents with multiple words in type

### ISSUE THREAD

**Issue by mxzf** [foundryvtt/foundryvtt#8083] opened 2022-09-05 00:54 UTC
### What happened?

When attempting to make a compendium in 10.284, it fails to create the compendium with a `errors.type: Rollable Table is not a valid choice` error for certain compendium types.  

All of the multi-word document type names are failing.  From some spot-checking, none of the single-word document names are failing to be created.

I suspect something is passing the localized/pretty name from the dropdown instead of the actual document type to the backend (which happens to work fine for single-word names that are incidentally the same).  

### What ways of accessing Foundry can you encounter this issue in?

- [ ] Native App (Electron)
- [ ] Chrome
- [ ] Firefox
- [ ] Safari
- [ ] Other

### Reproduction Steps

Attempt to create a compendium of type "Card Stack", "Journal Entry", or "Rollable Table".

### What core version are you reporting this for?

Version 10 Stable (build 284)

### Relevant log output

```shell
foundry.js:58303 Invalid Compendium Pack Data:
errors.type: Rollable Table is not a valid choice

foundry.js:2821 Uncaught (in promise) Error: Invalid Compendium Pack Data:
errors.type: Rollable Table is not a valid choice
```

### Bug Checklist

- [X] The issue occurs while all Modules are disabled

**Comment by mxzf** [comment] 2022-09-05 01:04
Digging into this more, foundry.js has this block in `CompendiumDirectory._onCreateCompendium
```js
const types = CONST.COMPENDIUM_DOCUMENT_TYPES.map(documentName => {
  return game.i18n.localize(getDocumentClass(documentName).metadata.label);
});
```

This is passing an array of already-localized document type labels into the compendium-create.html to be used as the option values
```handlebars
{{#each types}}
<option value="{{this}}">{{localize this}}</option>
{{/each}}
```

**Comment by ghost91-** [comment] 2022-09-05 08:22
This probably also makes it break for _all_ document types, when using a core localization module.

**Comment by Fyorl** [comment] 2022-09-05 11:08
I think this is being tracked in #8036 also

**Comment by aaclayton** [comment] 2022-09-05 13:09
Closing as duplicate of #8036

**Closed by aaclayton** 2022-09-05 13:09 UTC
Labels: bug, i18n, compendium
