### ISSUE TITLE
Changes made to a Scene while player clients are still loading it are not shown on those clients

### ISSUE THREAD

**Issue by Fyorl** [foundryvtt/foundryvtt#10050] opened 2023-10-02 15:47 UTC
Originally reported by gambettv https://discord.com/channels/170995199584108546/1065764070680186930/1152113490107060274

**ALL MODULES DISABLED?** true
**Short Description of bug**: Making changes to a scene while players load into the scene seems to cause the changes to not be registered on the player's screen. For instance, if I delete a token, they still see it. This also seems to happen if I add/remove light sources, and I think even walls.
**Simple steps to reproduce the bug**: Load players into a map, or while they load into Foundry for the first time. Delete a token while they're loading in but before they've loaded in.

**Comment by aaclayton** [comment] 2024-02-21 15:13
Closing as duplicate of #5624

**Closed by aaclayton** 2024-02-21 15:13 UTC
Labels: bug, scenes, canvas
