### ISSUE TITLE
Generalize the `TypedSchemaField` such that it can be used outside of an `ArrayField` context.

### ISSUE THREAD

**Issue by Ethaks** [foundryvtt/foundryvtt#10985] opened 2024-05-22 18:55 UTC
### What happened?

`TypedSchemaField`s fail their validation after updates since the server's response contains only a minimal diff, which excludes the `type` and thus fails `TypedSchemaField#_validateSpecial`'s check for `value.type`. The update _is_ successful on the server side, but the client errors in the update handling. Reloading the page presents the updated document.

### What ways of accessing Foundry can you encounter this issue in?

- [X] Native App (Electron)
- [ ] Chrome
- [ ] Firefox
- [ ] Safari
- [ ] Other

### Reproduction Steps

Create an actor type and give it the following model:
```js
export class TypedTest extends foundry.abstract.TypeDataModel {
	static defineSchema() {
		return {
			test: new foundry.data.fields.TypedSchemaField(
				{
					foo: new foundry.data.fields.EmbeddedDataField(TypesTestModel),
				},
				{ required: true, initial: { type: "foo", bar: "baz" } },
			),
		};
	}
}

class TypesTestModel extends foundry.abstract.DataModel {
	static defineSchema() {
		return {
			type: new foundry.data.fields.StringField({
				required: true,
				blank: false,
				initial: "foo",
				nullable: false,
			}),
			bar: new foundry.data.fields.StringField({
				required: true,
				blank: false,
				initial: "bar",
				nullable: false,
			}),
		};
	}
}
```

Update the actor with `actor.update({"system.test": { type: "foo", bar: "barg" } })`.

Side note: attempting to update without providing a `type` (i.e. directly updating `system.test.bar`) fails the pre-update validation since the type is then missing there already – not sure if that is intended though.

### What core version are you reporting this for?

Version 12 Stable 1 (Build 324)

### Relevant log output

```shell
foundry-esm.js:4699 Uncaught (in promise) Error: TypedTest validation errors:
  test: does not have a valid type
    at DataModelValidationFailure.asError (foundry-esm.js:4699:14)
    at TypedTest.validate (foundry-esm.js:10352:61)
    at new DataModel (foundry-esm.js:10101:12)
    at new TypeDataModel (foundry-esm.js:10716:7)
    at new TypedTest (typedtest.mjs:1:8)
    at TypeDataField.initialize (foundry-esm.js:9717:26)
    at Actor._initialize (foundry-esm.js:10260:29)
    at Actor._initialize (foundry-esm.js:10940:13)
    at Actor._initialize (foundry.js:10502:13)
    at Actor.updateSource (foundry-esm.js:10440:35)
```

### Bug Checklist

- [X] The issue occurs while all Modules are disabled

**Comment by aaclayton** [comment] 2024-05-23 13:44
Currently the `TypeDataModel` is incompatible with use anywhere except as the `system` field of a `Document`. It won't work anywhere else and would be a significant investment to make that happen. Don't expect any improvement here during V12.

**Comment by aaclayton** [comment] 2024-05-23 13:47
Aah, closing this as a duplicate of #10833

**Closed by aaclayton** 2024-05-23 13:47 UTC
Labels: api, blocked, data-models
