### ISSUE TITLE
Allow header buttons to define tooltips

### ISSUE THREAD

**Issue by mkahvi** [foundryvtt/foundryvtt#8216] opened 2022-09-16 14:38 UTC
### User Experience

Ability to define tooltips for header buttons would allow better explaining what the button is for in context, demystifying UI elements for players.

This currently requires additional hook on the app render to inject such.

**Comment by aaclayton** [comment] 2022-09-16 15:07
Related to #3273 and #5441

**Comment by Fyorl** [comment] 2023-10-24 14:25
Closing as duplicate of #6421

**Closed by Fyorl** 2023-10-24 14:25 UTC
Labels: ui, ux, api

**Comment by mkahvi** [comment] 2023-10-24 15:55
> Closing as duplicate of #6421

I think you linked wrong issue there.  #6412 is the correct one.

**Comment by Fyorl** [comment] 2023-10-24 15:56
> > Closing as duplicate of #6421
> 
> I think you linked wrong issue there. #6412 is the correct one.

Oops, thanks
