### ISSUE TITLE
World Migration window is not verfically centered when scrolled

### ISSUE THREAD

**Issue by cswendrowski** [foundryvtt/foundryvtt#9315] opened 2023-05-01 14:27 UTC
https://discord.com/channels/170995199584108546/1065764070680186930/1101255268765008012

When launching a world that hasn't been migrated, migration window appears at top of the DOM instead of in field of view.  This gives the appearance of the world not launching at all. 

Simple steps to reproduce the bug:  Have a long list of worlds. Scroll down until you are a full page below the top and launch any non migrated world.  Scroll back up to see the Migration Warning. 

![](https://media.discordapp.net/attachments/1065764070680186930/1101255268198789151/image.png?width=961&height=805)
![](https://media.discordapp.net/attachments/1065764070680186930/1101255268492394649/image.png?width=961&height=784)

**Comment by aaclayton** [comment] 2023-05-01 16:05
I am not able to reproduce this issue.

**Comment by Fyorl** [comment] 2023-05-02 11:11
Not able to reproduce this in chrome, firefox or electron, so closing as nonrepro

**Comment by MaxPat931** [comment] 2023-05-02 17:56
I was able to reproduce this by reducing the width of the Foundry window until it does not display the News/Featured Content elements

https://user-images.githubusercontent.com/86370342/235746323-93085d84-f3c4-42de-a644-c4756eb7cf1a.mp4

**Comment by Fyorl** [comment] 2023-05-02 18:20
Will take another look, thanks for the update

**Comment by MaxPat931** [comment] 2023-05-03 03:53
A similar issue can be seen on the Add-On Modules screen when Updating All, except it force scrolls you to the center of your modules list once the check is complete

https://user-images.githubusercontent.com/86370342/235829367-43f48ae3-7050-4512-b494-1a48e1f315bc.mp4

**Comment by Fyorl** [comment] 2023-05-03 11:26
That appears to have also been resolved now as part of the fix for the original reported issue

**Closed** 2023-05-03 11:26 UTC
Labels: bug, nonrepro, ui
