### ISSUE TITLE
Text drawings have a white outline

### ISSUE THREAD

**Issue by yjeroen** [foundryvtt/foundryvtt#8485] opened 2022-11-07 09:26 UTC
### What happened?

![image](https://user-images.githubusercontent.com/1303988/200274688-b93ddce0-e4ac-4820-bc71-f4c532cd0c5a.png)

### What ways of accessing Foundry can you encounter this issue in?

- [X] Native App (Electron)
- [X] Chrome
- [x] Firefox
- [x] Safari
- [x] Other

### Reproduction Steps

Create a text drawing that has a different text color then white.

### What core version are you reporting this for?

Version 10 Build 288

### Bug Checklist

- [X] The issue occurs while all Modules are disabled

**Comment by Fyorl** [comment] 2022-11-07 12:34
Duplicate of #8277

**Closed by Fyorl** 2022-11-07 12:34 UTC
Labels: bug
