### ISSUE TITLE
Not able to edit Journals created on V9 inside a shared compendium

### ISSUE THREAD

**Issue by Korghen** [foundryvtt/foundryvtt#8554] opened 2022-11-24 21:54 UTC
### What happened?

I can't edit journals created on V9 that are inside my shared compendium. I can open them and open the editor but save and/or close the editor gives an error and changes are not saved.
Tested with no module enable (only my shared compendium).
![Sans titre-1](https://user-images.githubusercontent.com/107515698/203865962-5238e037-9d52-4fe0-bb4c-ee0fd6b128c5.jpg)
I don't know if it should be, but the key in the error is not the ID of the journal.

### What ways of accessing Foundry can you encounter this issue in?

- [X] Native App (Electron)
- [ ] Chrome
- [ ] Firefox
- [ ] Safari
- [ ] Other

### Reproduction Steps

1. Open a shared compendium with journal entries
2. Open a journal created with V9.
3. Edit the journal.
4. Save and/or close the editor.

### What core version are you reporting this for?

Version 10 build 290

### Relevant log output

```shell
The key Ge3qgLNWPrS5zRia does not exist in the EmbeddedCollection Collection
fetch @ foundry.js:58907
notify @ foundry.js:58834
error @ foundry.js:58870
_handleError @ foundry.js:2874
(anonymous) @ foundry.js:2856
value @ socket.js:309
value @ socket.js:239
x.emit @ index.mjs:136
value @ manager.js:200
x.emit @ index.mjs:136
value @ index.js:119
value @ manager.js:192
x.emit @ index.mjs:136
value @ socket.js:323
x.emit @ index.mjs:136
value @ transport.js:104
value @ transport.js:97
ws.onmessage @ websocket.js:79


foundry.js:5877 Error: The key Ge3qgLNWPrS5zRia does not exist in the EmbeddedCollection Collection
    at EmbeddedCollection.get (/C:/Program%20Files/Foundry%20Virtual%20Tabletop/resources/app/common/utils/collection.mjs:119:13)
    at ServerDatabaseBackend._updateEmbeddedDocuments (/C:/Program%20Files/Foundry%20Virtual%20Tabletop/resources/app/dist/database/backend/server-backend.mjs:1:4284)
    at ServerDatabaseBackend.update (/C:/Program%20Files/Foundry%20Virtual%20Tabletop/resources/app/common/abstract/backend.mjs:153:31)
    at async Semaphore._try (/C:/Program%20Files/Foundry%20Virtual%20Tabletop/resources/app/common/utils/semaphore.mjs:101:17)
_onSubmit @ foundry.js:5877
await in _onSubmit (async)
submit @ foundry.js:6195
close @ foundry.js:6167
close @ foundry.js:6295
close @ foundry.js:63759
onclick @ foundry.js:5290
(anonymous) @ foundry.js:5198
dispatch @ jquery.min.js:2
y.handle @ jquery.min.js:2
```

### Bug Checklist

- [X] The issue occurs while all Modules are disabled

**Comment by Fyorl** [comment] 2022-11-28 12:52
This is a duplicate of #8417. The issue is that foundry does not really have a core concept of a 'shared compendium'. You can create a shared compendium by way of a module, but then you've created a module as far as the core software is concerned. Foundry will migrate world compendia automatically, but does not attempt to migrate module compendia, since that responsibility lies with the module author. It can be migrated with `pack.migrate()`, at which point this issue should resolve.

**Closed** 2022-11-28 14:43 UTC
Labels: duplicate, todelete
