### ISSUE TITLE
private folders in file picker visible when switching to player role

### ISSUE THREAD

**Issue by instantrice** [foundryvtt/foundryvtt#7545] opened 2022-07-18 16:22 UTC
* Foundry VTT Version: Version 9 - Build 269
* Operating System: Windows 10/Ubuntu 22.04
* How Are You Using Foundry: Electron, Chrome, Firefox
* Which Game System: dnd5e
* Modules Enabled?: no

### Issue Description
When DMs enable privacy on folders, the folder and items within are highlighted purple to indicate privacy is enabled. This is reflected in storage.json. When logging out as a GM and logging in as a player, the private items are still visible.

**Comment by Fyorl** [comment] 2022-07-20 18:41
I looked into this, but it appears to be working 'as designed'. If the user is logged into the server as the `admin`, they ignore file browser permissions, regardless of which role they have in the current active game. I was able to verify that logging in with a normal user session, I was unable to see any directories marked as private.

**Comment by aaclayton** [comment] 2022-07-20 21:36
Thanks for the investigation, that sounds working as intended and we can close this as wontfix.

**Closed by aaclayton** 2022-07-20 21:36 UTC
Labels: bug, authentication
