### ISSUE TITLE
UserConfig doesn't load properly on non-English localization

### ISSUE THREAD

**Issue by mclemente** [foundryvtt/foundryvtt#11041] opened 2024-05-27 03:08 UTC
### What happened?

![image](https://github.com/foundryvtt/foundryvtt/assets/5288872/62eb30f7-ea57-4344-b594-5c79635541f4)

### What ways of accessing Foundry can you encounter this issue in?

- [ ] Native App (Electron)
- [ ] Chrome
- [ ] Firefox
- [ ] Safari
- [ ] Other

### Reproduction Steps

- Load a system/module that has another language set in its package's json.
  - Alternatively, have a Core localization module installed.
- Change Foundry's language.
- Open User Config.

### What core version are you reporting this for?

V12.324

### Bug Checklist

- [X] The issue occurs while all Modules are disabled

**Comment by aaclayton** [comment] 2024-05-27 13:31
Closing as duplicate of #11003

**Closed by aaclayton** 2024-05-27 13:31 UTC
Labels: bug
