### ISSUE TITLE
Add "preview sound" option to filepicker when the selected file is an audio file

### ISSUE THREAD

**Issue by silvative** [foundryvtt/foundryvtt#9747] opened 2023-07-07 18:12 UTC
### User Experience

This would make it easier to select sounds for various functions by allowing you to "preview" them in the same way that our thumbnails do for images

**Comment by plutoneld** [comment] 2023-07-07 21:16
Seems like a duplicate of #5808

**Comment by plutoneld** [comment] 2023-07-25 19:29
#8861 too

**Comment by aaclayton** [comment] 2023-08-30 12:18
Closing as duplicate of #5808

**Closed by aaclayton** 2023-08-30 12:18 UTC
Labels: ui
