### ISSUE TITLE
SquareGrid#_measurePath calculations are incorrect for 3.5/Pathfinder Spell area highlights

### ISSUE THREAD

**Issue by esb** [foundryvtt/foundryvtt#11649] opened 2024-09-08 02:28 UTC
### What happened?

The 3.5/Pathfinder Spell effect templates are mostly centred on a vertex (top-left corner) of a cell. The grid cells included in the area are determined by the centre point of the grid cell. The calculations in SquareGrid#_measurePath are based on the offsets of the origin and destination points and these are rounded down in the calculations (using getOffset).
```javascript
const di = Math.abs(o0.i - o1.i);
const dj = Math.abs(o0.j - o1.j);
```
This results in a smaller distance/cost than required for the 3.5/Pathfinder rules.

Instead, the points should be used for the calculation and then rounded up.
```javascript
const di = Math.ceil(Math.abs(p0.y - p1.y) / this.size);
const dj = Math.ceil(Math.abs(p0.x - p1.x) / this.size);
```
The spell template measurements will always be wrong unless rounding up is used, and it will be impossible to replicate the exact template mapping as documented in "Dungeon Masters Guide" (V3.5), page 307.

This change will have no effect on measurements done from centre point to centre point.

### What ways of accessing Foundry can you encounter this issue in?

- [X] Native App (Electron)
- [ ] Chrome
- [ ] Firefox
- [ ] Safari
- [ ] Other

### Reproduction Steps

Requires custom 3.5/Pathfinder template code to test.

### What core version are you reporting this for?

Version 12 Build 331

### Bug Checklist

- [X] The issue occurs while all Modules are disabled

**Comment by aaclayton** [comment] 2024-09-10 01:54
We are actively making some changes here. I'm going to tag @dev7355608 on this issue since I think it will be resolved with our V13 changes. @dev7355608 to confirm.

**Comment by dev7355608** [comment] 2024-09-10 10:49
The math in `SquareGrid#_measurePath` is correct / working as intended. Systems that have different template shape rules can change the shapes of Measured Templates as needed. The PF2e system does so for example. Core's grid-based cone templates cover a few more grid spaces than 3.5/PF templates. From testing it looks like reducing the radius slightly makes the template cover the same grid squares as in 3.5/PF rules. Perhaps that helps.

**Closed by dev7355608** 2024-09-10 10:49 UTC
Labels: bug, grid

**Comment by esb** [comment] 2024-09-10 12:01
Sadly, it looks like this response doesn't help.

My Measured Template subclass does indeed try to calculate the correct grid squares to match the 3.5/Pathfinder templates when centred on a grid vertex and extensive testing demonstrates that it is not possible to get the calculation correct when using the ```SquareGrid#_measurePath``` API.

I'm not sure how to program the code to fix the problem by "reducing the radius slightly" - that's what fixing the incorrect rounding in the code will do, which is why I reported the problem in the first place.

**Comment by dev7355608** [comment] 2024-09-10 13:29
Reducing the radius by a little more than 1 pixel makes changes the condition for whether a grid space is covered from `distance to grid space center <= radius` (core) to `distance to grid space center < radius` (3.5/PF).

```js
  /** @override  */
  static getCircleShape(distance) {
    distance = Math.max(distance - (1.001 / canvas.dimensions.distancePixels), 0);
    return super.getCircleShape(distance);
  }
```

```js
  /** @override  */
  static getConeShape(distance, direction, angle) {
    distance = Math.max(distance - (1.001 / canvas.dimensions.distancePixels), 0);
    return super.getConeShape(distance, direction, angle);
  }
```

**Comment by aaclayton** [comment] 2024-09-10 13:58
Would this rounding rule be something we could provide an API-only configuration variable to assign?

**Comment by dev7355608** [comment] 2024-09-10 18:03
> Would this rounding rule be something we could provide an API-only configuration variable to customize?

The cost from A to B must always equal the cost of the direct path from A to B. This would be violated if there was different rounding in `SquareGrid#_measurePath`.

We could add a configuration option though such that only grid position with `< radius` are highlighted for get 3.5/PF style templates. This could be achieved with either by shrinking the shapes slightly as mentioned above, or by shifting the tested grid space centers in `MeasuredTemplate#_getGridHighlightPositions` slightly in the direction of the ray.

**Comment by esb** [comment] 2024-09-11 02:02
I'm beginning to suspect that there may be other more complex issues at play in this, rather than just the rounding in _measurePath.

For example, the problem is clearly demonstrated by drawing a 20ft radius circle centred on a vertex. Using 1/2/1 measuring, the template should cover only 2 grid squares at edges. See page 307 of the 3.5 DMG for how it should look. For a 20ft radius circle, the correct highlighting can be achieved by setting a radius of 19ft.

Now, based on the existing PF1 code, it appears necessary to highlight the cells based on the 3.5/PF1 standard 1/2/1 measurments. In the _getGridHighlightPositions routine, it's necessary to highlight cells based on the distance from the origin to the centre of each cell using 1/2/1 measuring, not exact distance measuring. For my own subclass, I ended up using a version of _measurePath with the above mentioned rounding fix and then using the path "cost", not "distance" to determine whether to highlight the cell or not.

From my observations, it appears that _getGridHighlightPositions is only using exact distance measurement, and not the underlying system measurement configuration.

Have I understood this correctly?

**Comment by esb** [comment] 2024-09-11 02:30
> Reducing the radius by a little more than 1 pixel makes changes the condition for whether a grid space is covered from `distance to grid space center <= radius` (core) to `distance to grid space center < radius` (3.5/PF).
> 
> ```js
>   /** @override  */
>   static getCircleShape(distance) {
>     distance = Math.max(distance - (1.001 / canvas.dimensions.distancePixels), 0);
>     return super.getCircleShape(distance);
>   }
> ```
> 
> ```js
>   /** @override  */
>   static getConeShape(distance, direction, angle) {
>     distance = Math.max(distance - (1.001 / canvas.dimensions.distancePixels), 0);
>     return super.getConeShape(distance, direction, angle);
>   }
> ```

Sorry. I tried this, but it had no effect. A 20ft radius circle centred on a vertex still has 4 cells highlighted at the edges, rather than the 2 required.

**Comment by dev7355608** [comment] 2024-09-11 12:00
> From my observations, it appears that _getGridHighlightPositions is only using exact distance measurement, and not the underlying system measurement configuration.

Core just tests whether the grid space's center point is contained within the template's shape to determine whether a grid space is covered (highlighted). Unless cone/circle shapes are overridden that is effectively the same as testing whether the angle grid space centers are within the angle (if cone) and whether the distance to the grid space center is less or equal to the radius. The distance measurements are that of the grid if Grid-based Templates Shapes is enabled and Euclidean otherwise.

> Sorry. I tried this, but it had no effect. A 20ft radius circle centred on a vertex still has 4 cells highlighted at the edges, rather than the 2 required.

Perhaps you have some other overrides in the MeasuredTemplate class that affect the grid highlighting, or you didn't enable Grid-based Template Shapes in the settings. Those are the results I get. Tested in dnd5e.

### Core
![image](https://github.com/user-attachments/assets/a2b9495a-a6cc-4a6b-b1d2-591024da2c3c)

### Slightly reduced radius
![image](https://github.com/user-attachments/assets/4bad803d-2f76-4ed2-acb5-2d6ab52c4927)

**Comment by esb** [comment] 2024-09-12 02:41
Ok. I can see the same results as you with Grid-Based templates.

From a personal preference, I'm not over the moon with the way the outline is drawn. I guess an actual circle feels better to me. However, showing this to my DM got a different response and he explained that it made it clearer about which squares were included in the template.,

However, the results are still problematic for cones and rays. If you check the 3.5 DMG and the PF1 Core Rulebook, cones have a centred origin, not a vertex or edge. Your examples are changing the origin to make the shape work. For a cone direction of 0 deg, the 15ft cone must have it's origin on an edge. When the cone gets to 30ft, it needs to be centred on a vertex.

The other issue is the highlighting for rays. If you look at the 3.5 Player's Handbook on page 176, there's a diagram showing the effect of line attacks. The rule is that all squares through which the line passes or touched are affected by the attack. The rays as highlighted by Foundry are simply the transversed path if you were moving grid by grid from start to finish. This is not the same as all cells that the line passes through or touches.

**Comment by dev7355608** [comment] 2024-09-12 10:55
> From a personal preference, I'm not over the moon with the way the outline is drawn. I guess an actual circle feels better to me. However, showing this to my DM got a different response and he explained that it made it clearer about which squares were included in the template.,

You can use an Euclidean circle and override `_getGridHighlightPositions` instead. The PF2 system does so I believe. It does have the disadvantage though that you can't tell without using the ruler whether a point is within the radius of the template. Also which larger circles you'll have entire grid spaces that seems to be within the templates shape, but aren't.

![image](https://github.com/user-attachments/assets/8e25f770-2a70-4e8c-acb6-003ab3894631)

Demo:
```js
  _getGridHighlightPositions() {
    const grid = canvas.grid;
    const {x: ox, y: oy} = this.document;
    const shape = this.shape;
    const bounds = shape.getBounds();
    bounds.x += ox;
    bounds.y += oy;
    bounds.fit(canvas.dimensions.rect);
    bounds.pad(1);

    const origin = {x: ox, y: oy};
    const radius = this.document.distance;

    // Identify grid space that have their center points covered by the template shape
    const positions = [];
    const [i0, j0, i1, j1] = grid.getOffsetRange(bounds);
    for ( let i = i0; i < i1; i++ ) {
      for ( let j = j0; j < j1; j++ ) {
        const offset = {i, j};
        const center = grid.getCenterPoint(offset);

        const covered = canvas.grid.measurePath([origin, center]).distance < radius;

        if ( !covered ) continue;
        positions.push(grid.getTopLeftPoint(offset));
      }
    }
    return positions;
  }
```

> However, the results are still problematic for cones and rays. If you check the 3.5 DMG and the PF1 Core Rulebook, cones have a centred origin, not a vertex or edge. Your examples are changing the origin to make the shape work. For a cone direction of 0 deg, the 15ft cone must have it's origin on an edge. When the cone gets to 30ft, it needs to be centred on a vertex.

We could add support template specific snapping behavior. I imagine that if the grid space center was the origin it would be a bit awkward for 30ft+ cones because it covers more grid spaces to one side of the cone. Imagine the caster of the cone spell is located at the blue square, but needs to place the origin of the template one square below, to cover move grid spaces south than north.
![image](https://github.com/user-attachments/assets/c850a255-155d-4996-8dc6-369fde4d2579)

> The other issue is the highlighting for rays. If you look at the 3.5 Player's Handbook on page 176, there's a diagram showing the effect of line attacks. The rule is that all squares through which the line passes or touched are affected by the attack. The rays as highlighted by Foundry are simply the transversed path if you were moving grid by grid from start to finish. This is not the same as all cells that the line passes through or touches.

You could override `_getGridHighlightPositions` to make that work. Core doesn't come with an algorithm that calculates the "supercover" of a line though.
