### ISSUE TITLE
Add a method for a Scene Region to be visible while the regions layer is not active, with configurable visibility permissions and aesthetic settings.

### ISSUE THREAD

**Issue by Norc** [foundryvtt/foundryvtt#10744] opened 2024-04-25 12:13 UTC
### User Experience

Currently, Scene Regions are only visible when the Scene Regions layer is active, and only then only to GM users.

A GM could benefit by being able to see certain Scene Regions during gameplay, such as traps or similar regions. Making a Scene Region visible to one or more players could also be useful, such as when one or more players detects such a trap.

This "visibility" should be similar to what the GM sees, but it should be rendered below tokens and not be affected by vision, perhaps in a manner similar to how Measured Templates currently work.

This configuration should be for only an individual Scene Region (or individual Shape perhaps). The following visibility levels would be ideal (when not on the Scene Regions layer):

- Invisible
- Visible to GMs
- Visible to all players
- Visible to certain players only

An interface similar to a Journal's Show Players button or a Document's Configure Permissions dialog might be useful here.

**Comment by Norc** [comment] 2024-04-25 12:23
Not sure if there should be any interaction with #10739. Should a GM be able to choose to not see a particular Scene Region, even if the global toggle is enabled?

**Comment by aaclayton** [comment] 2024-04-25 14:11
Deleting #10739 as duplicate of this one.

**Closed** 2024-05-02 21:53 UTC
Labels: ui, api, scene-regions
