### ISSUE TITLE
Feature Request: Ability to add/remove conditions to multiple tokens at once

### ISSUE THREAD

**Issue by cs96and** [foundryvtt/foundryvtt#11818] opened 2024-11-19 20:49 UTC
### User Experience

Initially requested on discord a while ago
https://discord.com/channels/170995199584108546/517504137403826177/1217557631061856316

If you select multiple tokens, then right click on them to add a condition, that condition is only added to the token you right-clicked on.  It would be nice if it added it to all the currently selected tokens.

I made a module to do this, but it's very hacky, and doesn't work with pf2e.
https://foundryvtt.com/packages/multistatus

**Comment by aaclayton** [comment] 2024-11-19 21:10
Closing as duplicate of #3793

**Closed by aaclayton** 2024-11-19 21:10 UTC
