### ISSUE TITLE
settings onChange function not being fired when scope is "world"

### ISSUE THREAD

**Issue by gotenxds** [foundryvtt/foundryvtt#11924] opened 2024-12-13 18:59 UTC
### What happened?

The onChange function for setting is not being fired when set programmatically and scope is set to "world"

If `scope` is set to `world` the the `set` function calls the `#setWorld` method without the onChange function, instead passing the `options` argument (which as far as I can see has no docs on what it can have) and then never calls the onChange function.

The on change function is only being passed down to the `#setClient` method where it is fired correctly

![image](https://github.com/user-attachments/assets/e814a534-6853-420b-a4a0-69e4be0de420)

### What ways of accessing Foundry can you encounter this issue in?

- [X] Native App (Electron)
- [X] Chrome
- [X] Firefox
- [ ] Safari
- [ ] Other

### Reproduction Steps

1. register a new setting with score `world`
2. change the setting via the `game.settings.set` method (not from the ui, it works from there for some reason)

### What core version are you reporting this for?

12 - 327

### Bug Checklist

- [X] The issue occurs while all Modules are disabled

**Comment by aaclayton** [comment] 2024-12-16 15:40
The setting `onChange` handler for world-scoped settings occurs on the far side of the database transaction to persist that setting change in the `Setting#_onUpdate` handler. 

This is working in V12 and V13 at the moment. Can you please double check your use case and report back with further diagnostics if there is still a problem?

**Comment by gotenxds** [comment] 2024-12-17 12:22
Hii @aaclayton , Maybe I misunderstood the cause but the issue still happens, the onChange method is never called when `scope` is set to `world`.

I have not tested this on v13 but I am using an updated version of v12.

Do note, when using scope: 'world' and changing the setting via the setting menu the onChange method is called, it is not called when manually calling the `set` function.

**Comment by aaclayton** [comment] 2024-12-18 16:45
@gotenxds I tracked down the cause of this to a bug in the `dnd5e` game system that needs to get patched.

**Comment by aaclayton** [comment] 2024-12-18 17:08
Resolved by code changes in `dnd5e` branch `4.2.x`!

**Closed by aaclayton** 2024-12-18 17:08 UTC
Labels: bug, nonrepro
