### ISSUE TITLE
_displayScrollingStatus() doesn't take into account if the scene is being viewed or not

### ISSUE THREAD

**Issue by dsorrentino** [foundryvtt/foundryvtt#9422] opened 2023-05-18 18:59 UTC
### What happened?

During a migration of a world, errors are being thrown about not being able to read the `visible` property from a `null` object.

When we are performing a migration on our system, we make changes to ActiveEffects as one of the migration steps.  This removes/re-adds ActiveEffects since they can't be changed on the actor.  This same process is used for active effects on token actors in the world.  This occurs on tokens whether or not the scene they are being viewed or not.

When the AE is added, Foundry eventually makes a call to _displayScrollingStatus():

```
  _displayScrollingStatus(enabled) {
    if ( !(this.flags.core?.statusId || this.changes.length) ) return;
    const actor = this.parent;
    const tokens = actor.isToken ? [actor.token?.object] : actor.getActiveTokens(true);
    const label = `${enabled ? "+" : "-"}(${this.label})`;
    for ( let t of tokens ) {
      if ( !t.visible || !t.renderable ) continue;
```
The 3rd line is setting the `tokens` constant by calling the `object` method and never checks what is returned because it assumes a list of tokens is returned. Unfortunately, that is not the case when the scene is not in view.  When the scene is not in view, it returns null, which then in the last line above, it can't find the `visible` property on `null`.

If we look at the object method:

```
  get object() {
    if ( this._object || this._destroyed ) return this._object;
    if ( !this.parent?.isView || !this.layer ) return null;
    this._object = this.layer.createObject(this);
    return this._object;
  }
```
The issue is the second if statement here because `this.parent` is the `Scene` the token is on and `isView` is set to `false` since it is not active/viewable.  Because this is false, it is returning `null` as the object.

The end result is that the test for `t.visible` throws an error since it `t` is `null`.

We would expect this not to throw errors in the console.

### What ways of accessing Foundry can you encounter this issue in?

- [ ] Native App (Electron)
- [X] Chrome
- [ ] Firefox
- [ ] Safari
- [ ] Other

### Reproduction Steps

We discovered it on the Cyberpunk Red - Core system but I was able to reproduce it in DnD5e:

1. Create a world using DnD5e
2. Launch World
3. Login as Gamemaster
4. Go to Scenes:
- Create Scene; name: a
- Create Scene; name: b
5. Go to Actors
6. Create Actor:
- Name: npc
- Type: Non-Player Character
7. Drag actor to **scene b** to create a token
8. Open token sheet
9. Go to Effect Tab
10. Click +Add next to Temporary Effects
11. Click the Edit icon next to the "New Effect"
12. Switch to the Effects Tab, click +
- Attribute Key: system.abilities.str.value
- Change Mode: Add
- Effect Value: 5
13. Click Submit Changes
14. Switch to Attributes and ensure Strength is increased by 5
15. Switch back to Effects tab and move the token sheet to the side so you can see the token.
16. Open Dev Tools

In the console, execute:

`const myAE = game.scenes.filter((s) => s.name === "b")[0].tokens.filter((t) => t.name === "npc")[0].actor.effects.filter((e) => e.label === "New Effect")[0]._id;`

This sets myAE to the _id of the Effect created on the token.

`await game.scenes.filter((s) => s.name === "b")[0].tokens.filter((t) => t.name === "npc")[0].actor.updateEmbeddedDocuments("ActiveEffect", [ {_id: myAE, disabled: true }])`

You should see the effect become disabled. Execute:
await game.scenes.filter((s) => s.name === "b")[0].tokens.filter((t) => t.name === "npc")[0].actor.updateEmbeddedDocuments("ActiveEffect", [ {_id: myAE, disabled: false }])

It should become active again and you should see the scrolling words on the token indicating it is active.

Close the sheet and switch to the `a` scene and execute the method in the console to disable the AE:

`await game.scenes.filter((s) => s.name === "b")[0].tokens.filter((t) => t.name === "npc")[0].actor.updateEmbeddedDocuments("ActiveEffect", [ {_id: myAE, disabled: true }])`

This works as expected.  Now try to enable the AE:

`await game.scenes.filter((s) => s.name === "b")[0].tokens.filter((t) => t.name === "npc")[0].actor.updateEmbeddedDocuments("ActiveEffect", [ {_id: myAE, disabled: false }])`

Results in the traceback:
foundry.js:16255 Uncaught TypeError: Cannot read properties of null (reading 'visible')
    at ActiveEffect5e._displayScrollingStatus (foundry.js:16254:15)
    at ActiveEffect5e._onUpdate (foundry.js:16213:12)
    at TokenDocument5e._onUpdateTokenActor (foundry.js:22482:17)
    at TokenDocument5e._onUpdate (foundry.js:22369:12)
    at ClientDatabaseBackend.callback (foundry.js:12823:11)
    at foundry.js:12804:43
    at Array.map (<anonymous>)
    at ClientDatabaseBackend._handleUpdateEmbeddedDocuments (foundry.js:12804:33)
    at ClientDatabaseBackend._updateEmbeddedDocuments (foundry.js:12672:17)
    at async TokenDocument5e.updateDocuments (commons.js:6153:23)

### What core version are you reporting this for?

Version 10 (build 291)

### Relevant log output

```shell
cpr-logger.js:36 TypeError: Cannot read properties of null (reading 'visible')
    at CPRActiveEffect._displayScrollingStatus (foundry.js:16254:15)
    at CPRActiveEffect._onUpdate (foundry.js:16213:12)
    at TokenDocument._onUpdateTokenActor (foundry.js:22482:17)
    at TokenDocument._onUpdate (foundry.js:22369:12)
    at ClientDatabaseBackend.callback (foundry.js:12823:11)
    at foundry.js:12804:43
    at Array.map (<anonymous>)
    at ClientDatabaseBackend._handleUpdateEmbeddedDocuments (foundry.js:12804:33)
    at ClientDatabaseBackend._updateEmbeddedDocuments (foundry.js:12672:17)
    at async TokenDocument.updateDocuments (commons.js:6153:23)
    at async TokenDocument.update (commons.js:6250:23)
    at async TokenDocument.updateActorEmbeddedDocuments (foundry.js:22208:5)
    at async ImprovedDialogMigration.migrateActor (008-improvedDialogs.js:119:7)
    at async cpr-migration.js:309:16
    at async Promise.allSettled (index 47)
    at async ImprovedDialogMigration.migrateScene (cpr-migration.js:317:20)
    at async cpr-migration.js:268:16
    at async Promise.allSettled (index 4)
    at async ImprovedDialogMigration.migrateScenes (cpr-migration.js:276:20)
    at async ImprovedDialogMigration.run (cpr-migration.js:90:11)
    at async MigrationRunner.runMigrations (migration.js:62:24)
    at async MigrationRunner.migrateWorld (migration.js:39:9)
    at async Object.fn (cpr.js:147:24)
```

### Bug Checklist

- [ ] The issue occurs while all Modules are disabled

**Comment by Fyorl** [comment] 2023-05-22 19:27
Duplicate of #9351

**Closed by Fyorl** 2023-05-22 19:27 UTC
Labels: bug, tokens
