### ISSUE TITLE
[Bug] Module dialog offers to deactivate dependencies needed by other modules

### ISSUE THREAD

**Issue by this-gavagai** [foundryvtt/foundryvtt#10378] opened 2024-02-01 04:12 UTC
### What happened?

When deactivating a module, Foundry offers to also deactivate dependencies. This is helpful behavior, but the problem is that Foundry will deactivate dependencies needed by other modules. This can lead to unexpected misbehavior.

### What ways of accessing Foundry can you encounter this issue in?

- [X] Native App (Electron)
- [X] Chrome
- [ ] Firefox
- [ ] Safari
- [ ] Other

### Reproduction Steps

1) Install and activate two modules with a shared dependency (libwrapper is a good candidate because it's used by so much).
2) Deactivate one of the two modules.
3) Prompt arises to deactivate the common dependency, even though it's still needed for the other module that remains active

### What core version are you reporting this for?

11.315

### Bug Checklist

- [ ] The issue occurs while all Modules are disabled

**Comment by aaclayton** [comment] 2024-02-02 14:26
I think this is a duplicate issue, but don't have time to search for the original at the moment. Reminder to re-connect them later.

**Comment by Fyorl** [comment] 2024-05-21 12:22
Duplicate of #10010

**Closed by Fyorl** 2024-05-21 12:22 UTC
Labels: bug, packages
