### ISSUE TITLE
Buttons end up in the `FormDataExtended` object

### ISSUE THREAD

**Issue by dev7355608** [foundryvtt/foundryvtt#7952] opened 2022-08-26 23:16 UTC
### What happened?

Buttons end up in the `FormDataExtended` object.

### What ways of accessing Foundry can you encounter this issue in?

- [X] Native App (Electron)
- [ ] Chrome
- [ ] Firefox
- [ ] Safari
- [ ] Other

### Reproduction Steps

```js
let form = document.createElement("form");
form.innerHTML = `
    <button type="button" name="foo">Click me</button>
`;
new FormDataExtended(form).object // => {foo: ''}
```

### What core version are you reporting this for?

Version 10 Testing 5 (build 279)

### Bug Checklist

- [X] The issue occurs while all Modules are disabled

**Comment by aaclayton** [comment] 2022-08-26 23:51
Duplicate of https://github.com/foundryvtt/foundryvtt/issues/7938

**Closed by aaclayton** 2022-08-26 23:51 UTC
Labels: bug, api
