### ISSUE TITLE
Tokens sometimes rebound away from walls

### ISSUE THREAD

**Issue by Fyorl** [foundryvtt/foundryvtt#6744] opened 2022-02-24 12:06 UTC
Originally in GitLab by @Fyorl

Originally reported by ParryDuckKill#9291 https://discord.com/channels/170995199584108546/872553750877835264/941852912315953185

**ALL MODULES DISABLED?** true  
**OS, Hosting, Browser (if applicable):** Windows 10, Forge, Chrome  
**Short Description of bug:** When moving a token into a field adjacent to a field containing a wall, the token will sometimes rebound away from the intended field about halfway into the space opposite that field. This seems to occur when pressing the directional keys more times than is needed to move the token into that square.  
**Simple steps to reproduce the bug:** Move a token into a space containing a wall in either of the sample scenes provided using more keystrokes on the directional keys than is required. User Phoenix was able to reproduce this bug.  
**Screenshots and/or console errors:**

Video of the bug: https://cdn.discordapp.com/attachments/872553750877835264/941853205728473128/70939873-4db8-4255-9d75-8a15f367f597.mp4

Scenes attached.

![image](https://gitlab.com/foundrynet/foundryvtt/uploads/0f4fe5489f4dc8d3696b6b67a1451fa7/fvtt-Scene-grimskalle-entrance-2_1.json)

![image](https://gitlab.com/foundrynet/foundryvtt/uploads/4552488a866aca90efdcdeb839701ff1/fvtt-Scene-karkolohk.json)

**Comment by Norc** [comment] 2024-10-04 12:56
Very old bug that I haven't seen recently and couldn't reproduce quickly, closing.

**Closed** 2024-10-04 13:04 UTC
Labels: bug, nonrepro, tokens, canvas
