### ISSUE TITLE
Chaining creating wall segments stops working after undo-ing a wall

### ISSUE THREAD

**Issue by strongpauly** [foundryvtt/foundryvtt#11453] opened 2024-07-13 14:22 UTC
### What happened?

Chaining walls by holding the <kbd>command ⌘</kbd> key stops working after a while.  It appears to be caused by undoing a segment by pressing <kbd>command ⌘</kbd> + <kbd>Z</kbd>.

Seen in both D&D 5e and Pathfinder systems with all modules disabled.

### What ways of accessing Foundry can you encounter this issue in?

- [X] Native App (Electron)
- [ ] Chrome
- [ ] Firefox
- [ ] Safari
- [ ] Other

### Reproduction Steps

1. Fire up a world inside local foundry (on a Mac if that makes any difference).
2. Create a wall.
3. <kbd>command ⌘</kbd> + Click on the end of a wall, which will create a new wall starting from the end of that wall.
4. Repeat step 3 multiple times without issue.
5. Press <kbd>command ⌘</kbd> + <kbd>Z</kbd> to undo the last segment.
6. Attempt step 3 again only to see that the behaviour now is to move the existing segment - i.e. what would have happened if the <kbd>command ⌘</kbd> wasn't pressed.

Refreshing Foundry restores the original behaviour.  Swapping scenes does not.

### What core version are you reporting this for?

Version 12 Stable (Build 328)

### Bug Checklist

- [X] The issue occurs while all Modules are disabled

**Comment by unsoluble** [comment] 2024-07-13 17:36
This is a great catch, and probably explains a number of random reports we've seen about wall chaining failing to work seemingly at random.

Additional note: It's not just Command-Z that breaks this, but any Command combo (so, ⌘-C or ⌘-V as well).

**Comment by dev7355608** [comment] 2024-07-16 10:57
I wasn't able to reproduce this bug as described. But I discovered a bug that made wall chaining stop working (#11463), but it isn't caused by CTRL+Z.

**Comment by unsoluble** [comment] 2024-07-16 15:03
Worth noting that this is probably exclusive to the Command metakey on macOS.

**Comment by aaclayton** [comment] 2024-10-28 14:27
Closing as nonrepro.

**Closed by aaclayton** 2024-10-28 14:27 UTC
Labels: bug, nonrepro, ux, walls

**Comment by aaclayton** [comment] 2024-10-28 14:47
> For what it's worth, I can still repro this in 13.332, albeit with less reliability — instead of happening 100% of the time after a Command-key combo, it happens about 50% of the time.

Is there any specific repro step here other than just "make walls"?

**Comment by unsoluble** [comment] 2024-10-28 14:49
Yep, that's all there is to it.
