### ISSUE TITLE
Token size scaling differs between prototype token and a regular token

### ISSUE THREAD

**Issue by Fyorl** [foundryvtt/foundryvtt#8539] opened 2022-11-18 13:03 UTC
Originally reported by Capsom#5617 https://discord.com/channels/170995199584108546/956306859491471420/1041790456004096030

**All Modules Disabled** - True  
**OS** - Windows 10, Hosting - Self  
**Description** - Token size scaling is different between Prototype Token and Regular Token.  
**Repro Steps** - In Appearance Menu change Dimensions to 0.5 on a token in your scene then update the Token. Then do the same for the Prototype Token and pull out a new token. They will be different sizes.

**Comment by Feu-Secret** [comment] 2022-11-21 19:34
Can't reproduce this issue in my environment. Need a second opinion.

**Comment by Feu-Secret** [comment] 2022-11-21 19:57
Closing this issue. Non reproduced in the team too.

**Closed by Feu-Secret** 2022-11-21 19:57 UTC
Labels: bug, nonrepro, tokens, canvas
