### ISSUE TITLE
Changing the Name of an Actor Doesn't Update The DocumentSheet Title

### ISSUE THREAD

**Issue by Alkali-Metal** [foundryvtt/foundryvtt#11955] opened 2024-12-21 21:23 UTC
### What happened?

**Note: This was only tested with Actor documents, other documents may also be affected**

When updating the name of an Actor document via sheet or API causes the sidebar and sheet to get re-rendered, however the title of the sheet doesn't update and still shows the old name of the actor.

### What ways of accessing Foundry can you encounter this issue in?

- [ ] Native App (Electron)
- [X] Chrome
- [ ] Firefox
- [ ] Safari
- [ ] Other

## Sheet
1. Create an Actor
2. Open it's sheet
3. Note the title of the sheet application
4. Edit the actor's name via the sheet input for whatever system you're in
5. Note the title of the sheet application is still the old name

## API
1. Create an Actor
2. Open it's sheet
3. Note the title of the sheet application
4. Edit the actor's name via an API call
5. Note the title of the sheet application is still the old name

### What core version are you reporting this for?

Version 13 Development 1 (Build 334)

### Relevant log output

```shell
Foundry Virtual Tabletop: Version 13 Development 1, 13.334
Game System: ripcrypt, 0.0.1
Active Modules: 0
Performance Mode: 2

OS: Linux 6.8.0 x86 (64-bit)
Client: Chromium/130.0.6723.172
GPU: ANGLE (AMD, AMD Radeon RX 6600 XT (navi23 LLVM 15.0.7), OpenGL 4.6)
Max Texture Size: 16384

Scene: 3840 x 1920 | Grid Size: 100 | Padding Percentage: 0
Walls: 0 | Ambient Lights: 5 | Ambient Sounds: 0 | Tiles: 1 | Tokens: 0
Largest Texture: 3840 x 1920

Actors: 1 | Items: 0 | Journal Entries: 0 | Rollable Tables: 0 |
Playlists: 0 | Compendium Packs: 0 | Chat Messages: 92

World Scripts: None
```

### Bug Checklist

- [X] The issue occurs while all Modules are disabled

**Comment by stwlam** [comment] 2024-12-22 22:32
Duplicate of #11761

**Closed by stwlam** 2024-12-22 22:32 UTC
Labels: bug, duplicate, todelete
