### ISSUE TITLE
Directory Folder context menus immediately collapse

### ISSUE THREAD

**Issue by kristianserrano** [foundryvtt/foundryvtt#9439] opened 2023-05-22 15:30 UTC
### What happened?

Right-clicking Directory Folders to pull up the context menu results in the context menu immediately collapsing, making it impossible to interact with the menu.

### What ways of accessing Foundry can you encounter this issue in?

- [ ] Native App (Electron)
- [X] Chrome
- [ ] Firefox
- [ ] Safari
- [ ] Other

### Reproduction Steps

1. Create a Directory Folder.
2. Right-click the Directory Folder.
3. Feel an overwhelming sadness because you can't interact with your beloved folder. It sits there, so close, yet so far away. You seek to gaze into its inner beauty, but alas you cannot.

### What core version are you reporting this for?

Version 11 Testing 3 (298)

### Bug Checklist

- [ ] The issue occurs while all Modules are disabled

**Comment by Fyorl** [comment] 2023-05-22 16:03
Duplicate of #9427

**Closed by Fyorl** 2023-05-22 16:03 UTC
Labels: bug
