### ISSUE TITLE
Modules that define a dependency without specifying the type of it do not appear in the installed module list

### ISSUE THREAD

**Issue by dev7355608** [foundryvtt/foundryvtt#7355] opened 2022-06-20 18:22 UTC
### Environment Details

* Foundry VTT Version: 10.270

### Issue Description

Doesn't matter whether it's old or new style. If the `type` of the dependency is missing, the module is not loaded.

```json
    "dependencies": [
        {
            "name": "lib-wrapper"
        }
    ],
```

```json
  "relationships": {
    "requires": [
      {
        "id": "lib-wrapper"
      }
    ]
  },
```

**Comment by aaclayton** [comment] 2022-06-20 18:58
Resolved by (and duplicate of) https://github.com/foundryvtt/foundryvtt/issues/7302

**Closed by aaclayton** 2022-06-20 18:58 UTC
Labels: bug
