### ISSUE TITLE
Rebuilding a v11 Adventure in v12 misses some content or marks it as removed

### ISSUE THREAD

**Issue by Fyorl** [foundryvtt/foundryvtt#11054] opened 2024-05-28 14:33 UTC
Originally reported by claytonthomson https://discord.com/channels/170995199584108546/1184176415139184731/1243255584627621958

**ALL MODULES DISABLED?**  true 
**OS, Hosting, Browser (if applicable)**: MacOS (14.5 (23F79)), Chrome (124.0.6367.210 ), Host: local for v11 and FoundryServer for v12.
**Short Description of bug**: Content stripped out or hidden in v12 adventure installer when the content is available and displays in v11 adventure installer (content was developed on latest version of v11 and latest two versions of the 5e system).  Also, when you open the installer to rebuild, there is content automatically shaded to be deleted (orange color) when no content was selected to be deleted.
**Simple steps to reproduce the bug**: Install module in v11 and v12 (this is unreleased content at the time of this writing; I can provide the developer a link to the module if assigned).  There were no console errors.
**Screenshots and/or console errors**:

![image](https://github.com/foundryvtt/foundryvtt/assets/207433/ea1fe768-a757-4f5c-ae5c-7248363da47f)

![image](https://github.com/foundryvtt/foundryvtt/assets/207433/505e94d4-c97d-4b82-8059-9c587cfb2678)

![image](https://github.com/foundryvtt/foundryvtt/assets/207433/416eceb8-07ed-4871-8dcb-d8034daaa14c)

**Comment by secondworldpublishing** [comment] 2024-06-07 00:32
It is possible that I've identified the root cause of the issue I reported. The affected maps were originally built in v10 and migrated fine to v11 (the majority of the maps were built from scratch and were unaffected). It appears that the affected maps did not migrate from v11 to v12. 

I resolved the issue by rebuilding the maps from scratch in v11 (which is what is currently installed on my local).  I tested installing the maps on two of my remote servers, and they appear in the Adventure pack and install fine in v11 and v12.

Earlier today, I provided Matt with the URL to the module in case you need it.  He reported to me that he had replicated the issue.

**Comment by aaclayton** [comment] 2024-10-28 14:26
Closing as nonrepro.

**Closed by aaclayton** 2024-10-28 14:26 UTC
Labels: bug, nonrepro, api
