### ISSUE TITLE
Allow readonly form fields to be passed to form data in FormApplication

### ISSUE THREAD

**Issue by Rughalt** [foundryvtt/foundryvtt#8348] opened 2022-10-09 19:17 UTC
### User Experience

As of V10, `readonly` form fields are not processed by `FormDataExtended` processor. While this is probably a good thing for the most part, some UI elements may use `readonly` inputs in conjunction with other control elements. It would be great if `readonly` fields could be processed and passed to the rest of the flow.

To not break existing V10 code, determining if read-only element should be passed could be determined by an additional attribute on the element.

**Comment by aaclayton** [comment] 2023-02-10 13:39
Duplicate of #8879

**Closed by aaclayton** 2023-02-10 13:39 UTC
Labels: api
