### ISSUE TITLE
Journals - PDF page type fails to render for editing

### ISSUE THREAD

**Issue by anathemamask** [foundryvtt/foundryvtt#7953] opened 2022-08-26 23:59 UTC
Steps to reproduce:
- Create a journal entry
- Create a pdf page 

Receive error:
```js
TypeError: An error occurred while rendering JournalPDFPageSheet 51. Cannot read properties of null (reading 'replace')
    at Object.getRoute (commons.js:1611:17)
    at JournalPDFPageSheet._getViewerParams (foundry.js:62651:82)
    at JournalPDFPageSheet.getData (foundry.js:62603:20)
    at JournalPDFPageSheet._render (foundry.js:4952:29)
    at JournalPDFPageSheet._render (foundry.js:5677:17)
    at JournalPDFPageSheet.render (foundry.js:4911:10)
    at JournalPDFPageSheet.render (foundry.js:6247:18)
    at Object.callback (foundry.js:63586:42)
    at #onClickItem (foundry.js:54575:11)
    at HTMLElement.dispatch (jquery.min.js:2:43064)
onError @ foundry.js:711
(anonymous) @ foundry.js:4913
Promise.catch (async)
render @ foundry.js:4911
render @ foundry.js:6247
callback @ foundry.js:63586
#onClickItem @ foundry.js:54575
dispatch @ jquery.min.js:2
v.handle @ jquery.min.js:2
```

**Comment by aaclayton** [comment] 2022-08-27 00:24
Duplicate of #7927 which Kim has fixed.

**Closed by aaclayton** 2022-08-27 00:24 UTC
Labels: bug, journal
