### ISSUE TITLE
Setup shows a compatibility warning although the version in concern is the actual foundy version

### ISSUE THREAD

**Issue by gizmo2342** [foundryvtt/foundryvtt#8552] opened 2022-11-24 16:50 UTC
### What happened?

When sidegrading a system/module that shows a compatibility warning, the warning will still be shown after the update, even if the verified version is the current foundry version. The warning disappears when foundry is restarted.

![grafik](https://user-images.githubusercontent.com/64664847/203834594-d76630d1-a7db-4e21-ba64-319f1f3e03df.png)

### What ways of accessing Foundry can you encounter this issue in?

- [X] Native App (Electron)
- [ ] Chrome
- [ ] Firefox
- [ ] Safari
- [ ] Other

### Reproduction Steps

see above

### What core version are you reporting this for?

Version 10 (build 290)

### Bug Checklist

- [X] The issue occurs while all Modules are disabled

**Comment by Fyorl** [comment] 2022-11-24 19:39
Duplicate of #8251

**Closed by Fyorl** 2022-11-24 19:39 UTC
Labels: bug
