### ISSUE TITLE
Editing a Module through the new Interface in Foundry messes up some pack properties in the module.json

### ISSUE THREAD

**Issue by Allalinor** [foundryvtt/foundryvtt#9707] opened 2023-06-29 20:59 UTC
### What happened?

When clicking on Edit module in Foundry, then just clicking the Edit Module button in the window that pops up to close it. (Not even doing anything) It removed some lines from my packs in my module.json. (see attached images for a before and after)
![Before](https://github.com/foundryvtt/foundryvtt/assets/7441153/13e6d0a7-cb25-4666-9075-a70fe9cda133)
![After](https://github.com/foundryvtt/foundryvtt/assets/7441153/a723f40b-f57d-4e03-84ce-a87d9b647b99)

### What ways of accessing Foundry can you encounter this issue in?

- [X] Native App (Electron)
- [X] Chrome
- [ ] Firefox
- [ ] Safari
- [ ] Other

### Reproduction Steps

1. Make/Get a module.json with some packs.
2. Open up Foundry
3. Right-click on the module and click Edit Module
4. Close the window that opened by clicking Edit Module

### What core version are you reporting this for?

Version 11 Build 304

### Bug Checklist

- [ ] The issue occurs while all Modules are disabled

**Comment by aaclayton** [comment] 2023-06-30 13:03
Duplicate of (or at least closely related to) #9559, merging this issue in with that one.

**Closed by aaclayton** 2023-06-30 13:03 UTC
Labels: bug
