### ISSUE TITLE
Allow set to be passed to `SetField` during update

### ISSUE THREAD

**Issue by arbron** [foundryvtt/foundryvtt#7910] opened 2022-08-23 22:15 UTC
### User Experience

Currently in order to perform an update to a set defined as a `SetField` in a `DataModel` it must first be converted to an array:

```javascript
const itemSet = this.document.system.items;
itemSet.add(item.uuid);
this.document.update({"system.items": Array.from(itemSet)});
```

It would be convenient if a set could be passed in:

```javascript
const itemSet = this.document.system.items;
itemSet.add(item.uuid);
this.document.update({"system.items": itemSet});
```

**Comment by Fyorl** [comment] 2022-08-24 10:53
Duplicate of #7706

**Closed by Fyorl** 2022-08-24 10:53 UTC
Labels: api, data-models
