### ISSUE TITLE
Set custom default render options for an Application

### ISSUE THREAD

**Issue by arcanistzed** [foundryvtt/foundryvtt#7835] opened 2022-08-17 04:11 UTC
### User Experience

One way this could be implemented would be to use certain core flags as render options if available. Alternatively, new `preRender` hooks could allow the render options to be modified before they are applied.

Currently it's very difficult to always have a document render with certain default options, since there is no way to reliably call the render method inside it's hook but with different parameters.

**Comment by aaclayton** [comment] 2022-08-17 14:37
Can you expand your report with an example use case that helps explain what you want to do and what degree of control you want to exert over the rendering flow?

**Comment by theripper93** [comment] 2022-08-17 14:49
i do agree, it would be nice to have a preRender hook where we can inject into the Handlebars template before it's compiled as well, so we could get the automatic hooking of filepickers, color inputs etc...

**Comment by arcanistzed** [comment] 2022-08-17 15:42
theripper93's idea is really good. This use case that prompted me to send the report is to have the option to configure my journals so that they always render with `{ mode: JournalSheet.VIEW_MODES.MULTIPLE, collapsed: true }`.

**Comment by aaclayton** [comment] 2024-02-20 02:50
Closing as duplicate of https://github.com/foundryvtt/foundryvtt/issues/3998

**Closed by aaclayton** 2024-02-20 02:50 UTC
Labels: ui, api
