### ISSUE TITLE
Attempting to edit using TinyMCE sheet for journals fails with error

### ISSUE THREAD

**Issue by anathemamask** [foundryvtt/foundryvtt#9121] opened 2023-03-27 17:20 UTC
From `@cswendrowski#9701`
```
Uncaught (in promise) TypeError: e.split is not a function
    NA tinymce.min.js:4
    BA tinymce.min.js:4
    BA tinymce.min.js:4
    r tinymce.min.js:4
    RO tinymce.min.js:4
    s tinymce.min.js:4
    s tinymce.min.js:4
    Re tinymce.min.js:4
    s tinymce.min.js:4
    executeHandlers tinymce.min.js:4
    i tinymce.min.js:4
    ha tinymce.min.js:4
    bind tinymce.min.js:4
    V tinymce.min.js:4
    init tinymce.min.js:4
    _createTinyMCE foundry.js:62256
    create foundry.js:62200
    activateEditor foundry.js:6589
    activateEditor foundry.js:6928
    activate foundry.js:6682
    _activateEditor foundry.js:6684
    activateListeners foundry.js:6411
    jQuery 2
    activateListeners foundry.js:6411
    activateListeners item-sheet.js:167
```

**Comment by Fyorl** [comment] 2023-04-18 19:56
Duplicate of #9078

**Closed by Fyorl** 2023-04-18 19:56 UTC
Labels: bug, text-editor
