### ISSUE TITLE
Creating a world with unset packfolder colors errors on startup

### ISSUE THREAD

**Issue by CarlosFdez** [foundryvtt/foundryvtt#10802] opened 2024-04-30 09:30 UTC
### What happened?

If you create a world for a system that have packfolders but without setting colors in system.json, the world does not start.

### What ways of accessing Foundry can you encounter this issue in?

- [X] Native App (Electron)
- [ ] Chrome
- [ ] Firefox
- [ ] Safari
- [ ] Other

### Reproduction Steps

In PF2e during development, the world initially didn't start (server version 12.319). I added color props to all pack folders and nested folders (after digging through bug reports in the discord) and that allowed us to start. I tested removing them and creating a new world (not an existing world) and the errors is still there.

From the user side, this is all you see:
![image](https://github.com/foundryvtt/foundryvtt/assets/1286721/61dc8635-cfea-401a-ab7f-fa0dd272df00)

### What core version are you reporting this for?

12.310

### Relevant log output

The server side (I'm running with the NodeJS version for v12) has a more interesting error message.

```shell
FoundryVTT | 2024-04-30 05:26:09 | [error] Cannot read properties of null (reading 'css')
TypeError: Cannot read properties of null (reading 'css')
    at n (file:///E:/FoundryVTT-12.320/resources/app/dist/packages/world.mjs:1:6549)
    at #i (file:///E:/FoundryVTT-12.320/resources/app/dist/packages/world.mjs:1:6930)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async #s (file:///E:/FoundryVTT-12.320/resources/app/dist/packages/world.mjs:1:5920)
    at async World.updateActivePacks (file:///E:/FoundryVTT-12.320/resources/app/dist/packages/world.mjs:1:5459)
    at async World.setup (file:///E:/FoundryVTT-12.320/resources/app/dist/packages/world.mjs:1:9773)
```

### Bug Checklist

- [X] The issue occurs while all Modules are disabled

**Comment by aaclayton** [comment] 2024-04-30 13:10
Closing as duplicate of https://github.com/foundryvtt/foundryvtt/issues/10545

**Closed by aaclayton** 2024-04-30 13:10 UTC
Labels: bug

**Comment by CarlosFdez** [comment] 2024-04-30 23:16
Whoops, I checked, but I couldn't find it. Turns out its a bit old, muhbad.
