### ISSUE TITLE
MeasuredTemplate#center returns the top-left corner of rectangular templates

### ISSUE THREAD

**Issue by Fyorl** [foundryvtt/foundryvtt#10055] opened 2023-10-02 16:16 UTC
Originally reported by manaflower https://discord.com/channels/170995199584108546/1065764070680186930/1156013160856293466

**ALL MODULES DISABLED?** true
**OS, Hosting, Browser (if applicable)**: any
**Short Description of bug**: MeasuredTemplate#center returns top-left corner for rectangle templates.
**Simple steps to reproduce the bug**:
Compare template.x/y against template.center of a rectangle template.

**Comment by Fyorl** [comment] 2023-10-02 16:18
I believe this is just a quirk of how rectangular measured templates are implemented, but probably technically a bug given the definition of the `center` getter.

**Comment by aaclayton** [comment] 2024-05-20 13:14
Closing as `wontfix` since this is "working as intended". The measured template system is likely to be revisited in V13.

**Closed by aaclayton** 2024-05-20 13:14 UTC
Labels: bug, templates, canvas
