### ISSUE TITLE
Add per-world client-scoped setting

### ISSUE THREAD

**Issue by mkahvi** [foundryvtt/foundryvtt#9488] opened 2023-05-29 08:53 UTC
### User Experience

Simple setting category for client scoped settings that affect only specific world.

Although many client scoped settings are nice to carry over between worlds, there are some that are just an utter nuisance when they do so. For example roll mode setting being carried over between a game I GM for and a game I am player in on the same server is just annoying when as GM I keep the roll mode usually as self roll, but as player I need to keep it usually public roll but never self roll.

This would also help with system and module settings that are world-specific but not world scoped settings as Foundry understands them. For example if I play a setting agnostic game on the same server, one campaign is scifi and the other fantasy, using the same client settings easily is simply utter garbage.

Lacking this kind of setting encourages instead using flags on the users to store such settings, which is not great when they have no purpose being shared to all users.

Simple solution would be to add world ID to the game setting, either on my end or on Foundry's end. The latter would be preferable to have uniform syntax and intent, and make API access of it much simpler for everyone.

**Comment by aaclayton** [comment] 2024-06-15 15:54
Closing as duplicate of https://github.com/foundryvtt/foundryvtt/issues/4804

**Closed by aaclayton** 2024-06-15 15:54 UTC
Labels: api
