### ISSUE TITLE
Integrate Babele feature inside Foundry core

### ISSUE THREAD

**Issue by LeRatierBretonnien** [foundryvtt/foundryvtt#10115] opened 2023-10-19 10:57 UTC
### User Experience

Since many years now, translation of systems and modules compendiums are delegated to the "Babele" module.

On the French developers side, we think that this localization feature shall be now handled and managed inside Foundry , instead of relying on an external module. 
Localization capability of Foundry is one of its key success in non-English speaking countries, and - from our opinion - it is time to integrate it into the core.

This ticket is here to register our request, and to discuss it, of course :)

**Comment by Vlyan26** [comment] 2023-10-19 11:06
We really need this ;)

**Comment by manfred7168** [comment] 2023-10-19 16:57
It's about time!

**Comment by deurk** [comment] 2023-10-19 17:44
Can software really still be built without translation support built-in nowadays?

**Comment by VincentVk9373** [comment] 2023-10-19 18:09
Bonus: even if this is for a "minority", it is good important for inclusion of all people

**Comment by Mandaar** [comment] 2023-10-19 18:29
Nowadays, the ability to play in your native language is a real selling point. Given that it's impossible to have all the languages, allowing everyone to do their own translation seems to me an excellent compromise.

**Comment by aaclayton** [comment] 2023-10-19 19:59
Closing as duplicate of #7283 and copying over comments.

**Closed by aaclayton** 2023-10-19 19:59 UTC
