### ISSUE TITLE
resizing rotated tile will preview the tile with 0 rotation

### ISSUE THREAD

**Issue by its-grape-juice** [foundryvtt/foundryvtt#8395] opened 2022-10-17 16:06 UTC
### What happened?

trying to resize a rotated a tile, will reset the tile's graphic to 0 rotation while dragging the resize controller

### What ways of accessing Foundry can you encounter this issue in?

- [ ] Native App (Electron)
- [X] Chrome
- [ ] Firefox
- [ ] Safari
- [ ] Other

### Reproduction Steps

drop a tile, rotate 45 degrees, start resizing. 

### What core version are you reporting this for?

V10.287

### Bug Checklist

- [X] The issue occurs while all Modules are disabled

**Comment by Fyorl** [comment] 2022-10-17 16:15
Duplicate of #6373

**Closed by Fyorl** 2022-10-17 16:15 UTC
Labels: bug
