### ISSUE TITLE
Changing Journal Entry 'Configure Ownership' generates 'Model Validation Errors'

### ISSUE THREAD

**Issue by buttonpushertv** [foundryvtt/foundryvtt#7951] opened 2022-08-26 19:38 UTC
### What happened?

Attempting to Change Ownership settings on a Journal Entry causes a `Model Validation Error`.

Usage Case: Trying to give Players Limited or Observer ownership on a Journal Entry produces the error shown below and does not change the ownership values.

This error occurs if you change either the "All Players" or a specific player to any of the options.

### What ways of accessing Foundry can you encounter this issue in?

- [ ] Native App (Electron)
- [X] Chrome
- [ ] Firefox
- [ ] Safari
- [ ] Other

### Reproduction Steps

1. Create Journal Entry
2. Close the new entry or leave it open
3. Right click new entry title in Journal Section on right sidebar, select Change Ownership
4. Attempt to Change Ownership values on the new entry and save them
5. Witness the error

### What core version are you reporting this for?

Version 10 Testing 5 (build 279)

### Relevant log output

```shell
foundry.js:711 Error: JournalEntry [zTjiylUMEiuVV3RU] Model Validation Errors
[JournalEntry.ownership]: is not a mapping of user IDs and document permission levels
    at SchemaField._validateType (commons.js:3623:15)
    at SchemaField.validate (commons.js:3350:37)
    at JournalEntry.validate (commons.js:4987:35)
    at ClientDatabaseBackend._preUpdateDocumentArray (foundry.js:12562:13)
    at ClientDatabaseBackend._updateDocuments (foundry.js:12478:33)
    at ClientDatabaseBackend.update (commons.js:6273:24)
    at async JournalEntry.updateDocuments (commons.js:5628:23)
    at async JournalEntry.update (commons.js:5725:23)
```

### Bug Checklist

- [X] The issue occurs while all Modules are disabled

**Comment by aaclayton** [comment] 2022-08-26 19:41
Duplicate of https://github.com/foundryvtt/foundryvtt/issues/7925

**Closed by aaclayton** 2022-08-26 19:41 UTC
Labels: bug

**Comment by buttonpushertv** [comment] 2022-08-26 19:43
Shoot. Sorry. Thought it was a Journal only thing.
