### ISSUE TITLE
Closing a Token's Settings erases its PIXI.Text._texture

### ISSUE THREAD

**Issue by mclemente** [foundryvtt/foundryvtt#8079] opened 2022-09-04 16:48 UTC
### What happened?

Closing the token settings will nullify `PIXI.Sprite._texture` from a PIXI.Text, which will remove the Text from the token and cause `PIXI.Sprite.destroy()` to throw an error.

### What ways of accessing Foundry can you encounter this issue in?

- [X] Native App (Electron)
- [ ] Chrome
- [ ] Firefox
- [ ] Safari
- [ ] Other

### Reproduction Steps

1) Select a token on the canvas
2) On the Console, enter `_token.test = _token.addChild(new PIXI.Text("Test", {fontSize: "12px"}));` A "Test" text will show up on the top left corner of the token.
3) Enter `_token.test._texture`. 
4) Open and Close the Token settings. The "Test" text will disappear and `_token.test._texture` will be null.
5) `_token.test.destroy()` will throw an error because _texture is null https://github.com/pixijs/pixijs/blob/dev/packages/sprite/src/Sprite.ts#L470

### What core version are you reporting this for?

Version 10 (build 284)

### Relevant log output

```shell
Uncaught TypeError: Cannot read properties of null (reading 'off')
    at r.destroy (sprite.min.mjs:8:4223)
    at r.destroy (text.min.mjs:8:17807)
    at <anonymous>:1:13
r.destroy	@	sprite.min.mjs:8
r.destroy	@	text.min.mjs:8
(anonymous)	@	VM5361:1
```

### Bug Checklist

- [X] The issue occurs while all Modules are disabled

**Comment by Fyorl** [comment] 2022-09-14 14:24
I was able to reproduce this but it required changing some value in the token config in order to trigger the preview workflow. Since the entire `_getSubmitData` is sent as part of the preview, this always triggers a full token `draw`, which calls `clear`, which removes the child text object and destroys its texture, so this might be related to #8078.

It's possible to adapt the token preview workflow to only trigger a `draw` when necessary, but `draw`s are sometimes required and it's unclear whether we intend for children added in this ad-hoc way to be able to survive a `draw`.

**Comment by mclemente** [comment] 2022-09-14 19:36
Personally, I don't mind it because I can just check for `PIXI.Sprite._texture` instead of just `PIXI.Sprite` to call `destroy`. It's just that this was unexpected behavior, as I never expected `closeTokenConfig` hook would break an interaction with a PIXI.Sprite.

**Comment by Fyorl** [comment] 2022-09-20 16:24
Yeah, that's fair enough. It's less that it's the `closeTokenConfig`, and more that any `Token#draw` call will destroy children, so they need to be added in a way that allows them to be re-drawn when appropriate, rather than being ad-hoc attached to the actor. Closing this as wontfix then for now.

**Closed by Fyorl** 2022-09-20 16:24 UTC
Labels: bug, api
