### ISSUE TITLE
Dragging a hotbar macro and dropping it outside the hotbar no longer removes that macro from the bar as it did in V9.

### ISSUE THREAD

**Issue by cswendrowski** [foundryvtt/foundryvtt#8185] opened 2022-09-12 16:06 UTC
From https://discord.com/channels/170995199584108546/956306859491471420/1018642666843553832

Simple steps to reproduce the bug: Place an icon on the hotbar, change icon on the sheet, the new icon art doesn't update even if you redrag on top of it, until you Right click -> Delete macro. In Version 9, you could drag to delete, but not anymore. Doing so will instead bug it out, where it disappears and you have to redrag it to the hotbar, then delete manually before getting the new icon.

![](https://i.imgur.com/WUD9QdB.png)

**Comment by Fyorl** [comment] 2022-09-16 14:42
I'm not able to reproduce this. It seems to be working as expected with regards to dragging off the hotbar. The report seems focused on the macro icon but it's not clear what behaviour they're expecting here.

**Comment by Fyorl** [comment] 2022-09-20 16:22
Closing as nonrepro.

**Closed by Fyorl** 2022-09-20 16:22 UTC
Labels: bug, nonrepro, ux, macros
