### ISSUE TITLE
Certain font glyphs are unsupported in the default font

### ISSUE THREAD

**Issue by Peach774** [foundryvtt/foundryvtt#10207] opened 2023-11-19 21:34 UTC
### What happened?

![image](https://github.com/foundryvtt/foundryvtt/assets/5171184/6878ec3f-a010-4adf-ae27-e3d8b74fbe7e)
As you can see here, the ǎ and ǒ in Liǎngzhǒng are not supported properly and are the wrong font/size for some reason.

### What ways of accessing Foundry can you encounter this issue in?

- [X] Native App (Electron)
- [ ] Chrome
- [ ] Firefox
- [ ] Safari
- [ ] Other

### Reproduction Steps

Type in or copy/paste  ǎ or ǒ into any of the text stuff in foundry

### What core version are you reporting this for?

Version 11 Build 315

### Bug Checklist

- [X] The issue occurs while all Modules are disabled

**Comment by aaclayton** [comment] 2023-11-20 00:54
Closing as duplicate of https://github.com/foundryvtt/foundryvtt/issues/5637

**Closed by aaclayton** 2023-11-20 00:54 UTC
Labels: bug
