### ISSUE TITLE
All drawing text has white stroke

### ISSUE THREAD

**Issue by Fyorl** [foundryvtt/foundryvtt#8277] opened 2022-09-26 11:31 UTC
Originally reported by KingNasher#3050 https://discord.com/channels/170995199584108546/956306859491471420/1022482326556528650

**ALL MODULES DISABLED?** True  
**OS, Hosting, Browser (if applicable):** Windows 11, Hosting on Rasbian (NGINX), All Browsers  
**Short Description of bug:** All drawing texts have a white outline that can't be removed or changed  
**Simple steps to reproduce the bug:** Attempted removing all modules. Verified with different user that issue persists on module free environment. Only happens with Black font. Other color changes do not get the same border  
**Screenshots and/or console errors:**

![image](https://user-images.githubusercontent.com/207433/192265977-2cc52b84-66c9-44e8-9ca9-d3ad04400127.png)

**Comment by aaclayton** [comment] 2022-09-26 13:42
This might be "working as intended". The current design of the software chooses a stroke color adaptively in order to provide contrast with the text. Opportunity to improve for a future version, but probably not a "bug".

**Comment by Fyorl** [comment] 2022-10-20 11:26
I was able to confirm that this is working as intended. Drawings cannot specify a text stroke so the 'adaptive' stroke option from `PreciseText.getTextStyle` is being used. A future improvement could be to add a stroke colour option to drawings.

**Comment by mnoreke** [comment] 2022-11-02 20:05
Suggestion: Add a checkbox to disable the stroke, as well as the ability to pick your own, or use the auto-selected one.

**Comment by Fyorl** [comment] 2022-11-07 12:36
Additional report from @yjeroen claims this is a regression from v9:

![image](https://user-images.githubusercontent.com/207433/200311811-e65b01e7-9114-4155-acd4-1e77642f8339.png)

I was able to verify that adaptive stroke is being used, but it looks like there could be a bug with the adaptive stroke implementation if it now differs from the v9 implementation.

**Comment by aaclayton** [comment] 2022-11-08 20:28
V10 text drawing stroke is adaptively chosen to provide a high amount of contrast against the color of the text to ensure that it stands out against map backgrounds. 

![Image](https://user-images.githubusercontent.com/2468703/200668117-ef2f1509-a951-48be-8c47-fff54933695a.png)

Text which has a lightness greater than `0.6` receives black stroke while text with lightness less than `0.6` receives white stroke. The reason for a change from the V9 behavior here was a correction to a bug which caused black stroke to be used always. See https://github.com/foundryvtt/foundryvtt/issues/7187

We can consider a feature that would make the text stroke color configurable in the future instead of automatically chosen. Closing this issue in favor of #6609 which captures that feature request.

**Closed by aaclayton** 2022-11-08 20:28 UTC
Labels: bug, drawings
