### ISSUE TITLE
Allow Region Event Triggers to fire when any edge of a token enters/exits a region

### ISSUE THREAD

**Issue by gambit07** [foundryvtt/foundryvtt#11251] opened 2024-06-20 13:31 UTC
### User Experience

Currently, regions will only fire an event trigger when a tokens center point crosses the threshold of the region. This causes issues for certain features In systems like 5e where if one square (ie any border of the token) is affected a creature is affected. Assuming there are specific reasons for checking the center of the token, it would be great if there was an option present for regions that allowed checking either the center of the token or the token border in order to trigger events.

**Comment by roth-michael** [comment] 2024-06-20 14:50
Adding on to this: I noticed in the `#triggerTokenMoveEvents` function of the `TokenDocument` class, there's the following line:
```js
const samples = [this.object.getCenterPoint({x: 0, y: 0})];
```
and `samples` is later used to determine which move events, if any, are triggered. My assumption is that it was done this way to allow for further extensibility (e.g. checking centerpoints of _each token-occupied gridspace_ or checking all grid intersections contained within/on the borders of a token). It might be nice to expose a "sample-generating" function that could be overridden by systems depending on their rulesets, with the default remaining whatever you guys think makes the most sense.

**Comment by dev7355608** [comment] 2024-06-24 12:35
Closing as duplicate of #10831.

**Closed by dev7355608** 2024-06-24 12:35 UTC
