### ISSUE TITLE
Token HUD is not re-rendered

### ISSUE THREAD

**Issue by dev7355608** [foundryvtt/foundryvtt#8683] opened 2022-12-29 19:57 UTC
### What happened?

The token HUD (`canvas.tokens.hud`) is not re-rendered in these cases:
- The elevation is changed: `_token.document.update({ elevation: _token.document.elevation + 5 })`.
- The hidden state is toggled: `_token.document.update({ hidden: !_token.document.hidden })`.
- The combat state is toggled: `_token.toggleCombat()`.
- The primary/secondary attribute is changed: `_token.actor.applyDamage(1)` (dnd5e).

Also the name of `Token#refreshHUD` might suggest that it re-renders `canvas.tokens.hud` if bound. Not sure whether it should do that. If not, the documentation should probably mention that it isn't refreshing `canvas.tokens.hud` to avoid potential confusion.

### What ways of accessing Foundry can you encounter this issue in?

- [ ] Native App (Electron)
- [ ] Chrome
- [ ] Firefox
- [ ] Safari
- [ ] Other

### Reproduction Steps

.

### What core version are you reporting this for?

Version 10 Stable 6 (build 291)

### Bug Checklist

- [X] The issue occurs while all Modules are disabled

**Comment by Fyorl** [comment] 2023-04-17 14:09
Seems related/duplicate of #8589

**Closed** 2023-04-20 11:10 UTC
Labels: bug, tokens, ui
