### ISSUE TITLE
allow bulk-updating of ownership/permissions into nested subfolders

### ISSUE THREAD

**Issue by wilcoxon** [foundryvtt/foundryvtt#10167] opened 2023-11-05 20:37 UTC
### User Experience

It would save a ton of time if changing the ownership/permissions of a folder would cascade the updates into nested subfolders.  While trying to figure out how to do so, I found many requests in different places for the same thing.

It is clearly documented that it does NOT update items in subfolders but this is completely counterintuitive and creates tons of extra work with many systems/modules.

If the concern is performance then make it an optional checkbox to cascade the updates (with a warning that it could take some time).

**Comment by unsoluble** [comment] 2023-11-05 21:25
Related to #4318.

**Comment by wilcoxon** [comment] 2023-11-05 21:31
Not a duplicate.  #3807 is asking to persist the permissions to newly added content.  This is simply asking for the one-time update to cascade into subfolders.  Currently, you have to manually update every single folder that has any non-folder contents - this is both counterintuitive (but documented), and time-consuming.

**Comment by unsoluble** [comment] 2023-11-05 21:33
#3807 is an exact duplicate of this request. #4318 is what you're thinking of.

**Comment by aaclayton** [comment] 2023-11-08 14:49
Closing as duplicate of #3807

**Closed by aaclayton** 2023-11-08 14:49 UTC
