### ISSUE TITLE
Desync when any changes happen while loading

### ISSUE THREAD

**Issue by natis1** [foundryvtt/foundryvtt#9639] opened 2023-06-16 21:23 UTC
### What happened?

If, while loading the game, any changes are made by any other players to actors (EG moving them around etc). These changes do not synchronize with your game.

On shotty internet or lowend computers such as mine I've often experienced desyncs from? I don't know exactly. they seem to happen over time. maybe it's alttabbing or maybe it's just the system freezing. In any case. To fix these I ideally want to reload the foundry game when it's not my turn.

However, doing this requires everyone else not do their turns and wait for me to reload as anything they do while foundry is loading will lead to a guaranteed desync. Because my computer is slow, this takes around a minute WITH all modules disabled. In organized play games where people are using bloated numbers of modules, this can take 3 minutes or more.

What I want is some system to automatically resolve desyncs without reloading. or to resync any changes that were made during the loading process.

An image showing the desync:
![image](https://github.com/foundryvtt/foundryvtt/assets/2016651/9772bc05-7e20-4495-8d9f-d3dbd5ae4d27)

### What ways of accessing Foundry can you encounter this issue in?

- [ ] Native App (Electron)
- [X] Chrome
- [X] Firefox
- [ ] Safari
- [ ] Other

### Reproduction Steps

Have a system with two players. Alice and Bob
Login to Alice in one browser window and Bob in a second (incognito) browser window
Reload Bob's window
While Bob is loading, in Alice's window add items to a token, or move a token around.
Notice Bob will not have these changes and the only way to resync is to wait for Bob to reload.
This happens even with no modules enabled.

### What core version are you reporting this for?

Version 10 Stable 291

### Bug Checklist

- [X] The issue occurs while all Modules are disabled

**Comment by Fyorl** [comment] 2023-06-19 11:11
Duplicate of #5624

**Closed by Fyorl** 2023-06-19 11:11 UTC
Labels: bug
