### ISSUE TITLE
Provide a method to retrieve the coordinates of all occupied grid spaces of a placeable.

### ISSUE THREAD

**Issue by krbz999** [foundryvtt/foundryvtt#9675] opened 2023-06-23 19:15 UTC
### User Experience

No native method exists for this, but it has been incredibly useful in a large number of modules and systems.

In an ideal world, a method like this would, on a **_square_** grid,
* Retrieve an array of x-y coordinates corresponding to the _centers_ of spaces that a placeable occupies (if the bounds of the placeable overlap this center coordinate).
* Optionally retrieve the top left coordinates instead.
* Optionally retrieve all grid space coordinates that a placeable _overlaps_ (if the bounds of the placeable contain any part of the grid space).
* Optionally retrieve all grid space coordinates that a placeable _touches_ (if touching at least an edge).

For the last two points, oddly shaped placeables should be considered, as well as placeables that are not placed in alignment with the grid.

On a hex grid, the above would still apply, but there would be some debate on what shape a placeable is and what they then occupy. Most placeables are still square (tiles for example), while tokens have a selection shape that fits the hex grid (though the `texture.src` may overflow this).

**Comment by dev7355608** [comment] 2024-08-07 10:29
Closing as duplicate of #10147.

**Closed by dev7355608** 2024-08-07 10:29 UTC
Labels: tokens, api
