### ISSUE TITLE
Shouldn't be able to drag-select tiles that are on the inactive Tiles layer

### ISSUE THREAD

**Issue by unsoluble** [foundryvtt/foundryvtt#8939] opened 2023-02-27 04:43 UTC
### What happened?

When you're on the Foreground Layer for tiles, you can't interact with tiles on the Background Layer, and vice-versa. This is currently working as expected.

But you _can_ drag-select tiles that are in the opposite layer. This probably shouldn't work, because you can't do anything with that selection anyway.

### What ways of accessing Foundry can you encounter this issue in?

- [X] Native App (Electron)
- [X] Chrome
- [X] Firefox
- [ ] Safari
- [ ] Other

### Reproduction Steps

1. Place a Tile on the Underfoot layer.
2. Switch the Foreground Layer toggle on.
3. Try clicking on the Tile (you can't; this is expected).
4. Try drag-selecting the Tile (you can; this is unexpected).

### What core version are you reporting this for?

10.291

### Bug Checklist

- [x] The issue occurs while all Modules are disabled

**Comment by dev7355608** [comment] 2023-02-27 17:50
Duplicate of #8700.

**Comment by unsoluble** [comment] 2023-02-27 17:51
God I hate/suck at GitHub search.

**Closed** 2023-03-02 15:13 UTC
Labels: bug, tiles
