### ISSUE TITLE
Add support for titles in an Application's headerButtons

### ISSUE THREAD

**Issue by aaclayton** [foundryvtt/foundryvtt#6726] opened 2022-02-21 14:11 UTC
Originally in GitLab by @geekswordsman

### Feature Summary

Currently header buttons added to an Application's headerButtons property do not support titles, which is necessary for proper a11y support.

### User Experience

For header buttons, this allows for icons only to be displayed and have the label, or longer text, shifted to the title on hover while also further enhancing Foundry's a11y support.

The default title can be set to the label, if no title is specified.

### Priority/Importance

Medium importance, for the a11y compliance.

**Comment by Fyorl** [comment] 2023-10-24 14:25
Closing as duplicate of #6421

**Closed by Fyorl** 2023-10-24 14:25 UTC
Labels: ui, a11y
