### ISSUE TITLE
Enforcement of `system` on packs does not need to occur on packs belonging to a System

### ISSUE THREAD

**Issue by cswendrowski** [foundryvtt/foundryvtt#7722] opened 2022-08-02 02:16 UTC
### User Experience

It is probably a safe assumption that Compendium packs declared by a System are for said System, and do not need strict enforcement of `system`

**Comment by aaclayton** [comment] 2022-08-02 02:45
Duplicate of https://github.com/foundryvtt/foundryvtt/issues/7678 which is already resolved.

**Closed by aaclayton** 2022-08-02 02:45 UTC
Labels: packages
