### ISSUE TITLE
Implement Number helpers for units\pixel conversions

### ISSUE THREAD

**Issue by theripper93** [foundryvtt/foundryvtt#8430] opened 2022-10-26 11:38 UTC
### User Experience

Especially when dealing with elevations (and other things in foundry in general) this can be a pain. having a built in helper would help greatly and it's a very quick and easy addition

```js
Number.prototype.toPixels = function(){
    return this * (canvas.scene.dimensions.size / canvas.scene.dimensions.distance);
};
Number.prototype.toUnits = function(){
    return this / (canvas.scene.dimensions.size / canvas.scene.dimensions.distance);
};
```

**Comment by aaclayton** [comment] 2023-03-27 20:58
Closing as duplicate of #9128

**Closed by aaclayton** 2023-03-27 20:58 UTC
Labels: api
