### ISSUE TITLE
PDF Journal Entry won't open

### ISSUE THREAD

**Issue by cswendrowski** [foundryvtt/foundryvtt#7980] opened 2022-08-29 15:40 UTC
From https://discord.com/channels/170995199584108546/956306859491471420/1013401162571067423

Create a PDF Journal Entry and open it.

![](https://media.discordapp.net/attachments/956306859491471420/1013401174034087997/unknown.png)

**Comment by aaclayton** [comment] 2022-08-29 16:17
Duplicate of https://github.com/foundryvtt/foundryvtt/issues/7927

**Closed by aaclayton** 2022-08-29 16:17 UTC
Labels: bug, journal
