### ISSUE TITLE
Fix unintended styling of the Asset Grid Size hint text in the Tile Browser

### ISSUE THREAD

**Issue by unsoluble** [foundryvtt/foundryvtt#10893] opened 2024-05-10 21:10 UTC
### What happened?

Something a bit funky is happening with the styling of the `Asset Grid Size` hint text in the Tile Browser:
<img width="516" alt="Screenshot 2024-05-10 at 2 05 31 PM" src="https://github.com/foundryvtt/foundryvtt/assets/801582/b31424e1-3a1c-41f0-bd4f-e64a3f80213a">

### What ways of accessing Foundry can you encounter this issue in?

- [ ] Native App (Electron)
- [X] Chrome
- [ ] Firefox
- [ ] Safari
- [ ] Other

### Reproduction Steps

1. Open the Tile Browser.

### What core version are you reporting this for?

12.322

### Bug Checklist

- [X] The issue occurs while all Modules are disabled

**Comment by krbz999** [comment] 2024-05-10 21:19
This is an issue with all hints in all light mode AppV2 instances, as well as the default styling for navigation elements (tabs).

**Comment by unsoluble** [comment] 2024-05-10 21:21
Hmm, I'm not seeing this specific effect anywhere else, though I _am_ seeing subtle mouseover changes on v2 app hints (which shouldn't be happening). Is there another related ticket already?

**Comment by aaclayton** [comment] 2024-05-11 13:42
Closing as duplicate of https://github.com/foundryvtt/foundryvtt/issues/10891

**Closed by aaclayton** 2024-05-11 13:42 UTC
Labels: bug
