### ISSUE TITLE
The illuminated area of a blinded token has a hard-coded scale

### ISSUE THREAD

**Issue by cswendrowski** [foundryvtt/foundryvtt#7974] opened 2022-08-29 15:20 UTC
From: https://discord.com/channels/170995199584108546/956306859491471420/1012434276966486137

Change the scale ratio of a token to something other than 1

1.0 vs 0.8
![](https://cdn.discordapp.com/attachments/956306859491471420/1012434275670446200/Screenshot_from_2022-08-25_13-48-58.png)

**Comment by Feu-Secret** [comment] 2022-08-30 15:32
I cant reproduce the bug report. Rescaling a token image also rescales the blindness area.

**Comment by Feu-Secret** [comment] 2022-08-30 19:05
Duplicate of https://github.com/foundryvtt/foundryvtt/issues/7520

**Closed by Feu-Secret** 2022-08-30 19:05 UTC
Labels: bug, nonrepro, lighting/fog
