### ISSUE TITLE
Pins should have the avility to link to Journal Sub headings

### ISSUE THREAD

**Issue by ryanwalder** [foundryvtt/foundryvtt#9684] opened 2023-06-26 11:30 UTC
### User Experience

When creating a Pin on a Scene you can link the pin to a specific page within a journal:

![image](https://github.com/foundryvtt/foundryvtt/assets/10901150/88168233-6e38-483c-9332-08fb0d72b0dc)

Given you can link Journal Page Sub Headings in EnrichedHTML fields (like in other Journal Sub Pages):

![image](https://github.com/foundryvtt/foundryvtt/assets/10901150/c730505c-c2d4-4116-8d2a-7ff902923b2d)

It would be beneficial to be able to do the same within a Pin Page:

![image](https://github.com/foundryvtt/foundryvtt/assets/10901150/b1a3f932-50bf-4529-9183-91abbb8f5071)

**Comment by Fyorl** [comment] 2023-06-26 12:29
Duplicate of #7448

**Closed by Fyorl** 2023-06-26 12:29 UTC
