### ISSUE TITLE
Call initializePacks before the setup hook

### ISSUE THREAD

**Issue by esb** [foundryvtt/foundryvtt#9129] opened 2023-03-27 20:36 UTC
### User Experience

I'm currently developing a DND 3.5 system, and I'm using a Compendium to store and manage information about Special Materials that can be used in Weapon and Armour creation.

It would be extremely useful if the packs could be initialized before the setup hook is called so that a Compendium could be used to populate and modify otherwise static information. In this instance, I am trying to use the materials defined in the compendium to populate selections of materials that can be configured for a weapon or armour. I also want to be able to dynamically add the materials available to lists of damage types that are used to configure Damage Reduction attributes.

Using Compendiums in this way avoids having to hard-code lists of items and allows the system to be easier to manage and extend. Having access to the packs at setup time would help with that goal.

**Comment by aaclayton** [comment] 2023-03-28 16:00
This change has been made for V11, please see https://github.com/foundryvtt/foundryvtt/issues/8510

Closing this issue as duplicate.

**Closed by aaclayton** 2023-03-28 16:00 UTC

**Comment by esb** [comment] 2023-03-28 22:04
I checked the code for V11, and yes, the setup hook has been moved after the call to initializePacks, but this doesn't really solve this particular use case as the call to initializeDocuments was moved as well!

What is needed is a way to get the packs initialized, and then use that data to build internal structures that can be used when the documents are loaded. In other words, we need an optional hook BETWEEN initializePacks and initializeDocuments that can be called to do the necessary initialization.

I hope this makes sense. For example, with special materials, I need to populate a list of available materials from the Compendium and this needs to be available BEFORE I load weapon and armour documents that reference that list.

**Comment by Fyorl** [comment] 2023-03-28 22:36
> I hope this makes sense. For example, with special materials, I need to populate a list of available materials from the Compendium and this needs to be available BEFORE I load weapon and armour documents that reference that list.

Assuming that information is available purely from the compendium index, then it should be possible to reference it during Document preparation. Is there anything blocking you from pursuing that solution? If you need to retrieve full Document instances from the compendium, then even adding a hook here will not help your use-case, since retrieving a Document from a compendium is an asynchronous operation

**Comment by esb** [comment] 2023-03-28 22:51
The data from the compendium needs to be collated and reduced to provide a list of special materials, so you don't really want to be doing this in an "on demand" for every access during document preparation.

I'm aware that it is asynchronous. I'm already monkey patching this on V10 and it works fine.

**Comment by aaclayton** [comment] 2023-03-29 00:31
I don't want to diminish your request, but "I was able to do this by monkeypatching in v10" isn't really a great justification for the feature request. What @Fyorl is asking is whether (and if not, why not) you are able to use compendium indices as the source data for your workflow?

**Comment by esb** [comment] 2023-03-29 02:41
> I don't want to diminish your request, but "I was able to do this by monkeypatching in v10" isn't really a great justification for the feature request. What @Fyorl is asking is whether (and if not, why not) you are able to use compendium indices as the source data for your workflow?

Processing the compendium data during document preparation is not really an effective way to go.

In the example I'm dealing with, I have created a Compendium of Materials, consisting of entries for possible materials that can be used in the crafting of weapons and armour. For example, there's an Adamantine entry, which encapsulates the characteristics of that material (cost, weight and damage effects), and also provides the rules for where the material can be used.

Now, documents representing weapons, armour and other items will reference lists of base materials, special materials and so on to allow the item to be configured with the desired special material. This allows the user to configure a dagger, for example to be an adamantine or alchemical silver weapon, but not a darkwood weapon. These lists are built up from the compendium entries by reading the entries and apply filters as appropriate. My current design allows me to build these lists one time only at startup and also to allow me to merge them with other static lists such as the list of possible damage types to build a set of options that can be used to configure damage reduction attributes for armour and shields.

Given the above complexity, it's not really an option to consider building these lists each and every time a document is referenced, which is why I'm trying to build these lists at startup time as they are static, but dependent on the contents of a Compendium.

The reference to patching V10 wasn't meant as a justification for the feature, but merely to highlight that the asynchronous nature of reading the compendium data wasn't really a show stopper as was implied in the response.

**Comment by aaclayton** [comment] 2023-03-29 02:45
We aren't proposing that you build these lists every time a document is referenced. We are proposing that you use the compendium index to construct these lists. Do you understand what I'm talkikng about when I reference the compendium index?

**Comment by esb** [comment] 2023-03-29 02:54
Unless I'm mistaken, my current approach is to get the keys from the index, then use those keys to read in all the compendium documents. These are then saved in an internal (in memory) registry which is used to build static lists of materials. I need the internal documents of each material in order to test the various flags and settings that define the material. There aren't a lot of entries, so having it in memory is not a big deal.

Is there a better way to do this?

**Comment by esb** [comment] 2023-03-29 03:04
I see from the discussion of https://github.com/foundryvtt/foundryvtt/issues/8776 that there has been a push to increase the amount of information provided in the compendium index. The counter to this is, of course, that it adds to the burden of data that needs to be loaded (which lead to the socket compression discussion)!

Would something like I'm proposing here be of help. If there's a hook (async) available after pack initialization, then there's an opportunity for some sort of post processing on the compendium data before continuing with the document loading. If you don't need it, then there's no penalty to anyone, but the system developer gets the opportunity to do something that's needed for a specific game system design.

**Comment by Fyorl** [comment] 2023-03-29 12:16
> Unless I'm mistaken, my current approach is to get the keys from the index, then use those keys to read in all the compendium documents.

That's kind of my point: There is no concept of async hooks in foundry. Foundry does not `await` hook calls (by design), so requesting a hook between `initializePacks` and `initializeDocuments` will not solve your use-case. I'm not sure what exactly you're monkey-patching in v10 or the details of how it works, so I can't comment on that, but it seems that we need to look for a different solution here, since performing this processing will also not work as part of data preparation for the same reason (data preparation is synchronous).

I think if we could understand how your current solution works, since it's apparently working fine for you, we might be able to suggest some ways to do it without monkey-patching.

**Comment by esb** [comment] 2023-03-29 20:52
Here's my current code to monkey-patch in some async initialization code after `initializePacks`.

```javascript
// Patch initializePacks to add code after the initialization.
{
  const origSetupGame = Game.prototype.setupGame;
  const origInitializePacks = Game.prototype.initializePacks;

  Game.prototype.initializePacks = async function() {
    // Do nothing but restore original function
    Game.prototype.initializePacks = origInitializePacks;
    return;
  };

  Game.prototype.setupGame = async function() {
    origInitializePacks.call(this);

    // Once the packs have been initialized, we can initialize the Materials registry
    dnd35e.registry.materials = new Materials();

    // We need to wait until the materials compendium is loaded.
    // This is not normally done by Foundry, which is why we hijack the function to
    // call it before the normal setupGame sequence.
    await dnd35e.registry.materials.init();

    // Now call original startup sequence
    origSetupGame.call(this);
    return;
  };
}
```
