### ISSUE TITLE
Switch to using header menus instead of buttons

### ISSUE THREAD

**Issue by kristianserrano** [foundryvtt/foundryvtt#10519] opened 2024-03-14 19:55 UTC
### User Experience

The header of an app window has limited space, and a lot of modules and systems compete for that real estate, often overcrowding it and causing core features to fall off or become concealed.

An easy solution for this would be to give application windows a menu bar among which would be a Tools into which modules can add menu items. This suggestion would be primarily for Documents and not every app window. It might look something like this.

- File (for Documents only)
  - Open (A list of World Documents of the same type)
  - Recent  (A list of recently opened World Documents of the same type)
  - Duplicate
  - Save as... (Duplicate with edited name and select which Folder)
- Edit
  - Sheet
  - Related registered settings from the system or modules
  - [Additional functional menu items from the system such as toggling Edit mode for 5e, Tweaks for SWADE, Prototype Tokens for Actors, etc.]
- Tools (Documents only)
  - Copy ID
  - Copy UUID
  - Send to console (for developers and users troubleshooting)
  - [Additional functional menu items from the system or modules such as Popout!]
- Window
  - Minimize/Collapse
  - Maximize
  - Keep on top
  - Close
- Help
  - About (if a Document, opens dialog with ID, UUID, and maybe Folder "location")
  - [Additional menu items from the system or modules that link to external URLs or Journal Entries for documentation/instructions or that open Tours]

I know a lot of these suggested menu items are technically new features. I don't mean for this issue to serve as a feature request for those; they're just added to illustrate what might be possible with a set of menus versus buttons.

**Comment by aaclayton** [comment] 2024-03-14 20:52
Closing as a duplicate of #3273

**Closed by aaclayton** 2024-03-14 20:52 UTC
