### ISSUE TITLE
Add a means of auto-toggling a vision/detection mode according to scene darkness

### ISSUE THREAD

**Issue by stwlam** [foundryvtt/foundryvtt#8080] opened 2022-09-04 19:38 UTC
### User Experience

This would be similar and an alternative to utilizing a scene's `globalLightThreshold`: a vision or detection mode could enable or disable itself depending on the darkness level of a scene. In this way, `globalLight` could always be turned off, but tokens representing actors with ordinary human eyeballs could see so long as the "sun" is out. Conversely, it could be a means of implementing a "light blindness" mechanic, to be applied to a subterranean creature that can only see in the dark.

**Comment by stwlam** [comment] 2022-10-15 21:46
I missed it before, but my feature request looks to be a duplicate of #7289--though I'm not sure what ambiguities there may be if there is a configurable threshold similar to the scene `globalLightThreshold`.

**Comment by aaclayton** [comment] 2022-10-16 17:57
Closing as duplicate of #7289

**Closed by aaclayton** 2022-10-16 17:57 UTC
Labels: vision
