### ISSUE TITLE
Unable to get available packages

### ISSUE THREAD

**Issue by Wameuh** [foundryvtt/foundryvtt#11533] opened 2024-08-03 17:47 UTC
### What happened?

I have recently installed a new FoundryVTT installation. But I am unable to get the list of available package:

```
key.split is not a function or its return value is not iterable
```

### What ways of accessing Foundry can you encounter this issue in?

- [ ] Native App (Electron)
- [X] Chrome
- [ ] Firefox
- [ ] Safari
- [ ] Other

### Reproduction Steps

Install Foundry, go on Add-on Modules and Install Module. Wait for the package.

### What core version are you reporting this for?

Version 12 Stable - Build 330

### Relevant log output

```shell
key.split is not a function or its return value is not iterable
```
```


### Bug Checklist

- [*] The issue occurs while all Modules are disabled

**Comment by JPMeehan** [comment] 2024-08-03 20:49
Did you do a clean install? Sounds like you should hit up the _troubleshooting channel on the discord first.

**Comment by aaclayton** [comment] 2024-08-05 13:28
We'll be happy to provide troubleshooting support there. Closing this issue accordingly.

**Comment by Norc** [comment] 2024-08-05 14:00
I am not certain that this should be deleted. The `key.split` error is specific and is coming up somewhat frequently recently, and it was not a symptom of module updating issues until quite recently.

I'd like to keep this open to investigate a bit further.

**Comment by arnesahlberg** [comment] 2024-08-21 08:45
I keep getting this as well.

**Comment by Raileth** [comment] 2024-08-21 10:38
I'm getting this error too for all module / system updates - I'm on build 331 and updated fine yesterday on the same build.

**Comment by Norc** [comment] 2024-08-21 12:40
Hey folks @arnesahlberg, could you try this again? We seem to have had a temporary, partial disruption servicing these requests that may have improved now.

**Comment by Ermissu** [comment] 2024-09-26 22:55
I am with this problem

**Comment by Turkeyworth** [comment] 2024-09-28 03:56
Currently having this issue as well, not sure what caused it as it was working fine 12 hours ago.

**Comment by kontokontovtt** [comment] 2024-09-29 11:28
I am also keep getting this since yesterday

**Comment by Xylospongium1995** [comment] 2024-10-09 18:33
I also have the same problem since last week

**Comment by unsoluble** [comment] 2024-10-09 18:34
Folks, please head to the [Discord](https://discord.gg/foundryvtt) for all general troubleshooting.

**Comment by Norc** [comment] 2024-10-28 15:46
As an update, this issue continues to crop up sporadically. In particular, reports of this issue only seem to happen in bursts during times when our web server seems to be under stress.

Here's the community's findings so far, and my own thoughts:

## Repro Steps

@anathemamask provided reproduction steps for this issue. I verified that these steps work for me also:

1. Launch via nodeJS
2. leave the browser window open to localhost:30000
3. kill the server process
4. click "update" on a package before the browser realises the connection is dead5. 

## Troubleshooting tips
If you are encountering this issue, the general recommendation is to reboot everything (computer, router, wifi). Using a different network can also be helpful (such as mobile tethering/VPN etc.) [Changing DNS servers](https://www.pcmag.com/how-to/how-and-why-to-change-your-dns-server) may also help.

## Potential Resolution
I think two potential fixes here might be helpful:

**1. Improving the wording of the "Key.split" Error:**
_Current:_ "key.split is not a function or its return value is not iterable."
_Recommended:_ "Failed to check for updates. Please try again later." (or something similar)
I'm breaking this out into a separate issue, as I think this is more minor change that could bring some immediate UX improvement at least.

**2. Improving the reliability of the update request**
Naively, it seems that sometimes a temporary network glitch happens and then this failure state becomes "stuck" (cached?) in some way. I remember reading in an internal discussion about the socket.io package that an [imporperly configured websocket](https://socket.io/docs/v4/faq/#what-are-the-features-provided-by-socketio-over-plain-websocket) may cause this? 

Just a shot in the dark, so please disregard if I'm wildly wrong.

**Closed** 2024-11-14 20:39 UTC
Labels: bug, nonrepro
