### ISSUE TITLE
Better Handling of System requirements for Packs

### ISSUE THREAD

**Issue by theripper93** [foundryvtt/foundryvtt#7692] opened 2022-07-29 18:35 UTC
### User Experience

At the moment packs require a system or they will fail to validate. I'm assuming a bugfix is coming to ignore this field if the module\system also declares a system dependency?

Even with such fix, my fear is that many users made their own "Shared Compendium" module, that i'm sure will not have any kind of system tags whatsoever. When regular users update to V10 there will be an unending stream of "Why my shared compendium isn't working" posts, from users that probably just copy pasted a template and are not tech savy enought to fix them.

**Comment by aaclayton** [comment] 2022-07-30 00:26
Duplicate of #7678, copying comment over there.

**Closed by aaclayton** 2022-07-30 00:26 UTC
