### ISSUE TITLE
Drag icon for imported actors sometimes incorrect

### ISSUE THREAD

**Issue by Thorarin** [foundryvtt/foundryvtt#10470] opened 2024-03-01 08:54 UTC
### What happened?

I was dragging some NPCs into a scene and I noticed that the token icon it shows while first dragging them onto the scene is not always correct. The first actor I dragged showed no icon, dragging the second actor might show the token for the first actor I dragged, etc. I would expect the drag icon to match what I'm actually dragging.

### What ways of accessing Foundry can you encounter this issue in?

- [ ] Native App (Electron)
- [X] Chrome
- [X] Firefox
- [ ] Safari
- [ ] Other

### Reproduction Steps

1. Have the Dungeons of Drakkenheim module installed (probably also works with other content modules though)
2. Create a new empty world and load it
3. Enable the Dungeon of Drakkenheim module
4. Import Adventure
5. Close the Journal entry
6. Optionally disable the Dungeons of Drakkenheim module again
7. Start dragging NPCs onto the scene and observe the drag icons: Sometimes there won't be any drag icon, sometimes they will be of the previously dragged NPC.

This seems easier to reproduce in Firefox, but I've also seen it happen in Chrome.

I have 15 NPCs that were freshly imported from a premium content module (Dungeons of Drakkenheim), but I disabled the module since then. While dragging any of the imported NPCs onto the scene, the wrong graphics were being shown, leading me to think that I misclicked. After dropping the token it shows the right graphics, though. 

I was able to reproduce it in two different browsers and reloading the UI several times. The first time I encountered the bug I had imported the adventure in Firefox, but after noticing the bug closed Firefox and opened Chrome (without reloading the world in Foundry), only to find the same problem. Potentially switching worlds in the Foundry VTT instance resolves the issue, because I tried to reproduce it in another world I already had, was not able to do so, then switching back to the DoD world it seems to no longer be reproducible either. I had to follow the repro steps again with a new world to see the problem come back.

To me, it appears like the drag icon seems to be generated asynchronously and lazily. Sometimes it isn't generated on time or it isn't applied? Repeated dragging of the same token seems to always show the right graphics.

### What core version are you reporting this for?

Version 11 build 315

### Relevant log output

```shell
N/A
```

### Bug Checklist

- [X] The issue occurs while all Modules are disabled

**Comment by aaclayton** [comment] 2024-03-01 20:43
Closing as duplicate of #2789

**Closed** 2024-03-01 20:43 UTC
Labels: bug
