### ISSUE TITLE
The Wall Configuration dialog can only be opened by double-clicking the Wall's endpoints

### ISSUE THREAD

**Issue by Norc** [foundryvtt/foundryvtt#10888] opened 2024-05-10 17:47 UTC
### What happened?

Double-clicking the line segment part of walls no longer allows you to edit the walls.  Instead, you have to click one of the Wall's two end-points to open the Wall Configuration dialog.

### What ways of accessing Foundry can you encounter this issue in?

- [X] Native App (Electron)
- [ ] Chrome
- [ ] Firefox
- [ ] Safari
- [ ] Other

### Reproduction Steps

1. Enable the Select Walls tool
2. Double-click the line segment portion of a Wall

Current: Nothing happens other than controlling the Wall
Preferred: The Wall is controlled and the Configure Wall dialog displays for that Wall

### What core version are you reporting this for?

12.322

### Bug Checklist

- [X] The issue occurs while all Modules are disabled

**Comment by Fyorl** [comment] 2024-05-20 13:47
Closing as duplicate of #10821

**Closed by Fyorl** 2024-05-20 13:47 UTC
Labels: bug, walls
