### ISSUE TITLE
Going back in initiative order gives a turn to the defeated enemies

### ISSUE THREAD

**Issue by TrofimSelbs** [foundryvtt/foundryvtt#11480] opened 2024-06-26 14:35 UTC
- I have disabled all other modules
- Foundry and System version Foundry v11 315
- D&D 3.1.2
- MacOS Sonoma, Chrome, Forge VTT

**Short description of bug** 
Going back in initiative order gives a turn to the defeated enemies

**Steps to reproduce the bug**
1. Start a fight with 3+ tokens
2. Mark one of them as defeated (you will see it disappear from initiative when you do)
3. Go forward in initiative further than this token was (in initiative)
4. Go back in initiative
5. You will see that the defeated token is given a turn.
https://github.com/foundryvtt/dnd5e/assets/124184162/a9f9f073-2b9a-4a2d-a696-5cdd9229eb91

**Comment by aaclayton** [comment] 2024-07-19 14:00
This actually was an intentional feature. **Skip Defeated** automatically bypasses over defeated enemies when moving forward in initiative, but it intentionally *does not skip* them when moving backwards in order. Sometimes you need to do something on a defeated enemy turn, so the design was that you skip them when advancing but you can go back if you need to.

We could discuss changing this, but it's not a bug.

**Comment by TrofimSelbs** [comment] 2024-07-25 13:21
Thank you for your reply! Got it, it is not a bug. 

You said, "We could discuss changing this, but it's not a bug". It would be nice to change that behavior or be able to choose it in settings. I sometimes need to go back a turn to some previous combatant, but I never need to "do something on a defeated enemy turn", and I can't think of a use case here, but maybe it is needed for some people ¯\_(ツ)_/¯. It is frustrating though to suddenly have a dead guy get a turn when you didn't intend or expect it

**Comment by aaclayton** [comment] 2024-10-28 17:14
Closing as wontfix, sorry!

**Closed by aaclayton** 2024-10-28 17:14 UTC
Labels: bug, combat
