### ISSUE TITLE
Safari version detection emits false positives

### ISSUE THREAD

**Issue by Fyorl** [foundryvtt/foundryvtt#10058] opened 2023-10-02 16:32 UTC
Originally reported by rathlord https://discord.com/channels/170995199584108546/1065764070680186930/1157682125177368586

**ALL MODULES DISABLED?** Yes/NA
**OS, Hosting, Browser (if applicable)**: Ubuntu, self hosted, Safari
**Short Description of bug**: Shows unsupported version even when version matches recommended
**Simple steps to reproduce the bug**: Connect to Foundry using Safari on the latest version
**Screenshots and/or console errors**:

![image](https://github.com/foundryvtt/foundryvtt/assets/207433/710bc687-702c-45fa-91bd-ea40f4a69f50)

**Comment by aaclayton** [comment] 2024-03-26 21:22
Closing as duplicate of https://github.com/foundryvtt/foundryvtt/issues/7750

**Closed by aaclayton** 2024-03-26 21:22 UTC
Labels: bug, browser
