### ISSUE TITLE
unexpected window behavior

### ISSUE THREAD

**Issue by Drental** [foundryvtt/foundryvtt#9545] opened 2023-06-03 18:47 UTC
### What happened?

the view through the south window gets larger when my character approaches the left window, and then the south wall becomes fully opaque when stepping away from the attenuation distance.

### What ways of accessing Foundry can you encounter this issue in?

- [ ] Native App (Electron)
- [X] Chrome
- [ ] Firefox
- [ ] Safari
- [ ] Other

### Reproduction Steps

![image](https://github.com/foundryvtt/foundryvtt/assets/74384067/80730e6f-2f7b-4429-b344-1134dcf56a5f)
![image](https://github.com/foundryvtt/foundryvtt/assets/74384067/bc0956c6-4f6a-4f68-909d-73f0c5ec7cab)
![image](https://github.com/foundryvtt/foundryvtt/assets/74384067/d791bbcc-9da1-48a1-8a0e-34c1b1760f40)

### What core version are you reporting this for?

11.300

### Bug Checklist

- [X] The issue occurs while all Modules are disabled

**Comment by dev7355608** [comment] 2023-06-03 19:13
Duplicate of #9531.

**Closed by dev7355608** 2023-06-03 19:13 UTC
Labels: bug, duplicate, todelete, walls, vision
